-- ----------------------------
-- Records of country 
-- ----------------------------
INSERT INTO "country" ("id", "country_name", "country_code", "country_tld", "continent") VALUES
(1, 'Georgia', 'GE', '.GE', 'Asia'),
(2, 'Afghanistan', 'AF', '.AF', 'Asia'),
(3, 'Åland Islands', 'AX', '.AX', 'Europe'),
(4, 'Albania', 'AL', '.AL', 'Europe'),
(5, 'Algeria', 'DZ', '.DZ', 'Africa'),
(6, 'American Samoa', 'AS', '.AS', 'Oceania'),
(7, 'Andorra', 'AD', '.AD', 'Europe'),
(8, 'Anguilla', 'AI', '.AI', 'North America'),
(9, 'Antarctica', 'AQ', '.AQ', 'Antarctica'),
(10, 'Antigua and Barbuda', 'AG', '.AG', 'North America'),
(11, 'Armenia', 'AM', '.AM', 'Asia'),
(12, 'Aruba', 'AW', '.AW', 'North America'),
(13, 'Bahamas', 'BS', '.BS', 'North America'),
(14, 'Bahrain', 'BH', '.BH', 'Asia'),
(15, 'Barbados', 'BB', '.BB', 'North America'),
(16, 'Benin', 'BJ', '.BJ', 'Africa'),
(17, 'Bermuda', 'BM', '.BM', 'North America'),
(18, 'Bhutan', 'BT', '.BT', 'Asia'),
(19, 'Bolivia', 'BO', '.BO', 'South America'),
(20, 'Botswana', 'BW', '.BW', 'Africa'),
(21, 'Bouvet Island', 'BV', '.BV', 'Antarctica'),
(22, 'British Indian Ocean Territory', 'IO', '.IO', 'Africa'),
(23, 'Brunei Darussalam', 'BN', '.BN', 'Asia'),
(24, 'Burkina Faso', 'BF', '.BF', 'Africa'),
(25, 'Burundi', 'BI', '.BI', 'Africa'),
(26, 'Cambodia', 'KH', '.KH', 'Asia'),
(27, 'Cameroon', 'CM', '.CM', 'Africa'),
(28, 'Cape Verde', 'CV', '.CV', 'Africa'),
(29, 'Central African Republic', 'CF', '.CF', 'Africa'),
(30, 'Chad', 'TD', '.TD', 'Africa'),
(31, 'Christmas Island', 'CX', '.CX', 'Oceania'),
(32, 'Cocos (Keeling) Islands', 'CC', '.CC', 'Oceania'),
(33, 'Comoros', 'KM', '.KM', 'Africa'),
(34, 'Congo', 'CG', '.CG', 'Africa'),
(35, 'The Democratic Republic Of The Congo', 'CD', '.CD', 'Africa'),
(36, 'Cook Islands', 'CK', '.CK', 'Oceania'),
(37, 'Costa Rica', 'CR', '.CR', 'North America'),
(38, 'Cote Divoire', 'CI', '.CI', 'Africa'),
(39, 'Cuba', 'CU', '.CU', 'North America'),
(40, 'Djibouti', 'DJ', '.DJ', 'Africa'),
(41, 'Dominica', 'DM', '.DM', 'North America'),
(42, 'Dominican Republic', 'DO', '.DO', 'North America'),
(43, 'El Salvador', 'SV', '.SV', 'North America'),
(44, 'Equatorial Guinea', 'GQ', '.GQ', 'Africa'),
(45, 'Eritrea', 'ER', '.ER', 'Africa'),
(46, 'Ethiopia', 'ET', '.ET', 'Africa'),
(47, 'Falkland Islands (Malvinas)', 'FK', '.FK', 'South America'),
(48, 'Faroe Islands', 'FO', '.FO', 'Europe'),
(49, 'Fiji', 'FJ', '.FJ', 'Oceania'),
(50, 'French Guiana', 'GF', '.GF', 'South America'),
(51, 'French Polynesia', 'PF', '.PF', 'Oceania'),
(52, 'French Southern Territories', 'TF', '.TF', 'Antarctica'),
(53, 'Gabon', 'GA', '.GA', 'Africa'),
(54, 'Gambia', 'GM', '.GM', 'Africa'),
(55, 'Ghana', 'GH', '.GH', 'Africa'),
(56, 'Gibraltar', 'GI', '.GI', 'Europe'),
(57, 'Greenland', 'GL', '.GL', 'North America'),
(58, 'Grenada', 'GD', '.GD', 'North America'),
(59, 'Guadeloupe', 'GP', '.GP', 'North America'),
(60, 'Guam', 'GU', '.GU', 'Oceania'),
(61, 'Guatemala', 'GT', '.GT', 'North America'),
(62, 'Guernsey', 'GG', '.GG', NULL),
(63, 'Guinea', 'GN', '.GN', 'Africa'),
(64, 'Guinea-Bissau', 'GW', '.GW', 'Africa'),
(65, 'Guyana', 'GY', '.GY', 'South America'),
(66, 'Haiti', 'HT', '.HT', 'North America'),
(67, 'Heard and McDonald Islands', 'HM', '.HM', 'Antarctica'),
(68, 'Holy See (Vatican City State)', 'VA', '.VA', 'Europe'),
(69, 'Honduras', 'HN', '.HN', 'North America'),
(70, 'Iceland', 'IS', '.IS', 'Europe'),
(71, 'Iraq', 'IQ', '.IQ', 'Asia'),
(72, 'Isle of Man', 'IM', '.IM', NULL),
(73, 'Jamaica', 'JM', '.JM', 'North America'),
(74, 'Jersey', 'JE', '.JE', NULL),
(75, 'Jordan', 'JO', '.JO', 'Asia'),
(76, 'Argentina', 'AR', '.AR', 'South America'),
(77, 'Austria', 'AT', '.AT', 'Europe'),
(78, 'Australia', 'AU', '.AU', 'Oceania'),
(79, 'Azerbaijan', 'AZ', '.AZ', 'Asia'),
(80, 'Bosnia and Herzegovina', 'BA', '.BA', 'Europe'),
(81, 'Bangladesh', 'BD', '.BD', 'Asia'),
(82, 'Belgium', 'BE', '.BE', 'Europe'),
(83, 'Bulgaria', 'BG', '.BG', 'Europe'),
(84, 'Brazil', 'BR', '.BR', 'South America'),
(85, 'Belarus', 'BY', '.BY', 'Europe'),
(86, 'Belize', 'BZ', '.BZ', 'North America'),
(87, 'Canada', 'CA', '.CA', 'North America'),
(88, 'Chile', 'CL', '.CL', 'South America'),
(89, 'China', 'CN', '.CN', 'Asia'),
(90, 'Colombia', 'CO', '.CO', 'South America'),
(91, 'Cyprus', 'CY', '.CY', 'Asia'),
(92, 'Czech Republic', 'CZ', '.CZ', 'Europe'),
(93, 'Germany', 'DE', '.DE', 'Europe'),
(94, 'Denmark', 'DK', '.DK', 'Europe'),
(95, 'Ecuador', 'EC', '.EC', 'South America'),
(96, 'Estonia', 'EE', '.EE', 'Europe'),
(97, 'Egypt', 'EG', '.EG', 'Africa'),
(98, 'Finland', 'FI', '.FI', 'Europe'),
(99, 'France', 'FR', '.FR', 'Europe'),
(100, 'Greece', 'GR', '.GR', 'Europe'),
(101, 'Hong Kong', 'HK', '.HK', 'Asia'),
(102, 'Croatia', 'HR', '.HR', 'Europe'),
(103, 'Hungary', 'HU', '.HU', 'Europe'),
(104, 'Indonesia', 'ID', '.ID', 'Asia'),
(105, 'Ireland', 'IE', '.IE', 'Europe'),
(106, 'Israel', 'IL', '.IL', 'Asia'),
(107, 'India', 'IN', '.IN', 'Asia'),
(108, 'Iran', 'IR', '.IR', 'Asia'),
(109, 'Italy', 'IT', '.IT', 'Europe'),
(110, 'Japan', 'JP', '.JP', 'Asia'),
(111, 'Cayman Islands', 'KY', '.KY', 'North America'),
(112, 'Kazakhstan', 'KZ', '.KZ', 'Asia'),
(113, 'Kiribati', 'KI', '.KI', 'Oceania'),
(114, 'North Korea', 'KP', '.KP', 'Asia'),
(115, 'Kuwait', 'KW', '.KW', 'Asia'),
(116, 'Kyrgyzstan', 'KG', '.KG', 'Asia'),
(117, 'Lao People', 'LA', '.LA', 'Asia'),
(118, 'Lebanon', 'LB', '.LB', 'Asia'),
(119, 'Lesotho', 'LS', '.LS', 'Africa'),
(120, 'Liberia', 'LR', '.LR', 'Africa'),
(121, 'Libya', 'LY', '.LY', 'Africa'),
(122, 'Liechtenstein', 'LI', '.LI', 'Europe'),
(123, 'Macao', 'MO', '.MO', 'Asia'),
(124, 'Madagascar', 'MG', '.MG', 'Africa'),
(125, 'Malawi', 'MW', '.MW', 'Africa'),
(126, 'Maldives', 'MV', '.MV', 'Asia'),
(127, 'Mali', 'ML', '.ML', 'Africa'),
(128, 'Marshall Islands', 'MH', '.MH', 'Oceania'),
(129, 'Martinique', 'MQ', '.MQ', 'North America'),
(130, 'Mauritania', 'MR', '.MR', 'Africa'),
(131, 'Mauritius', 'MU', '.MU', 'Africa'),
(132, 'Mayotte', 'YT', '.YT', 'Africa'),
(133, 'Micronesia', 'FM', '.FM', 'Oceania'),
(134, 'Monaco', 'MC', '.MC', 'Europe'),
(135, 'Mongolia', 'MN', '.MN', 'Asia'),
(136, 'Montenegro', 'ME', '.ME', 'Europe'),
(137, 'Montserrat', 'MS', '.MS', 'North America'),
(138, 'Morocco', 'MA', '.MA', 'Africa'),
(139, 'Mozambique', 'MZ', '.MZ', 'Africa'),
(140, 'Myanmar', 'MM', '.MM', 'Asia'),
(141, 'Namibia', 'NA', '.NA', 'Africa'),
(142, 'Nauru', 'NR', '.NR', 'Oceania'),
(143, 'Netherlands Antilles', 'AN', '.AN', NULL),
(144, 'New Caledonia', 'NC', '.NC', 'Oceania'),
(145, 'Nicaragua', 'NI', '.NI', 'North America'),
(146, 'Niger', 'NE', '.NE', 'Africa'),
(147, 'Nigeria', 'NG', '.NG', 'Africa'),
(148, 'Niue', 'NU', '.NU', 'Oceania'),
(149, 'Norfolk Island', 'NF', '.NF', 'Oceania'),
(150, 'Northern Mariana Islands', 'MP', '.MP', 'Oceania'),
(151, 'Oman', 'OM', '.OM', 'Asia'),
(152, 'Palau', 'PW', '.PW', 'Oceania'),
(153, 'Palestine', 'PS', '.PS', 'Asia'),
(154, 'Papua New Guinea', 'PG', '.PG', 'Oceania'),
(155, 'Paraguay', 'PY', '.PY', 'South America'),
(156, 'Peru', 'PE', '.PE', 'South America'),
(157, 'Philippines', 'PH', '.PH', 'Asia'),
(158, 'Saint Pierre And Miquelon', 'PM', '.PM', 'North America'),
(159, 'Pitcairn', 'PN', '.PN', 'Oceania'),
(160, 'Puerto Rico', 'PR', '.PR', 'North America'),
(161, 'Réunion', 'RE', '.RE', 'Africa'),
(162, 'Rwanda', 'RW', '.RW', 'Africa'),
(163, 'Saint Helena', 'SH', '.SH', 'Africa'),
(164, 'Saint Kitts And Nevis', 'KN', '.KN', 'North America'),
(165, 'Saint Lucia', 'LC', '.LC', 'North America'),
(166, 'Saint Vincent And The Grenedines', 'VC', '.VC', 'North America'),
(167, 'Samoa', 'WS', '.WS', 'Oceania'),
(168, 'San Marino', 'SM', '.SM', 'Europe'),
(169, 'Sao Tome and Principe', 'ST', '.ST', 'Africa'),
(170, 'Senegal', 'SN', '.SN', 'Africa'),
(171, 'Sierra Leone', 'SL', '.SL', 'Africa'),
(172, 'Slovenia', 'SI', '.SI', 'Europe'),
(173, 'Solomon Islands', 'SB', '.SB', 'Oceania'),
(174, 'Somalia', 'SO', '.SO', 'Africa'),
(175, 'South Georgia', 'GS', '.GS', 'Antarctica'),
(176, 'Sri Lanka', 'LK', '.LK', 'Asia'),
(177, 'Sudan', 'SD', '.SD', 'Africa'),
(178, 'Suriname', 'SR', '.SR', 'South America'),
(179, 'Svalbard And Jan Mayen', 'SJ', '.SJ', 'Europe'),
(180, 'Swaziland', 'SZ', '.SZ', 'Africa'),
(181, 'Syrian Arab Republic', 'SY', '.SY', 'Asia'),
(182, 'Tajikistan', 'TJ', '.TJ', 'Asia'),
(183, 'Tanzania', 'TZ', '.TZ', 'Africa'),
(184, 'Timor-Leste', 'TL', '.TL', 'Asia'),
(185, 'Togo', 'TG', '.TG', 'Africa'),
(186, 'Tokelau', 'TK', '.TK', 'Oceania'),
(187, 'Tonga', 'TO', '.TO', 'Oceania'),
(188, 'Trinidad and Tobago', 'TT', '.TT', 'North America'),
(189, 'Spain', 'ES', '.ES', 'Europe'),
(190, 'Kenya', 'KE', '.KE', 'Africa'),
(191, 'South Korea', 'KR', '.KR', 'Asia'),
(192, 'Lithuania', 'LT', '.LT', 'Europe'),
(193, 'Luxembourg', 'LU', '.LU', 'Europe'),
(194, 'Latvia', 'LV', '.LV', 'Europe'),
(195, 'Moldova', 'MD', '.MD', 'Europe'),
(196, 'Macedonia', 'MK', '.MK', 'Europe'),
(197, 'Malta', 'MT', '.MT', 'Europe'),
(198, 'Mexico', 'MX', '.MX', 'North America'),
(199, 'Malaysia', 'MY', '.MY', 'Asia'),
(200, 'Netherlands', 'NL', '.NL', 'Europe'),
(201, 'Norway', 'NO', '.NO', 'Europe'),
(202, 'Nepal', 'NP', '.NP', 'Asia'),
(203, 'New Zealand', 'NZ', '.NZ', 'Oceania'),
(204, 'Panama', 'PA', '.PA', 'North America'),
(205, 'Pakistan', 'PK', '.PK', 'Asia'),
(206, 'Poland', 'PL', '.PL', 'Europe'),
(207, 'Portugal', 'PT', '.PT', 'Europe'),
(208, 'Qatar', 'QA', '.QA', 'Asia'),
(209, 'Romania', 'RO', '.RO', 'Europe'),
(210, 'Serbia', 'RS', '.RS', 'Europe'),
(211, 'Russian Federation', 'RU', '.RU', 'Europe'),
(212, 'Saudi Arabia', 'SA', '.SA', 'Asia'),
(213, 'Seychelles', 'SC', '.SC', 'Africa'),
(214, 'Sweden', 'SE', '.SE', 'Europe'),
(215, 'Singapore', 'SG', '.SG', 'Asia'),
(216, 'Slovakia', 'SK', '.SK', 'Europe'),
(217, 'Thailand', 'TH', '.TH', 'Asia'),
(218, 'Tunisia', 'TN', '.TN', 'Africa'),
(219, 'Taiwan', 'TW', '.TW', 'Asia'),
(220, 'South Africa', 'ZA', '.ZA', 'Africa'),
(221, 'Turkmenistan', 'TM', '.TM', 'Asia'),
(222, 'Turks and Caicos Islands', 'TC', '.TC', 'North America'),
(223, 'Tuvalu', 'TV', '.TV', 'Oceania'),
(224, 'Uganda', 'UG', '.UG', 'Africa'),
(225, 'United Arab Emirates', 'AE', '.AE', 'Asia'),
(226, 'United States Minor Outlying Islands', 'UM', '.UM', 'Oceania'),
(227, 'Uruguay', 'UY', '.UY', 'South America'),
(228, 'Vanuatu', 'VU', '.VU', 'Oceania'),
(229, 'Virgin Islands', 'VI', '.VI', 'North America'),
(230, 'Wallis and Futuna', 'WF', '.WF', 'Oceania'),
(231, 'Western Sahara', 'EH', '.EH', 'Africa'),
(232, 'Yemen', 'YE', '.YE', 'Asia'),
(233, 'Zambia', 'ZM', '.ZM', 'Africa'),
(234, 'Zimbabwe', 'ZW', '.ZW', 'Africa'),
(235, 'Saint Barthélemy', 'BL', '.BL', 'North America'),
(236, 'Saint Martin', 'MF', '.MF', NULL),
(237, 'Bonaire', 'BQ', '.BQ', NULL),
(238, 'Curaçao', 'CW', '.CW', NULL),
(239, 'Sint Maarten', 'SX', '.SX', NULL),
(240, 'South Sudan', 'SS', '.SS', 'Africa'),
(241, 'Angola', 'AO', '.AO', 'Africa'),
(242, 'Switzerland', 'CH', '.CH', 'Europe'),
(243, 'United Kingdom', 'GB', '.UK', 'Europe'),
(244, 'Turkey', 'TR', '.TR', 'Asia'),
(245, 'Ukraine', 'UA', '.UA', 'Europe'),
(246, 'United States', 'US', '.US', 'North America'),
(247, 'Uzbekistan', 'UZ', '.UZ', 'Asia'),
(248, 'Venezuela', 'VE', '.VE', 'South America'),
(249, 'Virgin Islands', 'VG', '.VG', 'North America'),
(250, 'Vietnam', 'VN', '.VN', 'Asia'),
(251, 'Unknown', 'UN', '.UN', NULL);

-- ASN
INSERT INTO "asn" ("id", "number", "name") VALUES (1, '0', 'Unknown');

-- Top Shame Domains
INSERT INTO "top_shame" (id, site) VALUES 
(1, 'twitter.com'),
(2, 'twitch.tv'),
(3, 'ebay.com'),
(4, 'imgur.com'),
(5, 'imdb.com'),
(6, 'wordpress.com'),
(7, 'github.com'),
(8, 'paypal.com'),
(9, 'stackoverflow.com'),
(10, 'soundcloud.com'),
(11, 'nytimes.com'),
(12, 'w3schools.com');
