// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Continents string

const (
	ContinentsAfrica       Continents = "Africa"
	ContinentsAntarctica   Continents = "Antarctica"
	ContinentsAsia         Continents = "Asia"
	ContinentsEurope       Continents = "Europe"
	ContinentsOceania      Continents = "Oceania"
	ContinentsNorthAmerica Continents = "North America"
	ContinentsSouthAmerica Continents = "South America"
)

func (e *Continents) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Continents(s)
	case string:
		*e = Continents(s)
	default:
		return fmt.Errorf("unsupported scan type for Continents: %T", src)
	}
	return nil
}

type NullContinents struct {
	Continents Continents
	Valid      bool // Valid is true if Continents is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContinents) Scan(value interface{}) error {
	if value == nil {
		ns.Continents, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Continents.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContinents) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return ns.Continents, nil
}

type Asn struct {
	ID     int64
	Number int32
	Name   string
}

type Campaign struct {
	ID          int64
	CreatedAt   time.Time
	Uuid        uuid.UUID
	Name        string
	Description string
	Disabled    bool
}

type CampaignChangelog struct {
	ID         int64
	Ts         time.Time
	DomainID   int32
	CampaignID uuid.UUID
	Message    string
}

type CampaignDomain struct {
	ID         int64
	CampaignID uuid.UUID
	Site       string
	CheckAaaa  bool
	CheckWww   bool
	CheckNs    bool
	CheckCurl  bool
	AsnID      sql.NullInt64
	CountryID  sql.NullInt64
	Disabled   bool
	TsAaaa     sql.NullTime
	TsWww      sql.NullTime
	TsNs       sql.NullTime
	TsCurl     sql.NullTime
	TsCheck    sql.NullTime
	TsUpdated  sql.NullTime
}

type Changelog struct {
	ID       int64
	Ts       time.Time
	DomainID int32
	Message  string
}

type ChangelogCampaignView struct {
	ID         int64
	Ts         time.Time
	DomainID   int32
	CampaignID uuid.UUID
	Message    string
	Site       string
}

type ChangelogView struct {
	ID       int64
	Ts       time.Time
	DomainID int32
	Message  string
	Site     string
}

type Country struct {
	ID          int64
	CountryName string
	CountryCode string
	CountryTld  string
	Continent   NullContinents
	Sites       int32
	V6sites     int32
	Percent     pgtype.Numeric
}

type Domain struct {
	ID        int64
	Site      string
	CheckAaaa bool
	CheckWww  bool
	CheckNs   bool
	CheckCurl bool
	AsnID     sql.NullInt64
	CountryID sql.NullInt64
	Disabled  bool
	TsAaaa    sql.NullTime
	TsWww     sql.NullTime
	TsNs      sql.NullTime
	TsCurl    sql.NullTime
	TsCheck   sql.NullTime
	TsUpdated sql.NullTime
}

type DomainCrawlList struct {
	ID        int64
	Site      string
	CheckAaaa bool
	CheckWww  bool
	CheckNs   bool
	CheckCurl bool
	AsnID     sql.NullInt64
	CountryID sql.NullInt64
	Disabled  bool
	TsAaaa    sql.NullTime
	TsWww     sql.NullTime
	TsNs      sql.NullTime
	TsCurl    sql.NullTime
	TsCheck   sql.NullTime
	TsUpdated sql.NullTime
}

type DomainViewHeroes struct {
	ID          sql.NullInt64
	Site        sql.NullString
	CheckAaaa   sql.NullBool
	CheckWww    sql.NullBool
	CheckNs     sql.NullBool
	CheckCurl   sql.NullBool
	AsnID       sql.NullInt64
	CountryID   sql.NullInt64
	Disabled    sql.NullBool
	TsAaaa      sql.NullTime
	TsWww       sql.NullTime
	TsNs        sql.NullTime
	TsCurl      sql.NullTime
	TsCheck     sql.NullTime
	TsUpdated   sql.NullTime
	Rank        int64
	Asname      sql.NullString
	CountryName sql.NullString
}

type DomainViewIndex struct {
	ID          sql.NullInt64
	Site        sql.NullString
	CheckAaaa   sql.NullBool
	CheckWww    sql.NullBool
	CheckNs     sql.NullBool
	CheckCurl   sql.NullBool
	AsnID       sql.NullInt64
	CountryID   sql.NullInt64
	Disabled    sql.NullBool
	TsAaaa      sql.NullTime
	TsWww       sql.NullTime
	TsNs        sql.NullTime
	TsCurl      sql.NullTime
	TsCheck     sql.NullTime
	TsUpdated   sql.NullTime
	Rank        int64
	Asname      sql.NullString
	CountryName sql.NullString
}

type DomainViewList struct {
	ID          sql.NullInt64
	Site        sql.NullString
	CheckAaaa   sql.NullBool
	CheckWww    sql.NullBool
	CheckNs     sql.NullBool
	CheckCurl   sql.NullBool
	AsnID       sql.NullInt64
	CountryID   sql.NullInt64
	Disabled    sql.NullBool
	TsAaaa      sql.NullTime
	TsWww       sql.NullTime
	TsNs        sql.NullTime
	TsCurl      sql.NullTime
	TsCheck     sql.NullTime
	TsUpdated   sql.NullTime
	Rank        int64
	Asname      sql.NullString
	CountryName sql.NullString
}

type Lists struct {
	ID   int64
	Name string
	Ts   time.Time
}

type Metrics struct {
	ID          int64
	Measurement string
	Time        time.Time
	Data        pgtype.JSONB
}

type Sites struct {
	ID     int64
	ListID int64
	Rank   int64
	Site   string
}

type StatsAsn struct {
	ID        int64
	AsnID     int64
	V4Count   int32
	V4Percent pgtype.Numeric
	V6Count   int32
	V6Percent pgtype.Numeric
	Ts        time.Time
}
