{
 "title": "WhyNoIPv6",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'total_sites')::NUMERIC) as TotalSites,\n  ((data->>'total_ns')::NUMERIC) as TotalNs,\n  ((data->>'total_aaaa')::NUMERIC) as TotalAaaa,\n  ((data->>'total_www')::NUMERIC) as TotalWww,\n  ((data->>'total_both')::NUMERIC) as TotalBoth\nFROM\n  metrics\nWHERE measurement = 'domains'"
    }
   ]
  },
  {
   "title": "Last Crawl",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id, time from metrics where measurement = 'crawler' ORDER BY id desc LIMIT 1;"
    }
   ]
  },
  {
   "title": "Never checked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(1) \nFROM domain\nWHERE ts_check IS NULL\nAND disabled is FALSE;"
    }
   ]
  },
  {
   "title": "Last Campaign Crawl",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id, time from metrics where measurement = 'crawler_campaign' ORDER BY id desc LIMIT 1;"
    }
   ]
  },
  {
   "title": "Next Crawl",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(1) \nFROM domain\nWHERE (ts_check < now() - '3 days' :: interval) \nOR (ts_check IS NULL)\nAND disabled is FALSE;"
    }
   ]
  },
  {
   "title": "Disabled domains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) from domain where disabled = true"
    }
   ]
  },
  {
   "title": "Campaign domains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(1) from campaign_domain where disabled = false"
    }
   ]
  },
  {
   "title": "Changelog",
   "type": "logs",
   "gridPos": { "h": 25, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT * from changelog order by id desc limit 50"
    }
   ]
  },
  {
   "title": "Campaign Changelog",
   "type": "logs",
   "gridPos": { "h": 25, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT id,ts,message from campaign_changelog order by id desc limit 50"
    }
   ]
  },
  {
   "title": "Crawler Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'duration')::NUMERIC) as duration\nFROM\n  metrics\nWHERE measurement = 'crawler'"
    }
   ]
  },
  {
   "title": "Crawler Updated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'updated')::NUMERIC) as Updated\nFROM\n  metrics\nWHERE measurement = 'crawler'"
    }
   ]
  },
  {
   "title": "Campaign Crawler Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'duration')::NUMERIC) as duration\nFROM\n  metrics\nWHERE measurement = 'crawler_campaign'"
    }
   ]
  },
  {
   "title": "Campaign Crawler Updated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'updated')::NUMERIC) as Updated\nFROM\n  metrics\nWHERE measurement = 'crawler_campaign'"
    }
   ]
  },
  { "title": "Domains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total AAAA",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'total_aaaa')::NUMERIC) as TotalAAAA\nFROM\n  metrics\nWHERE measurement = 'domains'"
    }
   ]
  },
  {
   "title": "Total WWW",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'total_www')::NUMERIC) as TotalWww\nFROM\n  metrics\nWHERE measurement = 'domains'"
    }
   ]
  },
  {
   "title": "Total Both",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'total_both')::NUMERIC) as TotalBoth\nFROM\n  metrics\nWHERE measurement = 'domains'"
    }
   ]
  },
  {
   "title": "Total NS",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'total_ns')::NUMERIC) as TotalNS\nFROM\n  metrics\nWHERE measurement = 'domains'"
    }
   ]
  },
  {
   "title": "Total 1k",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'top_1k')::NUMERIC) as Top1k\nFROM\n  metrics\nWHERE measurement = 'domains'"
    }
   ]
  },
  {
   "title": "Total 1k NS",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ((data->>'top_ns')::NUMERIC) as TopNS\nFROM\n  metrics\nWHERE measurement = 'domains'"
    }
   ]
  }
 ]
}