-- =============================================================================
-- 000003_seed.up.sql — reference data seeds
-- Sentinels land with the asn/country seed data, BEFORE any domain row can
-- exist (domain.asn_id / domain.country_id are NOT NULL FKs). IDENTITY assigns
-- ids; binaries resolve sentinel ids once at startup by lookup
-- (asn.number = 0, country.code = 'UN'), never by literal id.
-- =============================================================================

-- Sentinel ASN (attribution fallback; appears in /asns as in production).
INSERT INTO asn (number, name) VALUES (0, 'Unknown');

-- Country reference data: 251 rows, including the sentinel
-- (code 'UN', name 'Unknown', tld '.UN'). Lifted from production
-- whynoipv6/db/migrations/02_data.up.sql with this exact transform:
--   (id, country_name, country_code, country_tld, continent)
--   -> (name = country_name, code = country_code, tld = country_tld);
--   id and continent are dropped (IDENTITY assigns ids; the new schema has no
--   continent column).
INSERT INTO country (name, code, tld) VALUES
('Georgia', 'GE', '.GE'),
('Afghanistan', 'AF', '.AF'),
('Åland Islands', 'AX', '.AX'),
('Albania', 'AL', '.AL'),
('Algeria', 'DZ', '.DZ'),
('American Samoa', 'AS', '.AS'),
('Andorra', 'AD', '.AD'),
('Anguilla', 'AI', '.AI'),
('Antarctica', 'AQ', '.AQ'),
('Antigua and Barbuda', 'AG', '.AG'),
('Armenia', 'AM', '.AM'),
('Aruba', 'AW', '.AW'),
('Bahamas', 'BS', '.BS'),
('Bahrain', 'BH', '.BH'),
('Barbados', 'BB', '.BB'),
('Benin', 'BJ', '.BJ'),
('Bermuda', 'BM', '.BM'),
('Bhutan', 'BT', '.BT'),
('Bolivia', 'BO', '.BO'),
('Botswana', 'BW', '.BW'),
('Bouvet Island', 'BV', '.BV'),
('British Indian Ocean Territory', 'IO', '.IO'),
('Brunei Darussalam', 'BN', '.BN'),
('Burkina Faso', 'BF', '.BF'),
('Burundi', 'BI', '.BI'),
('Cambodia', 'KH', '.KH'),
('Cameroon', 'CM', '.CM'),
('Cape Verde', 'CV', '.CV'),
('Central African Republic', 'CF', '.CF'),
('Chad', 'TD', '.TD'),
('Christmas Island', 'CX', '.CX'),
('Cocos (Keeling) Islands', 'CC', '.CC'),
('Comoros', 'KM', '.KM'),
('Congo', 'CG', '.CG'),
('The Democratic Republic Of The Congo', 'CD', '.CD'),
('Cook Islands', 'CK', '.CK'),
('Costa Rica', 'CR', '.CR'),
('Cote Divoire', 'CI', '.CI'),
('Cuba', 'CU', '.CU'),
('Djibouti', 'DJ', '.DJ'),
('Dominica', 'DM', '.DM'),
('Dominican Republic', 'DO', '.DO'),
('El Salvador', 'SV', '.SV'),
('Equatorial Guinea', 'GQ', '.GQ'),
('Eritrea', 'ER', '.ER'),
('Ethiopia', 'ET', '.ET'),
('Falkland Islands (Malvinas)', 'FK', '.FK'),
('Faroe Islands', 'FO', '.FO'),
('Fiji', 'FJ', '.FJ'),
('French Guiana', 'GF', '.GF'),
('French Polynesia', 'PF', '.PF'),
('French Southern Territories', 'TF', '.TF'),
('Gabon', 'GA', '.GA'),
('Gambia', 'GM', '.GM'),
('Ghana', 'GH', '.GH'),
('Gibraltar', 'GI', '.GI'),
('Greenland', 'GL', '.GL'),
('Grenada', 'GD', '.GD'),
('Guadeloupe', 'GP', '.GP'),
('Guam', 'GU', '.GU'),
('Guatemala', 'GT', '.GT'),
('Guernsey', 'GG', '.GG'),
('Guinea', 'GN', '.GN'),
('Guinea-Bissau', 'GW', '.GW'),
('Guyana', 'GY', '.GY'),
('Haiti', 'HT', '.HT'),
('Heard and McDonald Islands', 'HM', '.HM'),
('Holy See (Vatican City State)', 'VA', '.VA'),
('Honduras', 'HN', '.HN'),
('Iceland', 'IS', '.IS'),
('Iraq', 'IQ', '.IQ'),
('Isle of Man', 'IM', '.IM'),
('Jamaica', 'JM', '.JM'),
('Jersey', 'JE', '.JE'),
('Jordan', 'JO', '.JO'),
('Argentina', 'AR', '.AR'),
('Austria', 'AT', '.AT'),
('Australia', 'AU', '.AU'),
('Azerbaijan', 'AZ', '.AZ'),
('Bosnia and Herzegovina', 'BA', '.BA'),
('Bangladesh', 'BD', '.BD'),
('Belgium', 'BE', '.BE'),
('Bulgaria', 'BG', '.BG'),
('Brazil', 'BR', '.BR'),
('Belarus', 'BY', '.BY'),
('Belize', 'BZ', '.BZ'),
('Canada', 'CA', '.CA'),
('Chile', 'CL', '.CL'),
('China', 'CN', '.CN'),
('Colombia', 'CO', '.CO'),
('Cyprus', 'CY', '.CY'),
('Czech Republic', 'CZ', '.CZ'),
('Germany', 'DE', '.DE'),
('Denmark', 'DK', '.DK'),
('Ecuador', 'EC', '.EC'),
('Estonia', 'EE', '.EE'),
('Egypt', 'EG', '.EG'),
('Finland', 'FI', '.FI'),
('France', 'FR', '.FR'),
('Greece', 'GR', '.GR'),
('Hong Kong', 'HK', '.HK'),
('Croatia', 'HR', '.HR'),
('Hungary', 'HU', '.HU'),
('Indonesia', 'ID', '.ID'),
('Ireland', 'IE', '.IE'),
('Israel', 'IL', '.IL'),
('India', 'IN', '.IN'),
('Iran', 'IR', '.IR'),
('Italy', 'IT', '.IT'),
('Japan', 'JP', '.JP'),
('Cayman Islands', 'KY', '.KY'),
('Kazakhstan', 'KZ', '.KZ'),
('Kiribati', 'KI', '.KI'),
('North Korea', 'KP', '.KP'),
('Kuwait', 'KW', '.KW'),
('Kyrgyzstan', 'KG', '.KG'),
('Lao People', 'LA', '.LA'),
('Lebanon', 'LB', '.LB'),
('Lesotho', 'LS', '.LS'),
('Liberia', 'LR', '.LR'),
('Libya', 'LY', '.LY'),
('Liechtenstein', 'LI', '.LI'),
('Macao', 'MO', '.MO'),
('Madagascar', 'MG', '.MG'),
('Malawi', 'MW', '.MW'),
('Maldives', 'MV', '.MV'),
('Mali', 'ML', '.ML'),
('Marshall Islands', 'MH', '.MH'),
('Martinique', 'MQ', '.MQ'),
('Mauritania', 'MR', '.MR'),
('Mauritius', 'MU', '.MU'),
('Mayotte', 'YT', '.YT'),
('Micronesia', 'FM', '.FM'),
('Monaco', 'MC', '.MC'),
('Mongolia', 'MN', '.MN'),
('Montenegro', 'ME', '.ME'),
('Montserrat', 'MS', '.MS'),
('Morocco', 'MA', '.MA'),
('Mozambique', 'MZ', '.MZ'),
('Myanmar', 'MM', '.MM'),
('Namibia', 'NA', '.NA'),
('Nauru', 'NR', '.NR'),
('Netherlands Antilles', 'AN', '.AN'),
('New Caledonia', 'NC', '.NC'),
('Nicaragua', 'NI', '.NI'),
('Niger', 'NE', '.NE'),
('Nigeria', 'NG', '.NG'),
('Niue', 'NU', '.NU'),
('Norfolk Island', 'NF', '.NF'),
('Northern Mariana Islands', 'MP', '.MP'),
('Oman', 'OM', '.OM'),
('Palau', 'PW', '.PW'),
('Palestine', 'PS', '.PS'),
('Papua New Guinea', 'PG', '.PG'),
('Paraguay', 'PY', '.PY'),
('Peru', 'PE', '.PE'),
('Philippines', 'PH', '.PH'),
('Saint Pierre And Miquelon', 'PM', '.PM'),
('Pitcairn', 'PN', '.PN'),
('Puerto Rico', 'PR', '.PR'),
('Réunion', 'RE', '.RE'),
('Rwanda', 'RW', '.RW'),
('Saint Helena', 'SH', '.SH'),
('Saint Kitts And Nevis', 'KN', '.KN'),
('Saint Lucia', 'LC', '.LC'),
('Saint Vincent And The Grenedines', 'VC', '.VC'),
('Samoa', 'WS', '.WS'),
('San Marino', 'SM', '.SM'),
('Sao Tome and Principe', 'ST', '.ST'),
('Senegal', 'SN', '.SN'),
('Sierra Leone', 'SL', '.SL'),
('Slovenia', 'SI', '.SI'),
('Solomon Islands', 'SB', '.SB'),
('Somalia', 'SO', '.SO'),
('South Georgia', 'GS', '.GS'),
('Sri Lanka', 'LK', '.LK'),
('Sudan', 'SD', '.SD'),
('Suriname', 'SR', '.SR'),
('Svalbard And Jan Mayen', 'SJ', '.SJ'),
('Swaziland', 'SZ', '.SZ'),
('Syrian Arab Republic', 'SY', '.SY'),
('Tajikistan', 'TJ', '.TJ'),
('Tanzania', 'TZ', '.TZ'),
('Timor-Leste', 'TL', '.TL'),
('Togo', 'TG', '.TG'),
('Tokelau', 'TK', '.TK'),
('Tonga', 'TO', '.TO'),
('Trinidad and Tobago', 'TT', '.TT'),
('Spain', 'ES', '.ES'),
('Kenya', 'KE', '.KE'),
('South Korea', 'KR', '.KR'),
('Lithuania', 'LT', '.LT'),
('Luxembourg', 'LU', '.LU'),
('Latvia', 'LV', '.LV'),
('Moldova', 'MD', '.MD'),
('Macedonia', 'MK', '.MK'),
('Malta', 'MT', '.MT'),
('Mexico', 'MX', '.MX'),
('Malaysia', 'MY', '.MY'),
('Netherlands', 'NL', '.NL'),
('Norway', 'NO', '.NO'),
('Nepal', 'NP', '.NP'),
('New Zealand', 'NZ', '.NZ'),
('Panama', 'PA', '.PA'),
('Pakistan', 'PK', '.PK'),
('Poland', 'PL', '.PL'),
('Portugal', 'PT', '.PT'),
('Qatar', 'QA', '.QA'),
('Romania', 'RO', '.RO'),
('Serbia', 'RS', '.RS'),
('Russian Federation', 'RU', '.RU'),
('Saudi Arabia', 'SA', '.SA'),
('Seychelles', 'SC', '.SC'),
('Sweden', 'SE', '.SE'),
('Singapore', 'SG', '.SG'),
('Slovakia', 'SK', '.SK'),
('Thailand', 'TH', '.TH'),
('Tunisia', 'TN', '.TN'),
('Taiwan', 'TW', '.TW'),
('South Africa', 'ZA', '.ZA'),
('Turkmenistan', 'TM', '.TM'),
('Turks and Caicos Islands', 'TC', '.TC'),
('Tuvalu', 'TV', '.TV'),
('Uganda', 'UG', '.UG'),
('United Arab Emirates', 'AE', '.AE'),
('United States Minor Outlying Islands', 'UM', '.UM'),
('Uruguay', 'UY', '.UY'),
('Vanuatu', 'VU', '.VU'),
('Virgin Islands', 'VI', '.VI'),
('Wallis and Futuna', 'WF', '.WF'),
('Western Sahara', 'EH', '.EH'),
('Yemen', 'YE', '.YE'),
('Zambia', 'ZM', '.ZM'),
('Zimbabwe', 'ZW', '.ZW'),
('Saint Barthélemy', 'BL', '.BL'),
('Saint Martin', 'MF', '.MF'),
('Bonaire', 'BQ', '.BQ'),
('Curaçao', 'CW', '.CW'),
('Sint Maarten', 'SX', '.SX'),
('South Sudan', 'SS', '.SS'),
('Angola', 'AO', '.AO'),
('Switzerland', 'CH', '.CH'),
('United Kingdom', 'GB', '.UK'),
('Turkey', 'TR', '.TR'),
('Ukraine', 'UA', '.UA'),
('United States', 'US', '.US'),
('Uzbekistan', 'UZ', '.UZ'),
('Venezuela', 'VE', '.VE'),
('Virgin Islands', 'VG', '.VG'),
('Vietnam', 'VN', '.VN'),
('Unknown', 'UN', '.UN');

-- Day-0 stats rows: the /stats/overview endpoint (07) reads the latest
-- stats_global_daily row and MUST always find one, even on first boot before
-- the first nightly snapshot.
INSERT INTO stats_global_daily (
  day, domains, sinners, partial, heroes, saints, inactive, unknown, disabled,
  base_supported, www_supported, ns_supported, mx_supported, conn_supported,
  resources_supported, top_heroes, top_nameserver)
VALUES (CURRENT_DATE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
ON CONFLICT (day) DO NOTHING;
