// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asn.sql

package db

import (
	"context"
)

const ASNByNumber = `-- name: ASNByNumber :one
SELECT number, name, count_total, count_v6 FROM asn WHERE number = $1
`

type ASNByNumberRow struct {
	Number     int64  `json:"number"`
	Name       string `json:"name"`
	CountTotal int32  `json:"count_total"`
	CountV6    int32  `json:"count_v6"`
}

// The API network leaderboard (07 §4.6): keyset over (count, number) desc;
// the ILIKE arm serves ?q= substring match.
func (q *Queries) ASNByNumber(ctx context.Context, number int64) (ASNByNumberRow, error) {
	row := q.db.QueryRow(ctx, ASNByNumber, number)
	var i ASNByNumberRow
	err := row.Scan(
		&i.Number,
		&i.Name,
		&i.CountTotal,
		&i.CountV6,
	)
	return i, err
}

const ASNEnsure = `-- name: ASNEnsure :one
INSERT INTO asn (number, name) VALUES ($1, $2)
ON CONFLICT (number) DO NOTHING
RETURNING id
`

type ASNEnsureParams struct {
	Number int64  `json:"number"`
	Name   string `json:"name"`
}

// ASN auto-registration (06-ingest.md §6.3): pool-side, before the commit
// transaction (03 §3 A). ON CONFLICT DO NOTHING + re-read; names are never
// updated on later scans.
func (q *Queries) ASNEnsure(ctx context.Context, arg ASNEnsureParams) (int32, error) {
	row := q.db.QueryRow(ctx, ASNEnsure, arg.Number, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const ASNIDByNumber = `-- name: ASNIDByNumber :one
SELECT id FROM asn WHERE number = $1
`

func (q *Queries) ASNIDByNumber(ctx context.Context, number int64) (int32, error) {
	row := q.db.QueryRow(ctx, ASNIDByNumber, number)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const ASNSentinelID = `-- name: ASNSentinelID :one

SELECT id FROM asn WHERE number = 0
`

// db/query/asn.sql — sqlc query source (layout: 05-schema.md §10.2).
// Sentinel lookup: binaries resolve the sentinel ASN once at startup by
// lookup, never by literal id (05-schema.md §5).
func (q *Queries) ASNSentinelID(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ASNSentinelID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const RecomputeASNCounters = `-- name: RecomputeASNCounters :exec
UPDATE asn a SET
  count_total = agg.count_total,
  count_v6    = agg.count_v6
FROM (
  SELECT asn_id,
         count(*)                                                      AS count_total,
         count(*) FILTER (WHERE classification IN ('partial','hero'))  AS count_v6
  FROM domain
  WHERE rank IS NOT NULL AND NOT disabled
  GROUP BY asn_id
) agg
WHERE a.id = agg.asn_id
`

func (q *Queries) RecomputeASNCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, RecomputeASNCounters)
	return err
}

const RecomputeProviderCounters = `-- name: RecomputeProviderCounters :exec
UPDATE dns_provider p SET
  count_total = agg.count_total,
  count_v6    = agg.count_v6
FROM (
  SELECT dns_provider_id,
         count(*)                                                      AS count_total,
         count(*) FILTER (WHERE classification IN ('partial','hero'))  AS count_v6
  FROM domain
  WHERE rank IS NOT NULL AND NOT disabled AND dns_provider_id IS NOT NULL
  GROUP BY dns_provider_id
) agg
WHERE p.id = agg.dns_provider_id
`

func (q *Queries) RecomputeProviderCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, RecomputeProviderCounters)
	return err
}

const ResetASNCounters = `-- name: ResetASNCounters :exec
UPDATE asn SET count_total = 0, count_v6 = 0
`

// Tick step 3 — ASN + DNS-provider counter recompute (06-ingest.md §10.6).
func (q *Queries) ResetASNCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ResetASNCounters)
	return err
}

const ResetProviderCounters = `-- name: ResetProviderCounters :exec
UPDATE dns_provider SET count_total = 0, count_v6 = 0
`

func (q *Queries) ResetProviderCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ResetProviderCounters)
	return err
}
