// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asn.sql

package db

import (
	"context"
)

const ASNSentinelID = `-- name: ASNSentinelID :one

SELECT id FROM asn WHERE number = 0
`

// db/query/asn.sql — sqlc query source (layout: 05-schema.md §10.2).
// Sentinel lookup: binaries resolve the sentinel ASN once at startup by
// lookup, never by literal id (05-schema.md §5).
func (q *Queries) ASNSentinelID(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ASNSentinelID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
