// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaign.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CampaignAddMember = `-- name: CampaignAddMember :execrows
INSERT INTO campaign_domain (campaign_id, domain_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CampaignAddMemberParams struct {
	CampaignID int32 `json:"campaign_id"`
	DomainID   int64 `json:"domain_id"`
}

func (q *Queries) CampaignAddMember(ctx context.Context, arg CampaignAddMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, CampaignAddMember, arg.CampaignID, arg.DomainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const CampaignAdoption = `-- name: CampaignAdoption :one
SELECT day, domains, v6_ready FROM stats_campaign_daily
WHERE campaign_id = $1 ORDER BY day DESC LIMIT 1
`

type CampaignAdoptionRow struct {
	Day     pgtype.Date `json:"day"`
	Domains *int32      `json:"domains"`
	V6Ready *int32      `json:"v6_ready"`
}

func (q *Queries) CampaignAdoption(ctx context.Context, campaignID int32) (CampaignAdoptionRow, error) {
	row := q.db.QueryRow(ctx, CampaignAdoption, campaignID)
	var i CampaignAdoptionRow
	err := row.Scan(&i.Day, &i.Domains, &i.V6Ready)
	return i, err
}

const CampaignByUUID = `-- name: CampaignByUUID :one

SELECT id, uuid, name, source_file, disabled FROM campaign WHERE uuid = $1
`

type CampaignByUUIDRow struct {
	ID         int32       `json:"id"`
	Uuid       pgtype.UUID `json:"uuid"`
	Name       string      `json:"name"`
	SourceFile *string     `json:"source_file"`
	Disabled   bool        `json:"disabled"`
}

// db/query/campaign.sql — sqlc query source (layout: 05-schema.md §10.2).
func (q *Queries) CampaignByUUID(ctx context.Context, uuid pgtype.UUID) (CampaignByUUIDRow, error) {
	row := q.db.QueryRow(ctx, CampaignByUUID, uuid)
	var i CampaignByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.SourceFile,
		&i.Disabled,
	)
	return i, err
}

const CampaignDisableAbsent = `-- name: CampaignDisableAbsent :many
UPDATE campaign SET disabled = true, updated_at = now()
WHERE NOT disabled AND uuid <> ALL($1::uuid[])
RETURNING uuid, name
`

type CampaignDisableAbsentRow struct {
	Uuid pgtype.UUID `json:"uuid"`
	Name string      `json:"name"`
}

func (q *Queries) CampaignDisableAbsent(ctx context.Context, dollar_1 []pgtype.UUID) ([]CampaignDisableAbsentRow, error) {
	rows, err := q.db.Query(ctx, CampaignDisableAbsent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignDisableAbsentRow{}
	for rows.Next() {
		var i CampaignDisableAbsentRow
		if err := rows.Scan(&i.Uuid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const CampaignInsert = `-- name: CampaignInsert :one
INSERT INTO campaign (uuid, name, description, source_file, tags)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CampaignInsertParams struct {
	Uuid        pgtype.UUID `json:"uuid"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	SourceFile  *string     `json:"source_file"`
	Tags        []string    `json:"tags"`
}

func (q *Queries) CampaignInsert(ctx context.Context, arg CampaignInsertParams) (int32, error) {
	row := q.db.QueryRow(ctx, CampaignInsert,
		arg.Uuid,
		arg.Name,
		arg.Description,
		arg.SourceFile,
		arg.Tags,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const CampaignMembers = `-- name: CampaignMembers :many
SELECT domain_id FROM campaign_domain WHERE campaign_id = $1
`

func (q *Queries) CampaignMembers(ctx context.Context, campaignID int32) ([]int64, error) {
	rows, err := q.db.Query(ctx, CampaignMembers, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var domain_id int64
		if err := rows.Scan(&domain_id); err != nil {
			return nil, err
		}
		items = append(items, domain_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const CampaignPublicDetail = `-- name: CampaignPublicDetail :one
SELECT c.id, c.uuid, c.name, c.description, c.source_file, c.tags, c.disabled,
       (SELECT count(*) FROM campaign_domain cd WHERE cd.campaign_id = c.id) AS domain_count
FROM campaign c WHERE c.uuid = $1
`

type CampaignPublicDetailRow struct {
	ID          int32       `json:"id"`
	Uuid        pgtype.UUID `json:"uuid"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	SourceFile  *string     `json:"source_file"`
	Tags        []string    `json:"tags"`
	Disabled    bool        `json:"disabled"`
	DomainCount int64       `json:"domain_count"`
}

func (q *Queries) CampaignPublicDetail(ctx context.Context, uuid pgtype.UUID) (CampaignPublicDetailRow, error) {
	row := q.db.QueryRow(ctx, CampaignPublicDetail, uuid)
	var i CampaignPublicDetailRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.SourceFile,
		&i.Tags,
		&i.Disabled,
		&i.DomainCount,
	)
	return i, err
}

const CampaignPublicList = `-- name: CampaignPublicList :many
SELECT c.uuid, c.name, c.description, c.source_file, c.tags,
       (SELECT count(*) FROM campaign_domain cd WHERE cd.campaign_id = c.id) AS domain_count,
       s.day AS adoption_day, s.domains AS adoption_domains, s.v6_ready AS adoption_v6_ready
FROM campaign c
LEFT JOIN LATERAL (
    SELECT day, domains, v6_ready FROM stats_campaign_daily scd
    WHERE scd.campaign_id = c.id ORDER BY day DESC LIMIT 1
) s ON true
WHERE NOT c.disabled AND ($1::TEXT = '' OR $1 = ANY(c.tags))
ORDER BY c.name, c.id
`

type CampaignPublicListRow struct {
	Uuid            pgtype.UUID `json:"uuid"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	SourceFile      *string     `json:"source_file"`
	Tags            []string    `json:"tags"`
	DomainCount     int64       `json:"domain_count"`
	AdoptionDay     pgtype.Date `json:"adoption_day"`
	AdoptionDomains *int32      `json:"adoption_domains"`
	AdoptionV6Ready *int32      `json:"adoption_v6_ready"`
}

// The public campaign surface (07 §4.7): exact member counts (bounded sets),
// ?tag= via the GIN-indexed tags array. Each row carries the same adoption
// pair as the detail via a lateral read of the latest stats_campaign_daily
// row (the set is tens of rows, so the per-row join is trivially cheap).
func (q *Queries) CampaignPublicList(ctx context.Context, tag string) ([]CampaignPublicListRow, error) {
	rows, err := q.db.Query(ctx, CampaignPublicList, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignPublicListRow{}
	for rows.Next() {
		var i CampaignPublicListRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.SourceFile,
			&i.Tags,
			&i.DomainCount,
			&i.AdoptionDay,
			&i.AdoptionDomains,
			&i.AdoptionV6Ready,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const CampaignRemoveMembersNotIn = `-- name: CampaignRemoveMembersNotIn :execrows
DELETE FROM campaign_domain
WHERE campaign_id = $1 AND domain_id <> ALL($2::bigint[])
`

type CampaignRemoveMembersNotInParams struct {
	CampaignID int32   `json:"campaign_id"`
	Column2    []int64 `json:"column_2"`
}

func (q *Queries) CampaignRemoveMembersNotIn(ctx context.Context, arg CampaignRemoveMembersNotInParams) (int64, error) {
	result, err := q.db.Exec(ctx, CampaignRemoveMembersNotIn, arg.CampaignID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const CampaignUUIDBySourceFile = `-- name: CampaignUUIDBySourceFile :one
SELECT uuid FROM campaign WHERE source_file = $1
`

func (q *Queries) CampaignUUIDBySourceFile(ctx context.Context, sourceFile *string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, CampaignUUIDBySourceFile, sourceFile)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const CampaignUpdateFromFile = `-- name: CampaignUpdateFromFile :one
UPDATE campaign
SET name = $2, description = $3, tags = $4, source_file = $5,
    disabled = false, updated_at = now()
WHERE uuid = $1
RETURNING id
`

type CampaignUpdateFromFileParams struct {
	Uuid        pgtype.UUID `json:"uuid"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Tags        []string    `json:"tags"`
	SourceFile  *string     `json:"source_file"`
}

func (q *Queries) CampaignUpdateFromFile(ctx context.Context, arg CampaignUpdateFromFileParams) (int32, error) {
	row := q.db.QueryRow(ctx, CampaignUpdateFromFile,
		arg.Uuid,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.SourceFile,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
