// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changelog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CampaignHasMember = `-- name: CampaignHasMember :one
SELECT EXISTS(
  SELECT 1 FROM campaign_domain WHERE campaign_id = $1 AND domain_id = $2
)::bool
`

type CampaignHasMemberParams struct {
	CampaignID int32 `json:"campaign_id"`
	DomainID   int64 `json:"domain_id"`
}

func (q *Queries) CampaignHasMember(ctx context.Context, arg CampaignHasMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, CampaignHasMember, arg.CampaignID, arg.DomainID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const ChangelogByCampaign = `-- name: ChangelogByCampaign :many
SELECT cl.ts, d.host, cl.field, cl.old_value, cl.new_value
FROM changelog cl
JOIN domain d ON d.id = cl.domain_id
JOIN campaign_domain cd ON cd.domain_id = cl.domain_id AND cd.campaign_id = $1
ORDER BY cl.ts DESC, cl.domain_id DESC, cl.field DESC
LIMIT 50
`

type ChangelogByCampaignRow struct {
	Ts       pgtype.Timestamptz `json:"ts"`
	Host     string             `json:"host"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
}

func (q *Queries) ChangelogByCampaign(ctx context.Context, campaignID int32) ([]ChangelogByCampaignRow, error) {
	rows, err := q.db.Query(ctx, ChangelogByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogByCampaignRow{}
	for rows.Next() {
		var i ChangelogByCampaignRow
		if err := rows.Scan(
			&i.Ts,
			&i.Host,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ChangelogByCountry = `-- name: ChangelogByCountry :many
SELECT cl.ts, d.host, cl.field, cl.old_value, cl.new_value
FROM changelog cl JOIN domain d ON d.id = cl.domain_id
WHERE d.country_id = $1
ORDER BY cl.ts DESC, cl.domain_id DESC, cl.field DESC
LIMIT 50
`

type ChangelogByCountryRow struct {
	Ts       pgtype.Timestamptz `json:"ts"`
	Host     string             `json:"host"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
}

func (q *Queries) ChangelogByCountry(ctx context.Context, countryID int32) ([]ChangelogByCountryRow, error) {
	rows, err := q.db.Query(ctx, ChangelogByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogByCountryRow{}
	for rows.Next() {
		var i ChangelogByCountryRow
		if err := rows.Scan(
			&i.Ts,
			&i.Host,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ChangelogByDomain = `-- name: ChangelogByDomain :many
SELECT cl.ts, d.host, cl.field, cl.old_value, cl.new_value, cl.domain_id
FROM changelog cl JOIN domain d ON d.id = cl.domain_id
WHERE cl.domain_id = $1
  AND ($2::TEXT = '' OR cl.field = $2)
  AND (NOT $3::BOOL OR cl.ts >= $4::TIMESTAMPTZ)
  AND (NOT $5::BOOL OR cl.ts <= $6::TIMESTAMPTZ)
  AND (NOT $7::BOOL OR (cl.ts, cl.domain_id, cl.field) < ($8::TIMESTAMPTZ, $9::BIGINT, $10::TEXT))
ORDER BY cl.ts DESC, cl.domain_id DESC, cl.field DESC
LIMIT $11
`

type ChangelogByDomainParams struct {
	DomainID   int64              `json:"domain_id"`
	Field      string             `json:"field"`
	WithFrom   bool               `json:"with_from"`
	FromTs     pgtype.Timestamptz `json:"from_ts"`
	WithTo     bool               `json:"with_to"`
	ToTs       pgtype.Timestamptz `json:"to_ts"`
	WithSeek   bool               `json:"with_seek"`
	SeekTs     pgtype.Timestamptz `json:"seek_ts"`
	SeekDomain int64              `json:"seek_domain"`
	SeekField  string             `json:"seek_field"`
	Lim        int32              `json:"lim"`
}

type ChangelogByDomainRow struct {
	Ts       pgtype.Timestamptz `json:"ts"`
	Host     string             `json:"host"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
	DomainID int64              `json:"domain_id"`
}

func (q *Queries) ChangelogByDomain(ctx context.Context, arg ChangelogByDomainParams) ([]ChangelogByDomainRow, error) {
	rows, err := q.db.Query(ctx, ChangelogByDomain,
		arg.DomainID,
		arg.Field,
		arg.WithFrom,
		arg.FromTs,
		arg.WithTo,
		arg.ToTs,
		arg.WithSeek,
		arg.SeekTs,
		arg.SeekDomain,
		arg.SeekField,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogByDomainRow{}
	for rows.Next() {
		var i ChangelogByDomainRow
		if err := rows.Scan(
			&i.Ts,
			&i.Host,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ChangelogGlobal = `-- name: ChangelogGlobal :many

SELECT cl.ts, d.host, cl.field, cl.old_value, cl.new_value, cl.domain_id
FROM changelog cl JOIN domain d ON d.id = cl.domain_id
WHERE ($1::TEXT = '' OR cl.field = $1)
  AND (NOT $2::BOOL OR cl.ts >= $3::TIMESTAMPTZ)
  AND (NOT $4::BOOL OR cl.ts <= $5::TIMESTAMPTZ)
  AND (NOT $6::BOOL OR (cl.ts, cl.domain_id, cl.field) < ($7::TIMESTAMPTZ, $8::BIGINT, $9::TEXT))
ORDER BY cl.ts DESC, cl.domain_id DESC, cl.field DESC
LIMIT $10
`

type ChangelogGlobalParams struct {
	Field      string             `json:"field"`
	WithFrom   bool               `json:"with_from"`
	FromTs     pgtype.Timestamptz `json:"from_ts"`
	WithTo     bool               `json:"with_to"`
	ToTs       pgtype.Timestamptz `json:"to_ts"`
	WithSeek   bool               `json:"with_seek"`
	SeekTs     pgtype.Timestamptz `json:"seek_ts"`
	SeekDomain int64              `json:"seek_domain"`
	SeekField  string             `json:"seek_field"`
	Lim        int32              `json:"lim"`
}

type ChangelogGlobalRow struct {
	Ts       pgtype.Timestamptz `json:"ts"`
	Host     string             `json:"host"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
	DomainID int64              `json:"domain_id"`
}

// Changelog read surface (07 §4.8). Global + per-domain feeds paginate on
// the (ts, domain_id, field) DESC keyset; the scoped country/campaign feeds
// are capped to the latest-50 recent window (OPEN-15 guardrail).
func (q *Queries) ChangelogGlobal(ctx context.Context, arg ChangelogGlobalParams) ([]ChangelogGlobalRow, error) {
	rows, err := q.db.Query(ctx, ChangelogGlobal,
		arg.Field,
		arg.WithFrom,
		arg.FromTs,
		arg.WithTo,
		arg.ToTs,
		arg.WithSeek,
		arg.SeekTs,
		arg.SeekDomain,
		arg.SeekField,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogGlobalRow{}
	for rows.Next() {
		var i ChangelogGlobalRow
		if err := rows.Scan(
			&i.Ts,
			&i.Host,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.DomainID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ChangelogMaxTS = `-- name: ChangelogMaxTS :one
SELECT COALESCE(max(ts), 'epoch'::timestamptz)::timestamptz FROM changelog
`

func (q *Queries) ChangelogMaxTS(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, ChangelogMaxTS)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const ChangelogReplay = `-- name: ChangelogReplay :many
SELECT ts, field, old_value, new_value FROM changelog
WHERE domain_id = $1 ORDER BY ts ASC, field ASC
`

type ChangelogReplayRow struct {
	Ts       pgtype.Timestamptz `json:"ts"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
}

// The §4.9 confirmed-trajectory replay: the full transition history of one
// domain, ascending, reconstructed API-side (never raw scan observations).
func (q *Queries) ChangelogReplay(ctx context.Context, domainID int64) ([]ChangelogReplayRow, error) {
	rows, err := q.db.Query(ctx, ChangelogReplay, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogReplayRow{}
	for rows.Next() {
		var i ChangelogReplayRow
		if err := rows.Scan(
			&i.Ts,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ScanLatencyDaily = `-- name: ScanLatencyDaily :many
SELECT DISTINCT ON (ts::date) ts::date AS day, latency_v4_ms, latency_v6_ms
FROM scan
WHERE domain_id = $1 AND ts >= $2::TIMESTAMPTZ AND ts < $3::TIMESTAMPTZ
ORDER BY ts::date, ts DESC
`

type ScanLatencyDailyParams struct {
	DomainID int64              `json:"domain_id"`
	FromTs   pgtype.Timestamptz `json:"from_ts"`
	ToTs     pgtype.Timestamptz `json:"to_ts"`
}

type ScanLatencyDailyRow struct {
	Day         pgtype.Date `json:"day"`
	LatencyV4Ms *int32      `json:"latency_v4_ms"`
	LatencyV6Ms *int32      `json:"latency_v6_ms"`
}

// The §4.9 latency overlay: last scan measurement per day — the only value
// history takes from the scan hypertable.
func (q *Queries) ScanLatencyDaily(ctx context.Context, arg ScanLatencyDailyParams) ([]ScanLatencyDailyRow, error) {
	rows, err := q.db.Query(ctx, ScanLatencyDaily, arg.DomainID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanLatencyDailyRow{}
	for rows.Next() {
		var i ScanLatencyDailyRow
		if err := rows.Scan(&i.Day, &i.LatencyV4Ms, &i.LatencyV6Ms); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
