// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changelog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CampaignHasMember = `-- name: CampaignHasMember :one
SELECT EXISTS(
  SELECT 1 FROM campaign_domain WHERE campaign_id = $1 AND domain_id = $2
)::bool
`

type CampaignHasMemberParams struct {
	CampaignID int32 `json:"campaign_id"`
	DomainID   int64 `json:"domain_id"`
}

func (q *Queries) CampaignHasMember(ctx context.Context, arg CampaignHasMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, CampaignHasMember, arg.CampaignID, arg.DomainID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const ChangelogAnyCampaign = `-- name: ChangelogAnyCampaign :many
SELECT sub.ts, d.host, sub.field, sub.old_value, sub.new_value
FROM (SELECT DISTINCT domain_id FROM campaign_domain) m
CROSS JOIN LATERAL (
  SELECT cl.ts, cl.domain_id, cl.field, cl.old_value, cl.new_value
  FROM changelog cl
  WHERE cl.domain_id = m.domain_id
    AND cl.ts >= now() - INTERVAL '90 days'
  ORDER BY cl.ts DESC, cl.field DESC
  LIMIT 50
) sub
JOIN domain d ON d.id = sub.domain_id
ORDER BY sub.ts DESC, sub.domain_id DESC, sub.field DESC
LIMIT 50
`

type ChangelogAnyCampaignRow struct {
	Ts       pgtype.Timestamptz `json:"ts"`
	Host     string             `json:"host"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
}

// The ?scope=campaign global feed (07 §4.8): transitions of domains in ANY
// campaign. Driven from the bounded campaign_domain set via a lateral read
// of the (domain_id, ts, field) PK — never a sparse probe of the global ts
// index. Same latest-50 recent-window cap as the other scoped feeds.
func (q *Queries) ChangelogAnyCampaign(ctx context.Context) ([]ChangelogAnyCampaignRow, error) {
	rows, err := q.db.Query(ctx, ChangelogAnyCampaign)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogAnyCampaignRow{}
	for rows.Next() {
		var i ChangelogAnyCampaignRow
		if err := rows.Scan(
			&i.Ts,
			&i.Host,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ChangelogByCampaign = `-- name: ChangelogByCampaign :many
SELECT cl.ts, d.host, cl.field, cl.old_value, cl.new_value
FROM changelog cl
JOIN domain d ON d.id = cl.domain_id
JOIN campaign_domain cd ON cd.domain_id = cl.domain_id AND cd.campaign_id = $1
WHERE cl.ts >= now() - INTERVAL '90 days'
ORDER BY cl.ts DESC, cl.domain_id DESC, cl.field DESC
LIMIT 50
`

type ChangelogByCampaignRow struct {
	Ts       pgtype.Timestamptz `json:"ts"`
	Host     string             `json:"host"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
}

func (q *Queries) ChangelogByCampaign(ctx context.Context, campaignID int32) ([]ChangelogByCampaignRow, error) {
	rows, err := q.db.Query(ctx, ChangelogByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogByCampaignRow{}
	for rows.Next() {
		var i ChangelogByCampaignRow
		if err := rows.Scan(
			&i.Ts,
			&i.Host,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ChangelogByCountry = `-- name: ChangelogByCountry :many

SELECT cl.ts, d.host, cl.field, cl.old_value, cl.new_value
FROM changelog cl JOIN domain d ON d.id = cl.domain_id
WHERE d.country_id = $1
  AND cl.ts >= now() - INTERVAL '90 days'
ORDER BY cl.ts DESC, cl.domain_id DESC, cl.field DESC
LIMIT 50
`

type ChangelogByCountryRow struct {
	Ts       pgtype.Timestamptz `json:"ts"`
	Host     string             `json:"host"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
}

// db/query/changelog.sql — changelog read surface (07-api.md §4.8).
// The paginating global + per-domain feeds are builder-built in
// internal/postgres/changeloglist.go (05-schema §10.2 — one seek builder
// derives both walk directions); the scoped country/campaign feeds below
// are capped to the latest-50 recent window (OPEN-15 guardrail) and stay
// sqlc. The 90-day ts floor makes the window real: without it a sparse
// scope walks past the 60d columnstore boundary (no btree there) and can
// decompress the whole forever-retained table.
func (q *Queries) ChangelogByCountry(ctx context.Context, countryID int32) ([]ChangelogByCountryRow, error) {
	rows, err := q.db.Query(ctx, ChangelogByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogByCountryRow{}
	for rows.Next() {
		var i ChangelogByCountryRow
		if err := rows.Scan(
			&i.Ts,
			&i.Host,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ChangelogMaxTS = `-- name: ChangelogMaxTS :one
SELECT COALESCE(max(ts), 'epoch'::timestamptz)::timestamptz FROM changelog
`

func (q *Queries) ChangelogMaxTS(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, ChangelogMaxTS)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const ChangelogReplay = `-- name: ChangelogReplay :many
SELECT ts, field, old_value, new_value FROM changelog
WHERE domain_id = $1 ORDER BY ts ASC, field ASC
`

type ChangelogReplayRow struct {
	Ts       pgtype.Timestamptz `json:"ts"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
}

// The §4.9 confirmed-trajectory replay: the full transition history of one
// domain, ascending, reconstructed API-side (never raw scan observations).
func (q *Queries) ChangelogReplay(ctx context.Context, domainID int64) ([]ChangelogReplayRow, error) {
	rows, err := q.db.Query(ctx, ChangelogReplay, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangelogReplayRow{}
	for rows.Next() {
		var i ChangelogReplayRow
		if err := rows.Scan(
			&i.Ts,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ScanLatencyDaily = `-- name: ScanLatencyDaily :many
SELECT DISTINCT ON (ts::date) ts::date AS day, latency_v4_ms, latency_v6_ms
FROM scan
WHERE domain_id = $1 AND ts >= $2::TIMESTAMPTZ AND ts < $3::TIMESTAMPTZ
ORDER BY ts::date, ts DESC
`

type ScanLatencyDailyParams struct {
	DomainID int64              `json:"domain_id"`
	FromTs   pgtype.Timestamptz `json:"from_ts"`
	ToTs     pgtype.Timestamptz `json:"to_ts"`
}

type ScanLatencyDailyRow struct {
	Day         pgtype.Date `json:"day"`
	LatencyV4Ms *int32      `json:"latency_v4_ms"`
	LatencyV6Ms *int32      `json:"latency_v6_ms"`
}

// The §4.9 latency overlay: last scan measurement per day — the only value
// history takes from the scan hypertable.
func (q *Queries) ScanLatencyDaily(ctx context.Context, arg ScanLatencyDailyParams) ([]ScanLatencyDailyRow, error) {
	rows, err := q.db.Query(ctx, ScanLatencyDaily, arg.DomainID, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanLatencyDailyRow{}
	for rows.Next() {
		var i ScanLatencyDailyRow
		if err := rows.Scan(&i.Day, &i.LatencyV4Ms, &i.LatencyV6Ms); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
