// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: check_job.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const PurgeCheckJobs = `-- name: PurgeCheckJobs :execrows

DELETE FROM check_job WHERE created_at < now() - $1::interval
`

// db/query/check_job.sql — sqlc query source (layout: 05-schema.md §10.2).
// Tick step 6 — the 30d check_job purge (04 §9; key: live_check.retention).
func (q *Queries) PurgeCheckJobs(ctx context.Context, retention pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, PurgeCheckJobs, retention)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
