// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CommitDomain = `-- name: CommitDomain :execrows

UPDATE domain SET
  base_status = $1, base_observed = $2,
  base_pending = $3, base_pending_count = $4, base_since = $5,
  www_status = $6, www_observed = $7,
  www_pending = $8, www_pending_count = $9, www_since = $10,
  ns_status = $11, ns_observed = $12,
  ns_pending = $13, ns_pending_count = $14, ns_since = $15,
  mx_status = $16, mx_observed = $17,
  mx_pending = $18, mx_pending_count = $19, mx_since = $20,
  conn_status = $21, conn_observed = $22,
  conn_pending = $23, conn_pending_count = $24, conn_since = $25,
  resources_status = $26, resources_observed = $27,
  resources_pending = $28, resources_pending_count = $29,
  resources_since = $30,
  dnssec_observed = $31, ptr_observed = $32,
  smtp_observed = $33, parity_observed = $34,
  latency_v4_ms = $35, latency_v6_ms = $36,
  classification = $37, class_flags = $38, gold = $39,
  asn_id = $40, country_id = $41,
  disabled = $42, disabled_reason = $43, disabled_at = $44,
  dead_streak = $45, error_streak = $46,
  next_check_at = $47, last_checked_at = $48, last_counted_at = $49,
  claimed_at = NULL, updated_at = now()
WHERE id = $50 AND claimed_at = $51
`

type CommitDomainParams struct {
	BaseStatus            *Ipv6Status        `json:"base_status"`
	BaseObserved          *Observation       `json:"base_observed"`
	BasePending           *Ipv6Status        `json:"base_pending"`
	BasePendingCount      int16              `json:"base_pending_count"`
	BaseSince             pgtype.Timestamptz `json:"base_since"`
	WwwStatus             *Ipv6Status        `json:"www_status"`
	WwwObserved           *Observation       `json:"www_observed"`
	WwwPending            *Ipv6Status        `json:"www_pending"`
	WwwPendingCount       int16              `json:"www_pending_count"`
	WwwSince              pgtype.Timestamptz `json:"www_since"`
	NsStatus              *Ipv6Status        `json:"ns_status"`
	NsObserved            *Observation       `json:"ns_observed"`
	NsPending             *Ipv6Status        `json:"ns_pending"`
	NsPendingCount        int16              `json:"ns_pending_count"`
	NsSince               pgtype.Timestamptz `json:"ns_since"`
	MxStatus              *Ipv6Status        `json:"mx_status"`
	MxObserved            *Observation       `json:"mx_observed"`
	MxPending             *Ipv6Status        `json:"mx_pending"`
	MxPendingCount        int16              `json:"mx_pending_count"`
	MxSince               pgtype.Timestamptz `json:"mx_since"`
	ConnStatus            *Ipv6Status        `json:"conn_status"`
	ConnObserved          *Observation       `json:"conn_observed"`
	ConnPending           *Ipv6Status        `json:"conn_pending"`
	ConnPendingCount      int16              `json:"conn_pending_count"`
	ConnSince             pgtype.Timestamptz `json:"conn_since"`
	ResourcesStatus       *Ipv6Status        `json:"resources_status"`
	ResourcesObserved     *Observation       `json:"resources_observed"`
	ResourcesPending      *Ipv6Status        `json:"resources_pending"`
	ResourcesPendingCount int16              `json:"resources_pending_count"`
	ResourcesSince        pgtype.Timestamptz `json:"resources_since"`
	DnssecObserved        *Observation       `json:"dnssec_observed"`
	PtrObserved           *Observation       `json:"ptr_observed"`
	SmtpObserved          *Observation       `json:"smtp_observed"`
	ParityObserved        *Observation       `json:"parity_observed"`
	LatencyV4Ms           *int32             `json:"latency_v4_ms"`
	LatencyV6Ms           *int32             `json:"latency_v6_ms"`
	Classification        Classification     `json:"classification"`
	ClassFlags            []string           `json:"class_flags"`
	Gold                  bool               `json:"gold"`
	AsnID                 int32              `json:"asn_id"`
	CountryID             int32              `json:"country_id"`
	Disabled              bool               `json:"disabled"`
	DisabledReason        *DisabledReason    `json:"disabled_reason"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	DeadStreak            int16              `json:"dead_streak"`
	ErrorStreak           int16              `json:"error_streak"`
	NextCheckAt           pgtype.Timestamptz `json:"next_check_at"`
	Ts                    pgtype.Timestamptz `json:"ts"`
	LastCountedAt         pgtype.Timestamptz `json:"last_counted_at"`
	DomainID              int64              `json:"domain_id"`
	Lease                 pgtype.Timestamptz `json:"lease"`
}

// db/query/commit.sql — the per-domain commit write unit (03-state-machine.md
// §12). One pgx.Batch in one pgx.Tx; statement 1 is the lease-fenced UPDATE.
func (q *Queries) CommitDomain(ctx context.Context, arg CommitDomainParams) (int64, error) {
	result, err := q.db.Exec(ctx, CommitDomain,
		arg.BaseStatus,
		arg.BaseObserved,
		arg.BasePending,
		arg.BasePendingCount,
		arg.BaseSince,
		arg.WwwStatus,
		arg.WwwObserved,
		arg.WwwPending,
		arg.WwwPendingCount,
		arg.WwwSince,
		arg.NsStatus,
		arg.NsObserved,
		arg.NsPending,
		arg.NsPendingCount,
		arg.NsSince,
		arg.MxStatus,
		arg.MxObserved,
		arg.MxPending,
		arg.MxPendingCount,
		arg.MxSince,
		arg.ConnStatus,
		arg.ConnObserved,
		arg.ConnPending,
		arg.ConnPendingCount,
		arg.ConnSince,
		arg.ResourcesStatus,
		arg.ResourcesObserved,
		arg.ResourcesPending,
		arg.ResourcesPendingCount,
		arg.ResourcesSince,
		arg.DnssecObserved,
		arg.PtrObserved,
		arg.SmtpObserved,
		arg.ParityObserved,
		arg.LatencyV4Ms,
		arg.LatencyV6Ms,
		arg.Classification,
		arg.ClassFlags,
		arg.Gold,
		arg.AsnID,
		arg.CountryID,
		arg.Disabled,
		arg.DisabledReason,
		arg.DisabledAt,
		arg.DeadStreak,
		arg.ErrorStreak,
		arg.NextCheckAt,
		arg.Ts,
		arg.LastCountedAt,
		arg.DomainID,
		arg.Lease,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const EnsureResourceHost = `-- name: EnsureResourceHost :exec
INSERT INTO resource_host (host) VALUES ($1)
ON CONFLICT (host) DO NOTHING
`

func (q *Queries) EnsureResourceHost(ctx context.Context, rhost string) error {
	_, err := q.db.Exec(ctx, EnsureResourceHost, rhost)
	return err
}

const InsertChangelog = `-- name: InsertChangelog :exec
INSERT INTO changelog (domain_id, ts, field, old_value, new_value)
VALUES ($1, $2, $3, $4, $5)
`

type InsertChangelogParams struct {
	DomainID int64              `json:"domain_id"`
	Ts       pgtype.Timestamptz `json:"ts"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
}

func (q *Queries) InsertChangelog(ctx context.Context, arg InsertChangelogParams) error {
	_, err := q.db.Exec(ctx, InsertChangelog,
		arg.DomainID,
		arg.Ts,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const InsertScan = `-- name: InsertScan :exec
INSERT INTO scan (domain_id, ts, base, www, ns, mx, conn, resources,
                  dnssec, ptr, smtp, parity, latency_v4_ms, latency_v6_ms,
                  classification, country_id, asn_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13, $14,
        $15, $16, $17)
ON CONFLICT (domain_id, ts) DO NOTHING
`

type InsertScanParams struct {
	DomainID       int64              `json:"domain_id"`
	Ts             pgtype.Timestamptz `json:"ts"`
	Base           Observation        `json:"base"`
	Www            Observation        `json:"www"`
	Ns             Observation        `json:"ns"`
	Mx             Observation        `json:"mx"`
	Conn           Observation        `json:"conn"`
	Resources      Observation        `json:"resources"`
	Dnssec         *Observation       `json:"dnssec"`
	Ptr            *Observation       `json:"ptr"`
	Smtp           *Observation       `json:"smtp"`
	Parity         *Observation       `json:"parity"`
	LatencyV4Ms    *int32             `json:"latency_v4_ms"`
	LatencyV6Ms    *int32             `json:"latency_v6_ms"`
	Classification Classification     `json:"classification"`
	CountryID      *int32             `json:"country_id"`
	AsnID          *int32             `json:"asn_id"`
}

func (q *Queries) InsertScan(ctx context.Context, arg InsertScanParams) error {
	_, err := q.db.Exec(ctx, InsertScan,
		arg.DomainID,
		arg.Ts,
		arg.Base,
		arg.Www,
		arg.Ns,
		arg.Mx,
		arg.Conn,
		arg.Resources,
		arg.Dnssec,
		arg.Ptr,
		arg.Smtp,
		arg.Parity,
		arg.LatencyV4Ms,
		arg.LatencyV6Ms,
		arg.Classification,
		arg.CountryID,
		arg.AsnID,
	)
	return err
}

const InsertScanDetail = `-- name: InsertScanDetail :exec
INSERT INTO scan_detail (domain_id, ts, details, duration_ms)
VALUES ($1, $2, $3, $4)
ON CONFLICT (domain_id, ts) DO NOTHING
`

type InsertScanDetailParams struct {
	DomainID   int64              `json:"domain_id"`
	Ts         pgtype.Timestamptz `json:"ts"`
	Details    []byte             `json:"details"`
	DurationMs *int32             `json:"duration_ms"`
}

func (q *Queries) InsertScanDetail(ctx context.Context, arg InsertScanDetailParams) error {
	_, err := q.db.Exec(ctx, InsertScanDetail,
		arg.DomainID,
		arg.Ts,
		arg.Details,
		arg.DurationMs,
	)
	return err
}
