// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: country.sql

package db

import (
	"context"
)

const CountrySentinelID = `-- name: CountrySentinelID :one

SELECT id FROM country WHERE code = 'UN'
`

// db/query/country.sql — sqlc query source (layout: 05-schema.md §10.2).
// Sentinel lookup: binaries resolve the sentinel country once at startup by
// lookup, never by literal id (05-schema.md §5).
func (q *Queries) CountrySentinelID(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, CountrySentinelID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
