// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: country.sql

package db

import (
	"context"
)

const CountryCodeMap = `-- name: CountryCodeMap :many
SELECT id, code FROM country
`

type CountryCodeMapRow struct {
	ID   int32  `json:"id"`
	Code string `json:"code"`
}

func (q *Queries) CountryCodeMap(ctx context.Context) ([]CountryCodeMapRow, error) {
	rows, err := q.db.Query(ctx, CountryCodeMap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountryCodeMapRow{}
	for rows.Next() {
		var i CountryCodeMapRow
		if err := rows.Scan(&i.ID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const CountryIDByCode = `-- name: CountryIDByCode :one
SELECT id FROM country WHERE code = upper($1)::char(2)
`

func (q *Queries) CountryIDByCode(ctx context.Context, code interface{}) (int32, error) {
	row := q.db.QueryRow(ctx, CountryIDByCode, code)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const CountryIDByTLD = `-- name: CountryIDByTLD :one
SELECT id FROM country WHERE tld = $1
`

// Insert-time ccTLD attribution probe (06-ingest.md §6.5): '.NO'-form input.
func (q *Queries) CountryIDByTLD(ctx context.Context, tld *string) (int32, error) {
	row := q.db.QueryRow(ctx, CountryIDByTLD, tld)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const CountrySentinelID = `-- name: CountrySentinelID :one

SELECT id FROM country WHERE code = 'UN'
`

// db/query/country.sql — sqlc query source (layout: 05-schema.md §10.2).
// Sentinel lookup: binaries resolve the sentinel country once at startup by
// lookup, never by literal id (05-schema.md §5).
func (q *Queries) CountrySentinelID(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, CountrySentinelID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const CountryTLDMap = `-- name: CountryTLDMap :many
SELECT id, tld FROM country WHERE tld IS NOT NULL
`

type CountryTLDMapRow struct {
	ID  int32   `json:"id"`
	Tld *string `json:"tld"`
}

// The in-memory country.tld -> id map for insert-time/commit attribution
// (06-ingest.md §6.5); loaded once per run.
func (q *Queries) CountryTLDMap(ctx context.Context) ([]CountryTLDMapRow, error) {
	rows, err := q.db.Query(ctx, CountryTLDMap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountryTLDMapRow{}
	for rows.Next() {
		var i CountryTLDMapRow
		if err := rows.Scan(&i.ID, &i.Tld); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RecomputeCountryCounters = `-- name: RecomputeCountryCounters :exec
UPDATE country c SET
  sites   = agg.sites,
  v6sites = agg.v6sites,
  percent = CASE WHEN agg.sites = 0 THEN 0
                 ELSE ROUND(agg.v6sites::numeric / agg.sites::numeric * 100, 2) END
FROM (
  SELECT country_id,
         count(*)                                                      AS sites,
         count(*) FILTER (WHERE classification IN ('partial','hero'))  AS v6sites
  FROM domain
  WHERE rank IS NOT NULL AND NOT disabled
  GROUP BY country_id
) agg
WHERE c.id = agg.country_id
`

func (q *Queries) RecomputeCountryCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, RecomputeCountryCounters)
	return err
}

const ResetCountryCounters = `-- name: ResetCountryCounters :exec
UPDATE country SET sites = 0, v6sites = 0, percent = 0
`

// Tick step 3 — country counter recompute (06-ingest.md §10.6): reset, then
// recompute over the publicly-ranked scope.
func (q *Queries) ResetCountryCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ResetCountryCounters)
	return err
}
