// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: curated_subdomain.sql

package db

import (
	"context"
)

const CuratedSubdomainAdd = `-- name: CuratedSubdomainAdd :execrows


INSERT INTO curated_subdomain (domain_id) VALUES ($1) ON CONFLICT DO NOTHING
`

// db/query/curated_subdomain.sql — sqlc query source (layout: 05-schema.md §10.2).
// Membership of the curated subdomain lists (subdomains/<apex>.yml, 06): adds
// first, then one set-based removal of everything no longer listed, in the sync
// transaction. The removal must only run on a complete parse — a partial file
// set would drop live membership and start its 30-day delist grace.
func (q *Queries) CuratedSubdomainAdd(ctx context.Context, domainID int64) (int64, error) {
	result, err := q.db.Exec(ctx, CuratedSubdomainAdd, domainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const CuratedSubdomainRemoveNotIn = `-- name: CuratedSubdomainRemoveNotIn :execrows
DELETE FROM curated_subdomain WHERE domain_id <> ALL($1::bigint[])
`

// An empty (not NULL) array deletes every row: an emptied subdomains/ directory
// drops all membership, recoverable within the delist grace (04 §8). A NULL
// array matches nothing and would silently skip the diff.
func (q *Queries) CuratedSubdomainRemoveNotIn(ctx context.Context, domainIds []int64) (int64, error) {
	result, err := q.db.Exec(ctx, CuratedSubdomainRemoveNotIn, domainIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
