// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const BadgeDomain = `-- name: BadgeDomain :one
SELECT classification, gold, disabled FROM domain WHERE host = $1
`

type BadgeDomainRow struct {
	Classification Classification `json:"classification"`
	Gold           bool           `json:"gold"`
	Disabled       bool           `json:"disabled"`
}

// The badge read (07 §5.2): read-only, zero side effects, any kind/origin.
func (q *Queries) BadgeDomain(ctx context.Context, host string) (BadgeDomainRow, error) {
	row := q.db.QueryRow(ctx, BadgeDomain, host)
	var i BadgeDomainRow
	err := row.Scan(&i.Classification, &i.Gold, &i.Disabled)
	return i, err
}

const ClaimBatchByAge = `-- name: ClaimBatchByAge :many
UPDATE domain SET claimed_at = now()
WHERE id IN (
  SELECT id FROM domain
  WHERE (NOT disabled OR disabled_reason IN ('dead', 'delisted'))
    AND next_check_at <= now()
    AND (claimed_at IS NULL OR claimed_at < now() - interval '30 minutes')
  ORDER BY next_check_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING
  id, host, kind, rank, claimed_at,
  disabled, disabled_reason, disabled_at,
  dead_streak, error_streak, last_counted_at,
  asn_id, country_id,
  base_status, base_pending, base_pending_count, base_since,
  www_status, www_pending, www_pending_count, www_since,
  ns_status, ns_pending, ns_pending_count, ns_since,
  mx_status, mx_pending, mx_pending_count, mx_since,
  conn_status, conn_pending, conn_pending_count, conn_since,
  resources_status, resources_pending, resources_pending_count, resources_since
`

type ClaimBatchByAgeRow struct {
	ID                    int64              `json:"id"`
	Host                  string             `json:"host"`
	Kind                  DomainKind         `json:"kind"`
	Rank                  *int32             `json:"rank"`
	ClaimedAt             pgtype.Timestamptz `json:"claimed_at"`
	Disabled              bool               `json:"disabled"`
	DisabledReason        *DisabledReason    `json:"disabled_reason"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	DeadStreak            int16              `json:"dead_streak"`
	ErrorStreak           int16              `json:"error_streak"`
	LastCountedAt         pgtype.Timestamptz `json:"last_counted_at"`
	AsnID                 int32              `json:"asn_id"`
	CountryID             int32              `json:"country_id"`
	BaseStatus            *Ipv6Status        `json:"base_status"`
	BasePending           *Ipv6Status        `json:"base_pending"`
	BasePendingCount      int16              `json:"base_pending_count"`
	BaseSince             pgtype.Timestamptz `json:"base_since"`
	WwwStatus             *Ipv6Status        `json:"www_status"`
	WwwPending            *Ipv6Status        `json:"www_pending"`
	WwwPendingCount       int16              `json:"www_pending_count"`
	WwwSince              pgtype.Timestamptz `json:"www_since"`
	NsStatus              *Ipv6Status        `json:"ns_status"`
	NsPending             *Ipv6Status        `json:"ns_pending"`
	NsPendingCount        int16              `json:"ns_pending_count"`
	NsSince               pgtype.Timestamptz `json:"ns_since"`
	MxStatus              *Ipv6Status        `json:"mx_status"`
	MxPending             *Ipv6Status        `json:"mx_pending"`
	MxPendingCount        int16              `json:"mx_pending_count"`
	MxSince               pgtype.Timestamptz `json:"mx_since"`
	ConnStatus            *Ipv6Status        `json:"conn_status"`
	ConnPending           *Ipv6Status        `json:"conn_pending"`
	ConnPendingCount      int16              `json:"conn_pending_count"`
	ConnSince             pgtype.Timestamptz `json:"conn_since"`
	ResourcesStatus       *Ipv6Status        `json:"resources_status"`
	ResourcesPending      *Ipv6Status        `json:"resources_pending"`
	ResourcesPendingCount int16              `json:"resources_pending_count"`
	ResourcesSince        pgtype.Timestamptz `json:"resources_since"`
}

// The claim.order=age variant: aging pressure valve, no sort at all beyond
// the index order (04 §3).
func (q *Queries) ClaimBatchByAge(ctx context.Context, limit int32) ([]ClaimBatchByAgeRow, error) {
	rows, err := q.db.Query(ctx, ClaimBatchByAge, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimBatchByAgeRow{}
	for rows.Next() {
		var i ClaimBatchByAgeRow
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Kind,
			&i.Rank,
			&i.ClaimedAt,
			&i.Disabled,
			&i.DisabledReason,
			&i.DisabledAt,
			&i.DeadStreak,
			&i.ErrorStreak,
			&i.LastCountedAt,
			&i.AsnID,
			&i.CountryID,
			&i.BaseStatus,
			&i.BasePending,
			&i.BasePendingCount,
			&i.BaseSince,
			&i.WwwStatus,
			&i.WwwPending,
			&i.WwwPendingCount,
			&i.WwwSince,
			&i.NsStatus,
			&i.NsPending,
			&i.NsPendingCount,
			&i.NsSince,
			&i.MxStatus,
			&i.MxPending,
			&i.MxPendingCount,
			&i.MxSince,
			&i.ConnStatus,
			&i.ConnPending,
			&i.ConnPendingCount,
			&i.ConnSince,
			&i.ResourcesStatus,
			&i.ResourcesPending,
			&i.ResourcesPendingCount,
			&i.ResourcesSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ClaimBatchByRank = `-- name: ClaimBatchByRank :many
UPDATE domain SET claimed_at = now()
WHERE id IN (
  SELECT id FROM domain
  WHERE (NOT disabled OR disabled_reason IN ('dead', 'delisted'))
    AND next_check_at <= now()
    AND (claimed_at IS NULL OR claimed_at < now() - interval '30 minutes')
  ORDER BY rank ASC NULLS LAST, next_check_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING
  id, host, kind, rank, claimed_at,
  disabled, disabled_reason, disabled_at,
  dead_streak, error_streak, last_counted_at,
  asn_id, country_id,
  base_status, base_pending, base_pending_count, base_since,
  www_status, www_pending, www_pending_count, www_since,
  ns_status, ns_pending, ns_pending_count, ns_since,
  mx_status, mx_pending, mx_pending_count, mx_since,
  conn_status, conn_pending, conn_pending_count, conn_since,
  resources_status, resources_pending, resources_pending_count, resources_since
`

type ClaimBatchByRankRow struct {
	ID                    int64              `json:"id"`
	Host                  string             `json:"host"`
	Kind                  DomainKind         `json:"kind"`
	Rank                  *int32             `json:"rank"`
	ClaimedAt             pgtype.Timestamptz `json:"claimed_at"`
	Disabled              bool               `json:"disabled"`
	DisabledReason        *DisabledReason    `json:"disabled_reason"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	DeadStreak            int16              `json:"dead_streak"`
	ErrorStreak           int16              `json:"error_streak"`
	LastCountedAt         pgtype.Timestamptz `json:"last_counted_at"`
	AsnID                 int32              `json:"asn_id"`
	CountryID             int32              `json:"country_id"`
	BaseStatus            *Ipv6Status        `json:"base_status"`
	BasePending           *Ipv6Status        `json:"base_pending"`
	BasePendingCount      int16              `json:"base_pending_count"`
	BaseSince             pgtype.Timestamptz `json:"base_since"`
	WwwStatus             *Ipv6Status        `json:"www_status"`
	WwwPending            *Ipv6Status        `json:"www_pending"`
	WwwPendingCount       int16              `json:"www_pending_count"`
	WwwSince              pgtype.Timestamptz `json:"www_since"`
	NsStatus              *Ipv6Status        `json:"ns_status"`
	NsPending             *Ipv6Status        `json:"ns_pending"`
	NsPendingCount        int16              `json:"ns_pending_count"`
	NsSince               pgtype.Timestamptz `json:"ns_since"`
	MxStatus              *Ipv6Status        `json:"mx_status"`
	MxPending             *Ipv6Status        `json:"mx_pending"`
	MxPendingCount        int16              `json:"mx_pending_count"`
	MxSince               pgtype.Timestamptz `json:"mx_since"`
	ConnStatus            *Ipv6Status        `json:"conn_status"`
	ConnPending           *Ipv6Status        `json:"conn_pending"`
	ConnPendingCount      int16              `json:"conn_pending_count"`
	ConnSince             pgtype.Timestamptz `json:"conn_since"`
	ResourcesStatus       *Ipv6Status        `json:"resources_status"`
	ResourcesPending      *Ipv6Status        `json:"resources_pending"`
	ResourcesPendingCount int16              `json:"resources_pending_count"`
	ResourcesSince        pgtype.Timestamptz `json:"resources_since"`
}

// The frontier claim (04-lifecycle-scheduling.md §3). One statement per claim
// cycle; all rows in a batch share one claimed_at (the lease token L). The
// eligibility predicate textually matches idx_domain_due (05-schema §1.7).
func (q *Queries) ClaimBatchByRank(ctx context.Context, limit int32) ([]ClaimBatchByRankRow, error) {
	rows, err := q.db.Query(ctx, ClaimBatchByRank, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimBatchByRankRow{}
	for rows.Next() {
		var i ClaimBatchByRankRow
		if err := rows.Scan(
			&i.ID,
			&i.Host,
			&i.Kind,
			&i.Rank,
			&i.ClaimedAt,
			&i.Disabled,
			&i.DisabledReason,
			&i.DisabledAt,
			&i.DeadStreak,
			&i.ErrorStreak,
			&i.LastCountedAt,
			&i.AsnID,
			&i.CountryID,
			&i.BaseStatus,
			&i.BasePending,
			&i.BasePendingCount,
			&i.BaseSince,
			&i.WwwStatus,
			&i.WwwPending,
			&i.WwwPendingCount,
			&i.WwwSince,
			&i.NsStatus,
			&i.NsPending,
			&i.NsPendingCount,
			&i.NsSince,
			&i.MxStatus,
			&i.MxPending,
			&i.MxPendingCount,
			&i.MxSince,
			&i.ConnStatus,
			&i.ConnPending,
			&i.ConnPendingCount,
			&i.ConnSince,
			&i.ResourcesStatus,
			&i.ResourcesPending,
			&i.ResourcesPendingCount,
			&i.ResourcesSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const DomainByHost = `-- name: DomainByHost :one

SELECT id, host, kind, parent_id, disabled, disabled_reason
FROM domain WHERE host = $1
`

type DomainByHostRow struct {
	ID             int64           `json:"id"`
	Host           string          `json:"host"`
	Kind           DomainKind      `json:"kind"`
	ParentID       *int64          `json:"parent_id"`
	Disabled       bool            `json:"disabled"`
	DisabledReason *DisabledReason `json:"disabled_reason"`
}

// db/query/domain.sql — sqlc query source (layout: 05-schema.md §10.2).
func (q *Queries) DomainByHost(ctx context.Context, host string) (DomainByHostRow, error) {
	row := q.db.QueryRow(ctx, DomainByHost, host)
	var i DomainByHostRow
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Kind,
		&i.ParentID,
		&i.Disabled,
		&i.DisabledReason,
	)
	return i, err
}

const DomainConfirmed = `-- name: DomainConfirmed :one

SELECT id, kind, classification, class_flags, gold,
       base_status, base_since, www_status, www_since, ns_status, ns_since,
       mx_status, mx_since, conn_status, conn_since, resources_status, resources_since,
       last_checked_at, disabled, disabled_reason
FROM domain WHERE host = $1
`

type DomainConfirmedRow struct {
	ID              int64              `json:"id"`
	Kind            DomainKind         `json:"kind"`
	Classification  Classification     `json:"classification"`
	ClassFlags      []string           `json:"class_flags"`
	Gold            bool               `json:"gold"`
	BaseStatus      *Ipv6Status        `json:"base_status"`
	BaseSince       pgtype.Timestamptz `json:"base_since"`
	WwwStatus       *Ipv6Status        `json:"www_status"`
	WwwSince        pgtype.Timestamptz `json:"www_since"`
	NsStatus        *Ipv6Status        `json:"ns_status"`
	NsSince         pgtype.Timestamptz `json:"ns_since"`
	MxStatus        *Ipv6Status        `json:"mx_status"`
	MxSince         pgtype.Timestamptz `json:"mx_since"`
	ConnStatus      *Ipv6Status        `json:"conn_status"`
	ConnSince       pgtype.Timestamptz `json:"conn_since"`
	ResourcesStatus *Ipv6Status        `json:"resources_status"`
	ResourcesSince  pgtype.Timestamptz `json:"resources_since"`
	LastCheckedAt   pgtype.Timestamptz `json:"last_checked_at"`
	Disabled        bool               `json:"disabled"`
	DisabledReason  *DisabledReason    `json:"disabled_reason"`
}

// The §5.1 live-check domain reads/writes.
func (q *Queries) DomainConfirmed(ctx context.Context, host string) (DomainConfirmedRow, error) {
	row := q.db.QueryRow(ctx, DomainConfirmed, host)
	var i DomainConfirmedRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Classification,
		&i.ClassFlags,
		&i.Gold,
		&i.BaseStatus,
		&i.BaseSince,
		&i.WwwStatus,
		&i.WwwSince,
		&i.NsStatus,
		&i.NsSince,
		&i.MxStatus,
		&i.MxSince,
		&i.ConnStatus,
		&i.ConnSince,
		&i.ResourcesStatus,
		&i.ResourcesSince,
		&i.LastCheckedAt,
		&i.Disabled,
		&i.DisabledReason,
	)
	return i, err
}

const DomainDetailByHost = `-- name: DomainDetailByHost :one
SELECT d.id, d.host, d.rank, d.kind, p.host AS parent,
  d.classification, d.class_flags, d.gold,
  d.base_status, d.base_since, d.www_status, d.www_since,
  d.ns_status, d.ns_since, d.mx_status, d.mx_since,
  d.conn_status, d.conn_since, d.resources_status, d.resources_since,
  d.dnssec_observed, d.ptr_observed, d.smtp_observed, d.parity_observed,
  d.latency_v4_ms, d.latency_v6_ms,
  d.tld, c.code AS country_code, c.name AS country_name, c.tld AS country_tld,
  a.number AS asn_number, a.name AS asn_name,
  dp.id AS provider_id, dp.name AS provider_name,
  d.hosting_provider,
  (SELECT count(*) FROM domain ch WHERE ch.parent_id = d.id AND NOT ch.disabled) AS subdomain_count,
  d.disabled, d.last_checked_at, d.created_at
FROM domain d
JOIN country c ON c.id = d.country_id
JOIN asn a ON a.id = d.asn_id
LEFT JOIN dns_provider dp ON dp.id = d.dns_provider_id
LEFT JOIN domain p ON p.id = d.parent_id
WHERE d.host = $1
`

type DomainDetailByHostRow struct {
	ID              int64              `json:"id"`
	Host            string             `json:"host"`
	Rank            *int32             `json:"rank"`
	Kind            DomainKind         `json:"kind"`
	Parent          *string            `json:"parent"`
	Classification  Classification     `json:"classification"`
	ClassFlags      []string           `json:"class_flags"`
	Gold            bool               `json:"gold"`
	BaseStatus      *Ipv6Status        `json:"base_status"`
	BaseSince       pgtype.Timestamptz `json:"base_since"`
	WwwStatus       *Ipv6Status        `json:"www_status"`
	WwwSince        pgtype.Timestamptz `json:"www_since"`
	NsStatus        *Ipv6Status        `json:"ns_status"`
	NsSince         pgtype.Timestamptz `json:"ns_since"`
	MxStatus        *Ipv6Status        `json:"mx_status"`
	MxSince         pgtype.Timestamptz `json:"mx_since"`
	ConnStatus      *Ipv6Status        `json:"conn_status"`
	ConnSince       pgtype.Timestamptz `json:"conn_since"`
	ResourcesStatus *Ipv6Status        `json:"resources_status"`
	ResourcesSince  pgtype.Timestamptz `json:"resources_since"`
	DnssecObserved  *Observation       `json:"dnssec_observed"`
	PtrObserved     *Observation       `json:"ptr_observed"`
	SmtpObserved    *Observation       `json:"smtp_observed"`
	ParityObserved  *Observation       `json:"parity_observed"`
	LatencyV4Ms     *int32             `json:"latency_v4_ms"`
	LatencyV6Ms     *int32             `json:"latency_v6_ms"`
	Tld             *string            `json:"tld"`
	CountryCode     string             `json:"country_code"`
	CountryName     string             `json:"country_name"`
	CountryTld      *string            `json:"country_tld"`
	AsnNumber       int64              `json:"asn_number"`
	AsnName         string             `json:"asn_name"`
	ProviderID      *int64             `json:"provider_id"`
	ProviderName    *string            `json:"provider_name"`
	HostingProvider *string            `json:"hosting_provider"`
	SubdomainCount  int64              `json:"subdomain_count"`
	Disabled        bool               `json:"disabled"`
	LastCheckedAt   pgtype.Timestamptz `json:"last_checked_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) DomainDetailByHost(ctx context.Context, host string) (DomainDetailByHostRow, error) {
	row := q.db.QueryRow(ctx, DomainDetailByHost, host)
	var i DomainDetailByHostRow
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Rank,
		&i.Kind,
		&i.Parent,
		&i.Classification,
		&i.ClassFlags,
		&i.Gold,
		&i.BaseStatus,
		&i.BaseSince,
		&i.WwwStatus,
		&i.WwwSince,
		&i.NsStatus,
		&i.NsSince,
		&i.MxStatus,
		&i.MxSince,
		&i.ConnStatus,
		&i.ConnSince,
		&i.ResourcesStatus,
		&i.ResourcesSince,
		&i.DnssecObserved,
		&i.PtrObserved,
		&i.SmtpObserved,
		&i.ParityObserved,
		&i.LatencyV4Ms,
		&i.LatencyV6Ms,
		&i.Tld,
		&i.CountryCode,
		&i.CountryName,
		&i.CountryTld,
		&i.AsnNumber,
		&i.AsnName,
		&i.ProviderID,
		&i.ProviderName,
		&i.HostingProvider,
		&i.SubdomainCount,
		&i.Disabled,
		&i.LastCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const DomainDisable = `-- name: DomainDisable :execrows

UPDATE domain
SET disabled = true, disabled_reason = $1, disabled_at = now(), updated_at = now()
WHERE host = $2 AND NOT disabled
`

type DomainDisableParams struct {
	Reason *DisabledReason `json:"reason"`
	Host   string          `json:"host"`
}

// Operator disable/enable (P2.14; glossary: service/manual lifecycle).
func (q *Queries) DomainDisable(ctx context.Context, arg DomainDisableParams) (int64, error) {
	result, err := q.db.Exec(ctx, DomainDisable, arg.Reason, arg.Host)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DomainEnable = `-- name: DomainEnable :execrows
UPDATE domain
SET disabled = false, disabled_reason = NULL, disabled_at = NULL,
    next_check_at = now(), updated_at = now()
WHERE host = $1 AND disabled AND disabled_reason IN ('manual', 'service')
`

func (q *Queries) DomainEnable(ctx context.Context, host string) (int64, error) {
	result, err := q.db.Exec(ctx, DomainEnable, host)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DomainInsertEntity = `-- name: DomainInsertEntity :one
INSERT INTO domain (host, kind, parent_id, rank, created_by, asn_id, country_id, tld, next_check_at)
VALUES ($1, $2, $3, NULL, $4, $5, $6, $7, now())
ON CONFLICT (host) DO NOTHING
RETURNING id
`

type DomainInsertEntityParams struct {
	Host      string     `json:"host"`
	Kind      DomainKind `json:"kind"`
	ParentID  *int64     `json:"parent_id"`
	CreatedBy CreatedBy  `json:"created_by"`
	AsnID     int32      `json:"asn_id"`
	CountryID int32      `json:"country_id"`
	Tld       *string    `json:"tld"`
}

func (q *Queries) DomainInsertEntity(ctx context.Context, arg DomainInsertEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, DomainInsertEntity,
		arg.Host,
		arg.Kind,
		arg.ParentID,
		arg.CreatedBy,
		arg.AsnID,
		arg.CountryID,
		arg.Tld,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const DomainInsertLiveCheck = `-- name: DomainInsertLiveCheck :one
INSERT INTO domain (host, kind, parent_id, rank, created_by, asn_id, country_id, tld, last_requested_at, next_check_at)
VALUES ($1, $2, $3, NULL, 'live_check', $4, $5, $6, now(), now())
ON CONFLICT (host) DO NOTHING
RETURNING id
`

type DomainInsertLiveCheckParams struct {
	Host      string     `json:"host"`
	Kind      DomainKind `json:"kind"`
	ParentID  *int64     `json:"parent_id"`
	AsnID     int32      `json:"asn_id"`
	CountryID int32      `json:"country_id"`
	Tld       *string    `json:"tld"`
}

// The consumer's entity insert (07 §5.1.5 step 2): parent only if it
// ALREADY exists — live checks never auto-ensure parents.
func (q *Queries) DomainInsertLiveCheck(ctx context.Context, arg DomainInsertLiveCheckParams) (int64, error) {
	row := q.db.QueryRow(ctx, DomainInsertLiveCheck,
		arg.Host,
		arg.Kind,
		arg.ParentID,
		arg.AsnID,
		arg.CountryID,
		arg.Tld,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const DomainLiveCheckReentry = `-- name: DomainLiveCheckReentry :exec
UPDATE domain SET
  last_requested_at = now(),
  disabled        = CASE WHEN disabled_reason = 'delisted' THEN false ELSE disabled END,
  disabled_at     = CASE WHEN disabled_reason = 'delisted' THEN NULL ELSE disabled_at END,
  orphaned_at     = CASE WHEN disabled_reason = 'delisted' THEN NULL ELSE orphaned_at END,
  next_check_at   = CASE WHEN disabled_reason IN ('delisted', 'dead') THEN now() ELSE next_check_at END,
  disabled_reason = CASE WHEN disabled_reason = 'delisted' THEN NULL ELSE disabled_reason END,
  updated_at      = now()
WHERE host = $1
`

// Lifecycle re-entry (07 §5.1.6): every POST /check on an existing host.
func (q *Queries) DomainLiveCheckReentry(ctx context.Context, host string) error {
	_, err := q.db.Exec(ctx, DomainLiveCheckReentry, host)
	return err
}

const DomainMembershipReEntry = `-- name: DomainMembershipReEntry :exec
UPDATE domain SET
  disabled        = CASE WHEN disabled_reason = 'delisted' THEN false ELSE disabled END,
  disabled_at     = CASE WHEN disabled_reason = 'delisted' THEN NULL ELSE disabled_at END,
  next_check_at   = now(),
  disabled_reason = CASE WHEN disabled_reason = 'delisted' THEN NULL ELSE disabled_reason END,
  updated_at      = now()
WHERE id = $1 AND disabled_reason IN ('delisted', 'dead')
`

func (q *Queries) DomainMembershipReEntry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DomainMembershipReEntry, id)
	return err
}

const SubdomainExactCount = `-- name: SubdomainExactCount :one
SELECT count(*) FROM domain WHERE parent_id = $1 AND NOT disabled
`

func (q *Queries) SubdomainExactCount(ctx context.Context, parentID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, SubdomainExactCount, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SweepClearOrphans = `-- name: SweepClearOrphans :execrows

UPDATE domain d
SET orphaned_at = NULL, updated_at = now()
WHERE d.orphaned_at IS NOT NULL
  AND (d.rank IS NOT NULL
    OR EXISTS (SELECT 1 FROM campaign_domain cd
               JOIN campaign c ON c.id = cd.campaign_id AND NOT c.disabled
               WHERE cd.domain_id = d.id)
    OR EXISTS (SELECT 1 FROM domain ch WHERE ch.parent_id = d.id)
    OR d.last_requested_at >= now() - $1::interval)
`

// The daily lifecycle sweep S1–S5 (04-lifecycle-scheduling.md §8): one
// transaction, set-based; the linkage predicate is spelled identically in
// every statement. @live_check_linkage / @delist_grace / @slow_lane_every.
func (q *Queries) SweepClearOrphans(ctx context.Context, liveCheckLinkage pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, SweepClearOrphans, liveCheckLinkage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SweepDelistExpired = `-- name: SweepDelistExpired :execrows
UPDATE domain d
SET disabled = true, disabled_reason = 'delisted', disabled_at = now(),
    next_check_at = now() + $1::interval, updated_at = now()
WHERE NOT d.disabled AND d.rank IS NULL AND d.created_by <> 'live_check'
  AND NOT (
       EXISTS (SELECT 1 FROM campaign_domain cd
               JOIN campaign c ON c.id = cd.campaign_id AND NOT c.disabled
               WHERE cd.domain_id = d.id)
    OR EXISTS (SELECT 1 FROM domain ch WHERE ch.parent_id = d.id)
    -- NULL-safe (deviation from 04 §8's literal text): a never-live-checked
    -- row has last_requested_at NULL; the raw >= comparison makes NOT(...)
    -- NULL and silently exempts the row from S3–S5.
    OR COALESCE(d.last_requested_at >= now() - $2::interval, false))
  AND d.orphaned_at IS NOT NULL AND d.orphaned_at < now() - $3::interval
`

type SweepDelistExpiredParams struct {
	SlowLaneEvery    pgtype.Interval `json:"slow_lane_every"`
	LiveCheckLinkage pgtype.Interval `json:"live_check_linkage"`
	DelistGrace      pgtype.Interval `json:"delist_grace"`
}

func (q *Queries) SweepDelistExpired(ctx context.Context, arg SweepDelistExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, SweepDelistExpired, arg.SlowLaneEvery, arg.LiveCheckLinkage, arg.DelistGrace)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SweepDelistLiveCheck = `-- name: SweepDelistLiveCheck :execrows
UPDATE domain d
SET disabled = true, disabled_reason = 'delisted', disabled_at = now(),
    next_check_at = now() + $1::interval, updated_at = now()
WHERE NOT d.disabled AND d.rank IS NULL AND d.created_by = 'live_check'
  AND NOT (
       EXISTS (SELECT 1 FROM campaign_domain cd
               JOIN campaign c ON c.id = cd.campaign_id AND NOT c.disabled
               WHERE cd.domain_id = d.id)
    OR EXISTS (SELECT 1 FROM domain ch WHERE ch.parent_id = d.id)
    -- NULL-safe (deviation from 04 §8's literal text): a never-live-checked
    -- row has last_requested_at NULL; the raw >= comparison makes NOT(...)
    -- NULL and silently exempts the row from S3–S5.
    OR COALESCE(d.last_requested_at >= now() - $2::interval, false))
`

type SweepDelistLiveCheckParams struct {
	SlowLaneEvery    pgtype.Interval `json:"slow_lane_every"`
	LiveCheckLinkage pgtype.Interval `json:"live_check_linkage"`
}

func (q *Queries) SweepDelistLiveCheck(ctx context.Context, arg SweepDelistLiveCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, SweepDelistLiveCheck, arg.SlowLaneEvery, arg.LiveCheckLinkage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SweepReenableDelisted = `-- name: SweepReenableDelisted :execrows
UPDATE domain d
SET disabled = false, disabled_reason = NULL, disabled_at = NULL,
    orphaned_at = NULL, next_check_at = now(), updated_at = now()
WHERE d.disabled AND d.disabled_reason = 'delisted'
  AND (d.rank IS NOT NULL
    OR EXISTS (SELECT 1 FROM campaign_domain cd
               JOIN campaign c ON c.id = cd.campaign_id AND NOT c.disabled
               WHERE cd.domain_id = d.id)
    OR EXISTS (SELECT 1 FROM domain ch WHERE ch.parent_id = d.id)
    OR d.last_requested_at >= now() - $1::interval)
`

func (q *Queries) SweepReenableDelisted(ctx context.Context, liveCheckLinkage pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, SweepReenableDelisted, liveCheckLinkage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SweepStampOrphans = `-- name: SweepStampOrphans :execrows
UPDATE domain d
SET orphaned_at = now(), updated_at = now()
WHERE NOT d.disabled AND d.rank IS NULL AND d.created_by <> 'live_check'
  AND NOT (
       EXISTS (SELECT 1 FROM campaign_domain cd
               JOIN campaign c ON c.id = cd.campaign_id AND NOT c.disabled
               WHERE cd.domain_id = d.id)
    OR EXISTS (SELECT 1 FROM domain ch WHERE ch.parent_id = d.id)
    -- NULL-safe (deviation from 04 §8's literal text): a never-live-checked
    -- row has last_requested_at NULL; the raw >= comparison makes NOT(...)
    -- NULL and silently exempts the row from S3–S5.
    OR COALESCE(d.last_requested_at >= now() - $1::interval, false))
  AND d.orphaned_at IS NULL
`

func (q *Queries) SweepStampOrphans(ctx context.Context, liveCheckLinkage pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, SweepStampOrphans, liveCheckLinkage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
