// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain.sql

package db

import (
	"context"
)

const DomainByHost = `-- name: DomainByHost :one

SELECT id, host, kind, parent_id, disabled, disabled_reason
FROM domain WHERE host = $1
`

type DomainByHostRow struct {
	ID             int64           `json:"id"`
	Host           string          `json:"host"`
	Kind           DomainKind      `json:"kind"`
	ParentID       *int64          `json:"parent_id"`
	Disabled       bool            `json:"disabled"`
	DisabledReason *DisabledReason `json:"disabled_reason"`
}

// db/query/domain.sql — sqlc query source (layout: 05-schema.md §10.2).
func (q *Queries) DomainByHost(ctx context.Context, host string) (DomainByHostRow, error) {
	row := q.db.QueryRow(ctx, DomainByHost, host)
	var i DomainByHostRow
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.Kind,
		&i.ParentID,
		&i.Disabled,
		&i.DisabledReason,
	)
	return i, err
}

const DomainInsertEntity = `-- name: DomainInsertEntity :one
INSERT INTO domain (host, kind, parent_id, rank, created_by, asn_id, country_id, tld, next_check_at)
VALUES ($1, $2, $3, NULL, $4, $5, $6, $7, now())
ON CONFLICT (host) DO NOTHING
RETURNING id
`

type DomainInsertEntityParams struct {
	Host      string     `json:"host"`
	Kind      DomainKind `json:"kind"`
	ParentID  *int64     `json:"parent_id"`
	CreatedBy CreatedBy  `json:"created_by"`
	AsnID     int32      `json:"asn_id"`
	CountryID int32      `json:"country_id"`
	Tld       *string    `json:"tld"`
}

func (q *Queries) DomainInsertEntity(ctx context.Context, arg DomainInsertEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, DomainInsertEntity,
		arg.Host,
		arg.Kind,
		arg.ParentID,
		arg.CreatedBy,
		arg.AsnID,
		arg.CountryID,
		arg.Tld,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const DomainMembershipReEntry = `-- name: DomainMembershipReEntry :exec
UPDATE domain SET
  disabled        = CASE WHEN disabled_reason = 'delisted' THEN false ELSE disabled END,
  disabled_at     = CASE WHEN disabled_reason = 'delisted' THEN NULL ELSE disabled_at END,
  next_check_at   = now(),
  disabled_reason = CASE WHEN disabled_reason = 'delisted' THEN NULL ELSE disabled_reason END,
  updated_at      = now()
WHERE id = $1 AND disabled_reason IN ('delisted', 'dead')
`

func (q *Queries) DomainMembershipReEntry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, DomainMembershipReEntry, id)
	return err
}
