// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosting.sql

package db

import (
	"context"
)

const HostingLeaderboard = `-- name: HostingLeaderboard :many
SELECT slug, name, count_total, count_v6
FROM hosting_provider
ORDER BY count_total DESC, slug ASC
`

type HostingLeaderboardRow struct {
	Slug       string `json:"slug"`
	Name       string `json:"name"`
	CountTotal int32  `json:"count_total"`
	CountV6    int32  `json:"count_v6"`
}

// The API hosting league (07 §4.6): exact stored counters, count_v4
// synthesized server-side. Rows that attribution has never produced stay at
// zero rather than being hidden — the seed set is the documented vocabulary.
func (q *Queries) HostingLeaderboard(ctx context.Context) ([]HostingLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, HostingLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HostingLeaderboardRow{}
	for rows.Next() {
		var i HostingLeaderboardRow
		if err := rows.Scan(
			&i.Slug,
			&i.Name,
			&i.CountTotal,
			&i.CountV6,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RecomputeHostingCounters = `-- name: RecomputeHostingCounters :exec
INSERT INTO hosting_provider (slug, name, count_total, count_v6)
SELECT hosting_provider, hosting_provider,
       count(*),
       count(*) FILTER (WHERE classification IN ('partial','hero'))
FROM domain
WHERE rank IS NOT NULL AND NOT disabled AND hosting_provider IS NOT NULL
GROUP BY hosting_provider
ON CONFLICT (slug) DO UPDATE SET
  count_total = excluded.count_total,
  count_v6    = excluded.count_v6
`

// Upsert rather than UPDATE...FROM: a slug newly emitted by the attribution
// code has no seeded row yet, and it must join the league under its own slug
// as a display name rather than vanish. ON CONFLICT touches only the
// counters, so the curated display names survive every tick.
func (q *Queries) RecomputeHostingCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, RecomputeHostingCounters)
	return err
}

const ResetHostingCounters = `-- name: ResetHostingCounters :exec

UPDATE hosting_provider SET count_total = 0, count_v6 = 0
`

// db/query/hosting.sql — hosting/CDN registry (layout: 05-schema.md §10.2).
// Tick step 3 — hosting counter recompute, beside the ASN and DNS-provider
// pairs (06-ingest.md §10.6).
//
// Population and v6 predicate deliberately match RecomputeASNCounters and
// RecomputeProviderCounters exactly: ranked, not disabled, and v6 meaning
// classification IN ('partial','hero'). All three registries render in one
// switcher on /metrics with shared axes and a shared colour ramp, so a
// different population or a different v6 definition here would silently
// change what the chart means when the reader switches entity.
func (q *Queries) ResetHostingCounters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ResetHostingCounters)
	return err
}
