// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CrawlerThroughput = `-- name: CrawlerThroughput :one
SELECT
  (SELECT COALESCE(sum(processed), 0)::bigint FROM crawler_metrics
     WHERE ts >= now() - interval '24 hours') AS checked_24h,
  (SELECT max(ts) FROM crawler_metrics)::timestamptz AS latest
`

type CrawlerThroughputRow struct {
	Checked24h int64              `json:"checked_24h"`
	Latest     pgtype.Timestamptz `json:"latest"`
}

// The public throughput read behind GET /stats/crawler (07 §4.10).
//
// The SELECT list is the entire point of this query and must stay these two
// values. crawler_metrics is internal telemetry: worker, run_id, queue_depth,
// qps, p50_ms/p99_ms, dim_counters (which carries the lease_lost fence-abort
// counter) and is_final all describe how the crawler is deployed, not what it
// found, and none of them is public. A contract test asserts negatively that
// those names never appear in the response — widening this list will fail it.
//
// checked_24h sums the checkpoint deltas (processed resets at every
// checkpoint, so summing across workers and rows is correct) and counts check
// operations attempted, including retries and failures — deliberately not
// distinct hosts, so it can exceed the tracked-domain count. is_final rows are
// included: they carry the shutdown tail delta.
//
// latest is the newest observation regardless of the 24h window, so a dead
// crawler shows a stale timestamp rather than null. The idle loop checkpoints
// every 5 minutes even on a drained frontier, so staleness means a dead
// process, not a quiet one.
func (q *Queries) CrawlerThroughput(ctx context.Context) (CrawlerThroughputRow, error) {
	row := q.db.QueryRow(ctx, CrawlerThroughput)
	var i CrawlerThroughputRow
	err := row.Scan(&i.Checked24h, &i.Latest)
	return i, err
}

const InsertCrawlerMetrics = `-- name: InsertCrawlerMetrics :exec

INSERT INTO crawler_metrics (run_id, worker, processed, succeeded, failed, qps,
                             p50_ms, p99_ms, queue_depth,
                             dim_counters, geoip_build_epoch, is_final)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9,
        $10, $11, $12)
`

type InsertCrawlerMetricsParams struct {
	RunID           pgtype.UUID        `json:"run_id"`
	Worker          string             `json:"worker"`
	Processed       *int32             `json:"processed"`
	Succeeded       *int32             `json:"succeeded"`
	Failed          *int32             `json:"failed"`
	Qps             *float32           `json:"qps"`
	P50Ms           *int32             `json:"p50_ms"`
	P99Ms           *int32             `json:"p99_ms"`
	QueueDepth      *int32             `json:"queue_depth"`
	DimCounters     []byte             `json:"dim_counters"`
	GeoipBuildEpoch pgtype.Timestamptz `json:"geoip_build_epoch"`
	IsFinal         bool               `json:"is_final"`
}

// db/query/metrics.sql — sqlc query source (layout: 05-schema.md §10.2).
func (q *Queries) InsertCrawlerMetrics(ctx context.Context, arg InsertCrawlerMetricsParams) error {
	_, err := q.db.Exec(ctx, InsertCrawlerMetrics,
		arg.RunID,
		arg.Worker,
		arg.Processed,
		arg.Succeeded,
		arg.Failed,
		arg.Qps,
		arg.P50Ms,
		arg.P99Ms,
		arg.QueueDepth,
		arg.DimCounters,
		arg.GeoipBuildEpoch,
		arg.IsFinal,
	)
	return err
}

const InsertUnboundStats = `-- name: InsertUnboundStats :exec
INSERT INTO unbound_stats (host, num_queries, cache_hits, cache_miss,
                           rcode_servfail, rcode_nxdomain,
                           recursion_time_avg_ms, requestlist_avg, raw)
VALUES ($1, $2, $3, $4,
        $5, $6,
        $7, $8, $9)
`

type InsertUnboundStatsParams struct {
	Host               string   `json:"host"`
	NumQueries         *int64   `json:"num_queries"`
	CacheHits          *int64   `json:"cache_hits"`
	CacheMiss          *int64   `json:"cache_miss"`
	RcodeServfail      *int64   `json:"rcode_servfail"`
	RcodeNxdomain      *int64   `json:"rcode_nxdomain"`
	RecursionTimeAvgMs *float32 `json:"recursion_time_avg_ms"`
	RequestlistAvg     *float32 `json:"requestlist_avg"`
	Raw                []byte   `json:"raw"`
}

func (q *Queries) InsertUnboundStats(ctx context.Context, arg InsertUnboundStatsParams) error {
	_, err := q.db.Exec(ctx, InsertUnboundStats,
		arg.Host,
		arg.NumQueries,
		arg.CacheHits,
		arg.CacheMiss,
		arg.RcodeServfail,
		arg.RcodeNxdomain,
		arg.RecursionTimeAvgMs,
		arg.RequestlistAvg,
		arg.Raw,
	)
	return err
}

const QueueDepth = `-- name: QueueDepth :one
SELECT count(*) FROM domain
WHERE (NOT disabled OR disabled_reason IN ('dead', 'delisted'))
  AND next_check_at <= now()
  AND (claimed_at IS NULL OR claimed_at < now() - interval '30 minutes')
`

// The queue-depth probe (04 §15.1): O(due-set) via idx_domain_due, sampled
// at most once per checkpoint.
func (q *Queries) QueueDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, QueueDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const TickSummaryCounts = `-- name: TickSummaryCounts :one
SELECT
  (SELECT COALESCE(sum(processed), 0)::bigint FROM crawler_metrics
     WHERE ts >= now() - interval '24 hours') AS scanned,
  (SELECT count(*) FROM changelog WHERE ts >= now() - interval '24 hours') AS transitions,
  (SELECT count(*) FROM domain WHERE (NOT disabled OR disabled_reason IN ('dead', 'delisted'))
     AND next_check_at <= now()
     AND (claimed_at IS NULL OR claimed_at < now() - interval '30 minutes')) AS queue_depth
`

type TickSummaryCountsRow struct {
	Scanned     int64 `json:"scanned"`
	Transitions int64 `json:"transitions"`
	QueueDepth  int64 `json:"queue_depth"`
}

// The tick step-7 ops digest (04 §9). scanned sums the checkpoint deltas
// (crawler_metrics.processed resets every checkpoint) instead of counting
// raw scan rows — the scan hypertable has no ts-leading index and a 24h
// count(*) would seq-scan the newest chunk.
func (q *Queries) TickSummaryCounts(ctx context.Context) (TickSummaryCountsRow, error) {
	row := q.db.QueryRow(ctx, TickSummaryCounts)
	var i TickSummaryCountsRow
	err := row.Scan(&i.Scanned, &i.Transitions, &i.QueueDepth)
	return i, err
}
