// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type CheckJobStatus string

const (
	CheckJobStatusPending    CheckJobStatus = "pending"
	CheckJobStatusProcessing CheckJobStatus = "processing"
	CheckJobStatusDone       CheckJobStatus = "done"
	CheckJobStatusFailed     CheckJobStatus = "failed"
)

func (e *CheckJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckJobStatus(s)
	case string:
		*e = CheckJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckJobStatus: %T", src)
	}
	return nil
}

type NullCheckJobStatus struct {
	CheckJobStatus CheckJobStatus `json:"check_job_status"`
	Valid          bool           `json:"valid"` // Valid is true if CheckJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CheckJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckJobStatus), nil
}

type Classification string

const (
	ClassificationUnknown  Classification = "unknown"
	ClassificationInactive Classification = "inactive"
	ClassificationSinner   Classification = "sinner"
	ClassificationPartial  Classification = "partial"
	ClassificationHero     Classification = "hero"
)

func (e *Classification) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Classification(s)
	case string:
		*e = Classification(s)
	default:
		return fmt.Errorf("unsupported scan type for Classification: %T", src)
	}
	return nil
}

type NullClassification struct {
	Classification Classification `json:"classification"`
	Valid          bool           `json:"valid"` // Valid is true if Classification is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClassification) Scan(value interface{}) error {
	if value == nil {
		ns.Classification, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Classification.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClassification) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Classification), nil
}

type CreatedBy string

const (
	CreatedByTranco     CreatedBy = "tranco"
	CreatedByCampaign   CreatedBy = "campaign"
	CreatedByParentLink CreatedBy = "parent_link"
	CreatedByLiveCheck  CreatedBy = "live_check"
	CreatedByCurated    CreatedBy = "curated"
)

func (e *CreatedBy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreatedBy(s)
	case string:
		*e = CreatedBy(s)
	default:
		return fmt.Errorf("unsupported scan type for CreatedBy: %T", src)
	}
	return nil
}

type NullCreatedBy struct {
	CreatedBy CreatedBy `json:"created_by"`
	Valid     bool      `json:"valid"` // Valid is true if CreatedBy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreatedBy) Scan(value interface{}) error {
	if value == nil {
		ns.CreatedBy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreatedBy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreatedBy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreatedBy), nil
}

type DisabledReason string

const (
	DisabledReasonDead     DisabledReason = "dead"
	DisabledReasonService  DisabledReason = "service"
	DisabledReasonManual   DisabledReason = "manual"
	DisabledReasonDelisted DisabledReason = "delisted"
)

func (e *DisabledReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DisabledReason(s)
	case string:
		*e = DisabledReason(s)
	default:
		return fmt.Errorf("unsupported scan type for DisabledReason: %T", src)
	}
	return nil
}

type NullDisabledReason struct {
	DisabledReason DisabledReason `json:"disabled_reason"`
	Valid          bool           `json:"valid"` // Valid is true if DisabledReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDisabledReason) Scan(value interface{}) error {
	if value == nil {
		ns.DisabledReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DisabledReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDisabledReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DisabledReason), nil
}

type DomainKind string

const (
	DomainKindApex      DomainKind = "apex"
	DomainKindSubdomain DomainKind = "subdomain"
)

func (e *DomainKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DomainKind(s)
	case string:
		*e = DomainKind(s)
	default:
		return fmt.Errorf("unsupported scan type for DomainKind: %T", src)
	}
	return nil
}

type NullDomainKind struct {
	DomainKind DomainKind `json:"domain_kind"`
	Valid      bool       `json:"valid"` // Valid is true if DomainKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDomainKind) Scan(value interface{}) error {
	if value == nil {
		ns.DomainKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DomainKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDomainKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DomainKind), nil
}

type Ipv6Status string

const (
	Ipv6StatusSupported     Ipv6Status = "supported"
	Ipv6StatusUnsupported   Ipv6Status = "unsupported"
	Ipv6StatusNoRecord      Ipv6Status = "no_record"
	Ipv6StatusNotApplicable Ipv6Status = "not_applicable"
)

func (e *Ipv6Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Ipv6Status(s)
	case string:
		*e = Ipv6Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Ipv6Status: %T", src)
	}
	return nil
}

type NullIpv6Status struct {
	Ipv6Status Ipv6Status `json:"ipv6_status"`
	Valid      bool       `json:"valid"` // Valid is true if Ipv6Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIpv6Status) Scan(value interface{}) error {
	if value == nil {
		ns.Ipv6Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Ipv6Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIpv6Status) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Ipv6Status), nil
}

type Observation string

const (
	ObservationSupported     Observation = "supported"
	ObservationPartial       Observation = "partial"
	ObservationUnsupported   Observation = "unsupported"
	ObservationNoRecord      Observation = "no_record"
	ObservationNotApplicable Observation = "not_applicable"
	ObservationError         Observation = "error"
	ObservationInconsistent  Observation = "inconsistent"
)

func (e *Observation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Observation(s)
	case string:
		*e = Observation(s)
	default:
		return fmt.Errorf("unsupported scan type for Observation: %T", src)
	}
	return nil
}

type NullObservation struct {
	Observation Observation `json:"observation"`
	Valid       bool        `json:"valid"` // Valid is true if Observation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullObservation) Scan(value interface{}) error {
	if value == nil {
		ns.Observation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Observation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullObservation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Observation), nil
}

type ResourceSource string

const (
	ResourceSourceDiscovered ResourceSource = "discovered"
	ResourceSourceManual     ResourceSource = "manual"
)

func (e *ResourceSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceSource(s)
	case string:
		*e = ResourceSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceSource: %T", src)
	}
	return nil
}

type NullResourceSource struct {
	ResourceSource ResourceSource `json:"resource_source"`
	Valid          bool           `json:"valid"` // Valid is true if ResourceSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceSource) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceSource), nil
}

type Asn struct {
	ID         int32  `json:"id"`
	Number     int64  `json:"number"`
	Name       string `json:"name"`
	CountTotal int32  `json:"count_total"`
	CountV6    int32  `json:"count_v6"`
}

type Campaign struct {
	ID          int32              `json:"id"`
	Uuid        pgtype.UUID        `json:"uuid"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	SourceFile  *string            `json:"source_file"`
	Tags        []string           `json:"tags"`
	Disabled    bool               `json:"disabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CampaignDomain struct {
	CampaignID int32              `json:"campaign_id"`
	DomainID   int64              `json:"domain_id"`
	AddedAt    pgtype.Timestamptz `json:"added_at"`
}

type Changelog struct {
	DomainID int64              `json:"domain_id"`
	Ts       pgtype.Timestamptz `json:"ts"`
	Field    string             `json:"field"`
	OldValue Ipv6Status         `json:"old_value"`
	NewValue Ipv6Status         `json:"new_value"`
}

type CheckJob struct {
	ID          int64              `json:"id"`
	Host        string             `json:"host"`
	RequesterIp netip.Addr         `json:"requester_ip"`
	Status      CheckJobStatus     `json:"status"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	Result      []byte             `json:"result"`
	Error       *string            `json:"error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type Country struct {
	ID      int32          `json:"id"`
	Code    string         `json:"code"`
	Name    string         `json:"name"`
	Tld     *string        `json:"tld"`
	Sites   int32          `json:"sites"`
	V6sites int32          `json:"v6sites"`
	Percent pgtype.Numeric `json:"percent"`
}

type CrawlerMetric struct {
	Ts              pgtype.Timestamptz `json:"ts"`
	RunID           pgtype.UUID        `json:"run_id"`
	Worker          string             `json:"worker"`
	Processed       *int32             `json:"processed"`
	Succeeded       *int32             `json:"succeeded"`
	Failed          *int32             `json:"failed"`
	Qps             *float32           `json:"qps"`
	P50Ms           *int32             `json:"p50_ms"`
	P99Ms           *int32             `json:"p99_ms"`
	QueueDepth      *int32             `json:"queue_depth"`
	DimCounters     []byte             `json:"dim_counters"`
	GeoipBuildEpoch pgtype.Timestamptz `json:"geoip_build_epoch"`
	IsFinal         bool               `json:"is_final"`
}

type CuratedSubdomain struct {
	DomainID int64              `json:"domain_id"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
}

type DnsProvider struct {
	ID         int64    `json:"id"`
	Name       string   `json:"name"`
	NsSuffixes []string `json:"ns_suffixes"`
	CountTotal int32    `json:"count_total"`
	CountV6    int32    `json:"count_v6"`
}

type Domain struct {
	ID                    int64              `json:"id"`
	Host                  string             `json:"host"`
	Kind                  DomainKind         `json:"kind"`
	ParentID              *int64             `json:"parent_id"`
	Rank                  *int32             `json:"rank"`
	CreatedBy             CreatedBy          `json:"created_by"`
	BaseStatus            *Ipv6Status        `json:"base_status"`
	BaseObserved          *Observation       `json:"base_observed"`
	BasePending           *Ipv6Status        `json:"base_pending"`
	BasePendingCount      int16              `json:"base_pending_count"`
	BaseSince             pgtype.Timestamptz `json:"base_since"`
	WwwStatus             *Ipv6Status        `json:"www_status"`
	WwwObserved           *Observation       `json:"www_observed"`
	WwwPending            *Ipv6Status        `json:"www_pending"`
	WwwPendingCount       int16              `json:"www_pending_count"`
	WwwSince              pgtype.Timestamptz `json:"www_since"`
	NsStatus              *Ipv6Status        `json:"ns_status"`
	NsObserved            *Observation       `json:"ns_observed"`
	NsPending             *Ipv6Status        `json:"ns_pending"`
	NsPendingCount        int16              `json:"ns_pending_count"`
	NsSince               pgtype.Timestamptz `json:"ns_since"`
	MxStatus              *Ipv6Status        `json:"mx_status"`
	MxObserved            *Observation       `json:"mx_observed"`
	MxPending             *Ipv6Status        `json:"mx_pending"`
	MxPendingCount        int16              `json:"mx_pending_count"`
	MxSince               pgtype.Timestamptz `json:"mx_since"`
	ConnStatus            *Ipv6Status        `json:"conn_status"`
	ConnObserved          *Observation       `json:"conn_observed"`
	ConnPending           *Ipv6Status        `json:"conn_pending"`
	ConnPendingCount      int16              `json:"conn_pending_count"`
	ConnSince             pgtype.Timestamptz `json:"conn_since"`
	ResourcesStatus       *Ipv6Status        `json:"resources_status"`
	ResourcesObserved     *Observation       `json:"resources_observed"`
	ResourcesPending      *Ipv6Status        `json:"resources_pending"`
	ResourcesPendingCount int16              `json:"resources_pending_count"`
	ResourcesSince        pgtype.Timestamptz `json:"resources_since"`
	DnssecObserved        *Observation       `json:"dnssec_observed"`
	PtrObserved           *Observation       `json:"ptr_observed"`
	SmtpObserved          *Observation       `json:"smtp_observed"`
	ParityObserved        *Observation       `json:"parity_observed"`
	LatencyV4Ms           *int32             `json:"latency_v4_ms"`
	LatencyV6Ms           *int32             `json:"latency_v6_ms"`
	Classification        Classification     `json:"classification"`
	ClassFlags            []string           `json:"class_flags"`
	Saint                 bool               `json:"saint"`
	AsnID                 int32              `json:"asn_id"`
	CountryID             int32              `json:"country_id"`
	Tld                   *string            `json:"tld"`
	DnsProviderID         *int64             `json:"dns_provider_id"`
	HostingProvider       *string            `json:"hosting_provider"`
	Disabled              bool               `json:"disabled"`
	DisabledReason        *DisabledReason    `json:"disabled_reason"`
	DisabledAt            pgtype.Timestamptz `json:"disabled_at"`
	DeadStreak            int16              `json:"dead_streak"`
	OrphanedAt            pgtype.Timestamptz `json:"orphaned_at"`
	LastRequestedAt       pgtype.Timestamptz `json:"last_requested_at"`
	NextCheckAt           pgtype.Timestamptz `json:"next_check_at"`
	ClaimedAt             pgtype.Timestamptz `json:"claimed_at"`
	LastCheckedAt         pgtype.Timestamptz `json:"last_checked_at"`
	LastCountedAt         pgtype.Timestamptz `json:"last_counted_at"`
	ErrorStreak           int16              `json:"error_streak"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type DomainResource struct {
	DomainID       int64              `json:"domain_id"`
	ResourceHostID int64              `json:"resource_host_id"`
	Source         ResourceSource     `json:"source"`
	Required       bool               `json:"required"`
	FirstSeen      pgtype.Timestamptz `json:"first_seen"`
	LastSeen       pgtype.Timestamptz `json:"last_seen"`
}

type ResourceHost struct {
	ID               int64              `json:"id"`
	Host             string             `json:"host"`
	AaaaStatus       *Ipv6Status        `json:"aaaa_status"`
	AaaaPending      *Ipv6Status        `json:"aaaa_pending"`
	AaaaPendingCount int16              `json:"aaaa_pending_count"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
	NextCheckAt      pgtype.Timestamptz `json:"next_check_at"`
	DependentCount   int32              `json:"dependent_count"`
}

type Scan struct {
	DomainID       int64              `json:"domain_id"`
	Ts             pgtype.Timestamptz `json:"ts"`
	Base           Observation        `json:"base"`
	Www            Observation        `json:"www"`
	Ns             Observation        `json:"ns"`
	Mx             Observation        `json:"mx"`
	Conn           Observation        `json:"conn"`
	Resources      Observation        `json:"resources"`
	Dnssec         *Observation       `json:"dnssec"`
	Ptr            *Observation       `json:"ptr"`
	Smtp           *Observation       `json:"smtp"`
	Parity         *Observation       `json:"parity"`
	LatencyV4Ms    *int32             `json:"latency_v4_ms"`
	LatencyV6Ms    *int32             `json:"latency_v6_ms"`
	Classification Classification     `json:"classification"`
	CountryID      *int32             `json:"country_id"`
	AsnID          *int32             `json:"asn_id"`
}

type ScanDailyAdoption struct {
	Day       interface{} `json:"day"`
	CountryID *int32      `json:"country_id"`
	Scanned   int64       `json:"scanned"`
	BaseV6    int64       `json:"base_v6"`
	ConnV6    int64       `json:"conn_v6"`
	Heroes    int64       `json:"heroes"`
	Sinners   int64       `json:"sinners"`
}

type ScanDetail struct {
	DomainID   int64              `json:"domain_id"`
	Ts         pgtype.Timestamptz `json:"ts"`
	Details    []byte             `json:"details"`
	DurationMs *int32             `json:"duration_ms"`
}

type ServiceCandidate struct {
	DomainID   int64              `json:"domain_id"`
	Reasons    []string           `json:"reasons"`
	DetectedAt pgtype.Timestamptz `json:"detected_at"`
	Dismissed  bool               `json:"dismissed"`
}

type StatsAsnDaily struct {
	Day       pgtype.Timestamptz `json:"day"`
	AsnID     int32              `json:"asn_id"`
	Domains   *int32             `json:"domains"`
	V6Domains *int32             `json:"v6_domains"`
	Sinners   *int32             `json:"sinners"`
	Heroes    *int32             `json:"heroes"`
}

type StatsCampaignDaily struct {
	Day           pgtype.Date `json:"day"`
	CampaignID    int32       `json:"campaign_id"`
	Domains       *int32      `json:"domains"`
	V6Ready       *int32      `json:"v6_ready"`
	Sinners       *int32      `json:"sinners"`
	Partial       *int32      `json:"partial"`
	Heroes        *int32      `json:"heroes"`
	BaseSupported *int32      `json:"base_supported"`
	WwwSupported  *int32      `json:"www_supported"`
	NsSupported   *int32      `json:"ns_supported"`
	MxSupported   *int32      `json:"mx_supported"`
	ConnSupported *int32      `json:"conn_supported"`
}

type StatsCountryDaily struct {
	Day           pgtype.Date `json:"day"`
	CountryID     int32       `json:"country_id"`
	Domains       *int32      `json:"domains"`
	Sinners       *int32      `json:"sinners"`
	Partial       *int32      `json:"partial"`
	Heroes        *int32      `json:"heroes"`
	BaseSupported *int32      `json:"base_supported"`
	ConnSupported *int32      `json:"conn_supported"`
}

type StatsGlobalDaily struct {
	Day                pgtype.Date        `json:"day"`
	Domains            *int32             `json:"domains"`
	Sinners            *int32             `json:"sinners"`
	Partial            *int32             `json:"partial"`
	Heroes             *int32             `json:"heroes"`
	Saints             *int32             `json:"saints"`
	Inactive           *int32             `json:"inactive"`
	Unknown            *int32             `json:"unknown"`
	Disabled           *int32             `json:"disabled"`
	BaseSupported      *int32             `json:"base_supported"`
	WwwSupported       *int32             `json:"www_supported"`
	NsSupported        *int32             `json:"ns_supported"`
	MxSupported        *int32             `json:"mx_supported"`
	ConnSupported      *int32             `json:"conn_supported"`
	ResourcesSupported *int32             `json:"resources_supported"`
	TopHeroes          *int32             `json:"top_heroes"`
	TopNameserver      *int32             `json:"top_nameserver"`
	GeneratedAt        pgtype.Timestamptz `json:"generated_at"`
	TrackedTotal       *int32             `json:"tracked_total"`
	PtrSupported       *int32             `json:"ptr_supported"`
	PtrGraded          *int32             `json:"ptr_graded"`
	SmtpSupported      *int32             `json:"smtp_supported"`
	SmtpGraded         *int32             `json:"smtp_graded"`
}

type TopShame struct {
	DomainID int64              `json:"domain_id"`
	Reason   *string            `json:"reason"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
}

type TrancoImport struct {
	ID             int32              `json:"id"`
	ListID         string             `json:"list_id"`
	ListDate       pgtype.Date        `json:"list_date"`
	LineCount      *int32             `json:"line_count"`
	ImportedCount  *int32             `json:"imported_count"`
	Delisted       *int32             `json:"delisted"`
	RejectedCount  *int32             `json:"rejected_count"`
	DuplicateCount *int32             `json:"duplicate_count"`
	Aborted        bool               `json:"aborted"`
	Note           *string            `json:"note"`
	ImportedAt     pgtype.Timestamptz `json:"imported_at"`
}

type UnboundStat struct {
	Ts                 pgtype.Timestamptz `json:"ts"`
	Host               string             `json:"host"`
	NumQueries         *int64             `json:"num_queries"`
	CacheHits          *int64             `json:"cache_hits"`
	CacheMiss          *int64             `json:"cache_miss"`
	RcodeServfail      *int64             `json:"rcode_servfail"`
	RcodeNxdomain      *int64             `json:"rcode_nxdomain"`
	RecursionTimeAvgMs *float32           `json:"recursion_time_avg_ms"`
	RequestlistAvg     *float32           `json:"requestlist_avg"`
	Raw                []byte             `json:"raw"`
}
