// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package db

import (
	"context"
)

const DomainStampDNSProvider = `-- name: DomainStampDNSProvider :exec
UPDATE domain SET dns_provider_id = $2 WHERE id = $1
`

type DomainStampDNSProviderParams struct {
	ID            int64  `json:"id"`
	DnsProviderID *int64 `json:"dns_provider_id"`
}

// The attribution stamp: touches ONLY the pivot column, never the
// commit/trust machine's columns (06-ingest.md §6.10).
func (q *Queries) DomainStampDNSProvider(ctx context.Context, arg DomainStampDNSProviderParams) error {
	_, err := q.db.Exec(ctx, DomainStampDNSProvider, arg.ID, arg.DnsProviderID)
	return err
}

const DomainStampHostingProvider = `-- name: DomainStampHostingProvider :exec
UPDATE domain SET hosting_provider = $2 WHERE id = $1
`

type DomainStampHostingProviderParams struct {
	ID              int64   `json:"id"`
	HostingProvider *string `json:"hosting_provider"`
}

func (q *Queries) DomainStampHostingProvider(ctx context.Context, arg DomainStampHostingProviderParams) error {
	_, err := q.db.Exec(ctx, DomainStampHostingProvider, arg.ID, arg.HostingProvider)
	return err
}

const ProviderAppendSuffixes = `-- name: ProviderAppendSuffixes :exec
UPDATE dns_provider
SET ns_suffixes = (SELECT array_agg(DISTINCT s ORDER BY s)
                   FROM unnest(ns_suffixes || $2::text[]) AS s)
WHERE id = $1
`

type ProviderAppendSuffixesParams struct {
	ID      int64    `json:"id"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) ProviderAppendSuffixes(ctx context.Context, arg ProviderAppendSuffixesParams) error {
	_, err := q.db.Exec(ctx, ProviderAppendSuffixes, arg.ID, arg.Column2)
	return err
}

const ProviderByName = `-- name: ProviderByName :one
SELECT id, name, ns_suffixes FROM dns_provider WHERE name = $1
`

type ProviderByNameRow struct {
	ID         int64    `json:"id"`
	Name       string   `json:"name"`
	NsSuffixes []string `json:"ns_suffixes"`
}

func (q *Queries) ProviderByName(ctx context.Context, name string) (ProviderByNameRow, error) {
	row := q.db.QueryRow(ctx, ProviderByName, name)
	var i ProviderByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.NsSuffixes)
	return i, err
}

const ProviderClearDomains = `-- name: ProviderClearDomains :execrows
UPDATE domain SET dns_provider_id = NULL
WHERE dns_provider_id = (SELECT id FROM dns_provider WHERE name = $1)
`

// provider remove clears referencing domains first (FK); they re-stamp on
// their next scan commit (06-ingest.md §6.11 self-healing).
func (q *Queries) ProviderClearDomains(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, ProviderClearDomains, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ProviderDelete = `-- name: ProviderDelete :execrows
DELETE FROM dns_provider WHERE name = $1
`

func (q *Queries) ProviderDelete(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, ProviderDelete, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ProviderDetail = `-- name: ProviderDetail :one
SELECT id, name, count_total, count_v6 FROM dns_provider WHERE id = $1
`

type ProviderDetailRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	CountTotal int32  `json:"count_total"`
	CountV6    int32  `json:"count_v6"`
}

// The API DNS-provider league table (07 §4.6): exact stored counters,
// count_v4 synthesized server-side.
func (q *Queries) ProviderDetail(ctx context.Context, id int64) (ProviderDetailRow, error) {
	row := q.db.QueryRow(ctx, ProviderDetail, id)
	var i ProviderDetailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CountTotal,
		&i.CountV6,
	)
	return i, err
}

const ProviderDomainCount = `-- name: ProviderDomainCount :one
SELECT count(*) FROM domain WHERE dns_provider_id = $1
`

func (q *Queries) ProviderDomainCount(ctx context.Context, dnsProviderID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, ProviderDomainCount, dnsProviderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ProviderInsert = `-- name: ProviderInsert :one
INSERT INTO dns_provider (name, ns_suffixes) VALUES ($1, $2) RETURNING id
`

type ProviderInsertParams struct {
	Name       string   `json:"name"`
	NsSuffixes []string `json:"ns_suffixes"`
}

func (q *Queries) ProviderInsert(ctx context.Context, arg ProviderInsertParams) (int64, error) {
	row := q.db.QueryRow(ctx, ProviderInsert, arg.Name, arg.NsSuffixes)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ProviderLeaderboard = `-- name: ProviderLeaderboard :many
SELECT id, name, count_total, count_v6 FROM dns_provider ORDER BY count_total DESC, id
`

type ProviderLeaderboardRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	CountTotal int32  `json:"count_total"`
	CountV6    int32  `json:"count_v6"`
}

func (q *Queries) ProviderLeaderboard(ctx context.Context) ([]ProviderLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, ProviderLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderLeaderboardRow{}
	for rows.Next() {
		var i ProviderLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CountTotal,
			&i.CountV6,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ProviderList = `-- name: ProviderList :many

SELECT id, name, ns_suffixes, count_total, count_v6 FROM dns_provider ORDER BY name
`

// db/query/provider.sql — dns_provider reference data + attribution stamp
// (05-schema.md — dns_provider; 06-ingest.md §6.10/§6.11).
func (q *Queries) ProviderList(ctx context.Context) ([]DnsProvider, error) {
	rows, err := q.db.Query(ctx, ProviderList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsProvider{}
	for rows.Next() {
		var i DnsProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NsSuffixes,
			&i.CountTotal,
			&i.CountV6,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
