// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// The API network leaderboard (07 §4.6): keyset over (count, number) desc;
	// the ILIKE arm serves ?q= substring match.
	ASNByNumber(ctx context.Context, number int64) (ASNByNumberRow, error)
	// ASN auto-registration (06-ingest.md §6.3): pool-side, before the commit
	// transaction (03 §3 A). ON CONFLICT DO NOTHING + re-read; names are never
	// updated on later scans.
	ASNEnsure(ctx context.Context, arg ASNEnsureParams) (int32, error)
	ASNIDByNumber(ctx context.Context, number int64) (int32, error)
	// db/query/asn.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Sentinel lookup: binaries resolve the sentinel ASN once at startup by
	// lookup, never by literal id (05-schema.md §5).
	ASNSentinelID(ctx context.Context) (int32, error)
	// The badge read (07 §5.2): read-only, zero side effects, any kind/origin.
	BadgeDomain(ctx context.Context, host string) (BadgeDomainRow, error)
	CampaignAddMember(ctx context.Context, arg CampaignAddMemberParams) (int64, error)
	CampaignAdoption(ctx context.Context, campaignID int32) (CampaignAdoptionRow, error)
	// db/query/campaign.sql — sqlc query source (layout: 05-schema.md §10.2).
	CampaignByUUID(ctx context.Context, uuid pgtype.UUID) (CampaignByUUIDRow, error)
	CampaignDisableAbsent(ctx context.Context, dollar_1 []pgtype.UUID) ([]CampaignDisableAbsentRow, error)
	CampaignHasMember(ctx context.Context, arg CampaignHasMemberParams) (bool, error)
	CampaignInsert(ctx context.Context, arg CampaignInsertParams) (int32, error)
	CampaignMembers(ctx context.Context, campaignID int32) ([]int64, error)
	CampaignPublicDetail(ctx context.Context, uuid pgtype.UUID) (CampaignPublicDetailRow, error)
	// The public campaign surface (07 §4.7): exact member counts (bounded sets),
	// ?tag= via the GIN-indexed tags array. Each row carries the same adoption
	// pair as the detail via a lateral read of the latest stats_campaign_daily
	// row (the set is tens of rows, so the per-row join is trivially cheap).
	CampaignPublicList(ctx context.Context, tag string) ([]CampaignPublicListRow, error)
	CampaignRemoveMembersNotIn(ctx context.Context, arg CampaignRemoveMembersNotInParams) (int64, error)
	CampaignUUIDBySourceFile(ctx context.Context, sourceFile *string) (pgtype.UUID, error)
	CampaignUpdateFromFile(ctx context.Context, arg CampaignUpdateFromFileParams) (int32, error)
	// The ?scope=campaign global feed (07 §4.8): transitions of domains in ANY
	// campaign. Driven from the bounded campaign_domain set via a lateral read
	// of the (domain_id, ts, field) PK — never a sparse probe of the global ts
	// index. Same latest-50 recent-window cap as the other scoped feeds.
	ChangelogAnyCampaign(ctx context.Context) ([]ChangelogAnyCampaignRow, error)
	ChangelogByCampaign(ctx context.Context, campaignID int32) ([]ChangelogByCampaignRow, error)
	// Changelog read surface (07 §4.8). The paginating global + per-domain
	// feeds are builder-built in internal/postgres/changeloglist.go (05-schema
	// §10.2 — one seek builder derives both walk directions); the scoped
	// country/campaign feeds below are capped to the latest-50 recent window
	// (OPEN-15 guardrail) and stay sqlc.
	ChangelogByCountry(ctx context.Context, countryID int32) ([]ChangelogByCountryRow, error)
	ChangelogMaxTS(ctx context.Context) (pgtype.Timestamptz, error)
	// The §4.9 confirmed-trajectory replay: the full transition history of one
	// domain, ascending, reconstructed API-side (never raw scan observations).
	ChangelogReplay(ctx context.Context, domainID int64) ([]ChangelogReplayRow, error)
	CheckJobByID(ctx context.Context, id int64) (CheckJobByIDRow, error)
	// The consumer claim (07 §5.1.5): oldest pending or stale-processing row.
	CheckJobClaim(ctx context.Context, reclaim pgtype.Interval) (CheckJobClaimRow, error)
	CheckJobComplete(ctx context.Context, arg CheckJobCompleteParams) error
	CheckJobDedupe(ctx context.Context, arg CheckJobDedupeParams) (CheckJobDedupeRow, error)
	CheckJobFail(ctx context.Context, arg CheckJobFailParams) error
	// The §5.1 live-check job lifecycle.
	CheckJobInsert(ctx context.Context, arg CheckJobInsertParams) (CheckJobInsertRow, error)
	CheckJobRateGlobal(ctx context.Context) (CheckJobRateGlobalRow, error)
	// Rate limiting (07 §6.3): /64-prefix and global hourly windows; min_created
	// feeds retry_after = ceil(3600 − (now − min(created_at))).
	CheckJobRatePrefix(ctx context.Context, prefix netip.Prefix) (CheckJobRatePrefixRow, error)
	// The reaper: every poller terminates ≤ fail_after.
	CheckJobReap(ctx context.Context, failAfter pgtype.Interval) (int64, error)
	// The claim.order=age variant: aging pressure valve, no sort at all beyond
	// the index order (04 §3).
	ClaimBatchByAge(ctx context.Context, limit int32) ([]ClaimBatchByAgeRow, error)
	// The frontier claim (04-lifecycle-scheduling.md §3). One statement per claim
	// cycle; all rows in a batch share one claimed_at (the lease token L). The
	// eligibility predicate textually matches idx_domain_due (05-schema §1.7).
	ClaimBatchByRank(ctx context.Context, limit int32) ([]ClaimBatchByRankRow, error)
	// db/query/commit.sql — the per-domain commit write unit (03-state-machine.md
	// §12). One pgx.Batch in one pgx.Tx; statement 1 is the lease-fenced UPDATE.
	CommitDomain(ctx context.Context, arg CommitDomainParams) (int64, error)
	// The API country representations (07 §4.5).
	CountryByCode(ctx context.Context, code interface{}) (CountryByCodeRow, error)
	CountryCodeMap(ctx context.Context) ([]CountryCodeMapRow, error)
	CountryIDByCode(ctx context.Context, code interface{}) (int32, error)
	// Insert-time ccTLD attribution probe (06-ingest.md §6.5): '.NO'-form input.
	CountryIDByTLD(ctx context.Context, tld *string) (int32, error)
	CountryLeaderboard(ctx context.Context) ([]CountryLeaderboardRow, error)
	// db/query/country.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Sentinel lookup: binaries resolve the sentinel country once at startup by
	// lookup, never by literal id (05-schema.md §5).
	CountrySentinelID(ctx context.Context) (int32, error)
	// The in-memory country.tld -> id map for insert-time/commit attribution
	// (06-ingest.md §6.5); loaded once per run.
	CountryTLDMap(ctx context.Context) ([]CountryTLDMapRow, error)
	// db/query/service_candidate.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Tick step 4 — candidate detection, never auto-disable (04 §9).
	DetectServiceCandidatesApex(ctx context.Context) (int64, error)
	DetectServiceCandidatesIndegree(ctx context.Context, indegreeThreshold int32) (int64, error)
	// db/query/domain.sql — sqlc query source (layout: 05-schema.md §10.2).
	DomainByHost(ctx context.Context, host string) (DomainByHostRow, error)
	// The §5.1 live-check domain reads/writes.
	DomainConfirmed(ctx context.Context, host string) (DomainConfirmedRow, error)
	DomainDetailByHost(ctx context.Context, host string) (DomainDetailByHostRow, error)
	// Operator disable/enable (P2.14; glossary: service/manual lifecycle).
	DomainDisable(ctx context.Context, arg DomainDisableParams) (int64, error)
	DomainEnable(ctx context.Context, host string) (int64, error)
	DomainInsertEntity(ctx context.Context, arg DomainInsertEntityParams) (int64, error)
	// The consumer's entity insert (07 §5.1.5 step 2): parent only if it
	// ALREADY exists — live checks never auto-ensure parents.
	DomainInsertLiveCheck(ctx context.Context, arg DomainInsertLiveCheckParams) (int64, error)
	// Lifecycle re-entry (07 §5.1.6): every POST /check on an existing host.
	DomainLiveCheckReentry(ctx context.Context, host string) error
	DomainMembershipReEntry(ctx context.Context, id int64) error
	// The worker's pre-commit roll-up input (02 §6): required links only.
	DomainRequiredLinks(ctx context.Context, domainID int64) ([]*Ipv6Status, error)
	// Resource-dependency reads (07 §4.11). Forward list is bounded small
	// (exact count, no cursor); the reverse dependents list is served by the
	// domainlist builder.
	DomainResourceList(ctx context.Context, domainID int64) ([]DomainResourceListRow, error)
	// The attribution stamp: touches ONLY the pivot column, never the
	// commit/trust machine's columns (06-ingest.md §6.10).
	DomainStampDNSProvider(ctx context.Context, arg DomainStampDNSProviderParams) error
	DomainStampHostingProvider(ctx context.Context, arg DomainStampHostingProviderParams) error
	EnsureResourceHost(ctx context.Context, rhost string) error
	// The nightly dataset export (07 §5.3): one parameterized read covers the
	// three tiers — ranked_only for top100k/top1m, max_rank 0 = unbounded.
	ExportRows(ctx context.Context, arg ExportRowsParams) ([]ExportRowsRow, error)
	InsertChangelog(ctx context.Context, arg InsertChangelogParams) error
	// db/query/metrics.sql — sqlc query source (layout: 05-schema.md §10.2).
	InsertCrawlerMetrics(ctx context.Context, arg InsertCrawlerMetricsParams) error
	InsertScan(ctx context.Context, arg InsertScanParams) error
	InsertScanDetail(ctx context.Context, arg InsertScanDetailParams) error
	InsertUnboundStats(ctx context.Context, arg InsertUnboundStatsParams) error
	// db/query/scan.sql — sqlc query source (layout: 05-schema.md §10.2).
	// The detail page's evidence block: the latest scan_detail payload
	// (07 §4.3 ?include=evidence).
	LatestScanDetail(ctx context.Context, domainID int64) ([]byte, error)
	ProviderAppendSuffixes(ctx context.Context, arg ProviderAppendSuffixesParams) error
	ProviderByName(ctx context.Context, name string) (ProviderByNameRow, error)
	// provider remove clears referencing domains first (FK); they re-stamp on
	// their next scan commit (06-ingest.md §6.11 self-healing).
	ProviderClearDomains(ctx context.Context, name string) (int64, error)
	ProviderDelete(ctx context.Context, name string) (int64, error)
	// The API DNS-provider league table (07 §4.6): exact stored counters,
	// count_v4 synthesized server-side.
	ProviderDetail(ctx context.Context, id int64) (ProviderDetailRow, error)
	ProviderDomainCount(ctx context.Context, dnsProviderID *int64) (int64, error)
	ProviderInsert(ctx context.Context, arg ProviderInsertParams) (int64, error)
	ProviderLeaderboard(ctx context.Context) ([]ProviderLeaderboardRow, error)
	// db/query/provider.sql — dns_provider reference data + attribution stamp
	// (05-schema.md — dns_provider; 06-ingest.md §6.10/§6.11).
	ProviderList(ctx context.Context) ([]DnsProvider, error)
	// db/query/check_job.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Tick step 6 — the 30d check_job purge (04 §9; key: live_check.retention).
	PurgeCheckJobs(ctx context.Context, retention pgtype.Interval) (int64, error)
	// The queue-depth probe (04 §15.1): O(due-set) via idx_domain_due, sampled
	// at most once per checkpoint.
	QueueDepth(ctx context.Context) (int64, error)
	RankedDomainCount(ctx context.Context) (int64, error)
	RecomputeASNCounters(ctx context.Context) error
	RecomputeCountryCounters(ctx context.Context) error
	RecomputeProviderCounters(ctx context.Context) error
	// Tick step 3 — ASN + DNS-provider counter recompute (06-ingest.md §10.6).
	ResetASNCounters(ctx context.Context) error
	// Tick step 3 — country counter recompute (06-ingest.md §10.6): reset, then
	// recompute over the publicly-ranked scope.
	ResetCountryCounters(ctx context.Context) error
	ResetProviderCounters(ctx context.Context) error
	ResourceHostByHost(ctx context.Context, host string) (ResourceHostByHostRow, error)
	ResourceHostIDByHost(ctx context.Context, host string) (int64, error)
	// The live-check registry probe (07 §5.1.4): one set-based read.
	ResourceHostStatuses(ctx context.Context, hosts []string) ([]ResourceHostStatusesRow, error)
	ResourceManualRemove(ctx context.Context, arg ResourceManualRemoveParams) (int64, error)
	// The §5.5 manual verbs. The (xmax = 0) probe distinguishes a genuine
	// insert (bump dependent_count) from a conflict update (don't).
	ResourceManualUpsert(ctx context.Context, arg ResourceManualUpsertParams) error
	// The sweep claim (06 §5.2): the schedule bump IS the crash lease.
	ResourceSweepClaim(ctx context.Context, batch int32) ([]ResourceSweepClaimRow, error)
	// The sweep host commit (06 §5.4): one single-row write per definitive
	// outcome.
	ResourceSweepCommit(ctx context.Context, arg ResourceSweepCommitParams) error
	// The §4.9 latency overlay: last scan measurement per day — the only value
	// history takes from the scan hypertable.
	ScanLatencyDaily(ctx context.Context, arg ScanLatencyDailyParams) ([]ScanLatencyDailyRow, error)
	// Operator triage (P2.14; 04 — service/manual lifecycle).
	ServiceCandidateList(ctx context.Context) ([]ServiceCandidateListRow, error)
	ServiceCandidateResolve(ctx context.Context, host string) (int64, error)
	// db/query/shame.sql — sqlc query source (layout: 05-schema.md §10.2).
	// v6ctl shame — the single top_shame write path (06-ingest.md §7).
	ShameEligibleDomain(ctx context.Context, host string) (ShameEligibleDomainRow, error)
	ShameList(ctx context.Context) ([]ShameListRow, error)
	ShameRemove(ctx context.Context, host string) (int64, error)
	ShameUpsert(ctx context.Context, arg ShameUpsertParams) error
	SnapshotASNDaily(ctx context.Context) error
	SnapshotCampaignDaily(ctx context.Context) error
	SnapshotCountryDaily(ctx context.Context) error
	// db/query/stats.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Tick step 2 — the four confirmed-state snapshot upserts (06-ingest.md §10).
	SnapshotGlobalDaily(ctx context.Context) error
	StatsASNRange(ctx context.Context, arg StatsASNRangeParams) ([]StatsASNRangeRow, error)
	StatsCampaignRange(ctx context.Context, arg StatsCampaignRangeParams) ([]StatsCampaignRangeRow, error)
	StatsCountryRange(ctx context.Context, arg StatsCountryRangeParams) ([]StatsCountryRangeRow, error)
	// The envelope meta source (07-api.md §2.4): generation = YYYYMMDD of
	// max(stats_global_daily.day); as_of = its generated_at, falling back to
	// day at 00:00:00Z when NULL (the day-0 seed row).
	StatsGeneration(ctx context.Context) (StatsGenerationRow, error)
	// The §4.10 time-series reads: bounded windows (≤366 rows/yr), ascending;
	// weekly sampling happens API-side over the fetched window.
	StatsGlobalRange(ctx context.Context, arg StatsGlobalRangeParams) ([]StatsGlobalRangeRow, error)
	SubdomainExactCount(ctx context.Context, parentID *int64) (int64, error)
	// The daily lifecycle sweep S1–S5 (04-lifecycle-scheduling.md §8): one
	// transaction, set-based; the linkage predicate is spelled identically in
	// every statement. @live_check_linkage / @delist_grace / @slow_lane_every.
	SweepClearOrphans(ctx context.Context, liveCheckLinkage pgtype.Interval) (int64, error)
	SweepDelistExpired(ctx context.Context, arg SweepDelistExpiredParams) (int64, error)
	SweepDelistLiveCheck(ctx context.Context, arg SweepDelistLiveCheckParams) (int64, error)
	SweepReenableDelisted(ctx context.Context, liveCheckLinkage pgtype.Interval) (int64, error)
	SweepStampOrphans(ctx context.Context, liveCheckLinkage pgtype.Interval) (int64, error)
	// The tick step-7 ops digest (04 §9).
	TickSummaryCounts(ctx context.Context) (TickSummaryCountsRow, error)
	TrancoInsertAborted(ctx context.Context, arg TrancoInsertAbortedParams) error
	TrancoInsertProvenance(ctx context.Context, arg TrancoInsertProvenanceParams) (int64, error)
	TrancoLastSuccessAt(ctx context.Context) (pgtype.Timestamptz, error)
	// db/query/tranco.sql — sqlc query source (layout: 05-schema.md §10.2).
	TrancoLatestSuccessListID(ctx context.Context) (string, error)
	TrancoListWasAborted(ctx context.Context, listID string) (bool, error)
	TrancoRecentImports(ctx context.Context) ([]TrancoImport, error)
}

var _ Querier = (*Queries)(nil)
