// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// db/query/asn.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Sentinel lookup: binaries resolve the sentinel ASN once at startup by
	// lookup, never by literal id (05-schema.md §5).
	ASNSentinelID(ctx context.Context) (int32, error)
	CampaignAddMember(ctx context.Context, arg CampaignAddMemberParams) (int64, error)
	// db/query/campaign.sql — sqlc query source (layout: 05-schema.md §10.2).
	CampaignByUUID(ctx context.Context, uuid pgtype.UUID) (CampaignByUUIDRow, error)
	CampaignDisableAbsent(ctx context.Context, dollar_1 []pgtype.UUID) ([]CampaignDisableAbsentRow, error)
	CampaignInsert(ctx context.Context, arg CampaignInsertParams) (int32, error)
	CampaignMembers(ctx context.Context, campaignID int32) ([]int64, error)
	CampaignRemoveMembersNotIn(ctx context.Context, arg CampaignRemoveMembersNotInParams) (int64, error)
	CampaignUUIDBySourceFile(ctx context.Context, sourceFile *string) (pgtype.UUID, error)
	CampaignUpdateFromFile(ctx context.Context, arg CampaignUpdateFromFileParams) (int32, error)
	// The claim.order=age variant: aging pressure valve, no sort at all beyond
	// the index order (04 §3).
	ClaimBatchByAge(ctx context.Context, limit int32) ([]ClaimBatchByAgeRow, error)
	// The frontier claim (04-lifecycle-scheduling.md §3). One statement per claim
	// cycle; all rows in a batch share one claimed_at (the lease token L). The
	// eligibility predicate textually matches idx_domain_due (05-schema §1.7).
	ClaimBatchByRank(ctx context.Context, limit int32) ([]ClaimBatchByRankRow, error)
	// db/query/commit.sql — the per-domain commit write unit (03-state-machine.md
	// §12). One pgx.Batch in one pgx.Tx; statement 1 is the lease-fenced UPDATE.
	CommitDomain(ctx context.Context, arg CommitDomainParams) (int64, error)
	CountryCodeMap(ctx context.Context) ([]CountryCodeMapRow, error)
	// Insert-time ccTLD attribution probe (06-ingest.md §6.5): '.NO'-form input.
	CountryIDByTLD(ctx context.Context, tld *string) (int32, error)
	// db/query/country.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Sentinel lookup: binaries resolve the sentinel country once at startup by
	// lookup, never by literal id (05-schema.md §5).
	CountrySentinelID(ctx context.Context) (int32, error)
	// The in-memory country.tld -> id map for insert-time/commit attribution
	// (06-ingest.md §6.5); loaded once per run.
	CountryTLDMap(ctx context.Context) ([]CountryTLDMapRow, error)
	// db/query/service_candidate.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Tick step 4 — candidate detection, never auto-disable (04 §9).
	DetectServiceCandidatesApex(ctx context.Context) (int64, error)
	DetectServiceCandidatesIndegree(ctx context.Context, indegreeThreshold int32) (int64, error)
	// db/query/domain.sql — sqlc query source (layout: 05-schema.md §10.2).
	DomainByHost(ctx context.Context, host string) (DomainByHostRow, error)
	// Operator disable/enable (P2.14; glossary: service/manual lifecycle).
	DomainDisable(ctx context.Context, arg DomainDisableParams) (int64, error)
	DomainEnable(ctx context.Context, host string) (int64, error)
	DomainInsertEntity(ctx context.Context, arg DomainInsertEntityParams) (int64, error)
	DomainMembershipReEntry(ctx context.Context, id int64) error
	// The attribution stamp: touches ONLY the pivot column, never the
	// commit/trust machine's columns (06-ingest.md §6.10).
	DomainStampDNSProvider(ctx context.Context, arg DomainStampDNSProviderParams) error
	DomainStampHostingProvider(ctx context.Context, arg DomainStampHostingProviderParams) error
	EnsureResourceHost(ctx context.Context, rhost string) error
	InsertChangelog(ctx context.Context, arg InsertChangelogParams) error
	InsertScan(ctx context.Context, arg InsertScanParams) error
	InsertScanDetail(ctx context.Context, arg InsertScanDetailParams) error
	ProviderAppendSuffixes(ctx context.Context, arg ProviderAppendSuffixesParams) error
	ProviderByName(ctx context.Context, name string) (ProviderByNameRow, error)
	// provider remove clears referencing domains first (FK); they re-stamp on
	// their next scan commit (06-ingest.md §6.11 self-healing).
	ProviderClearDomains(ctx context.Context, name string) (int64, error)
	ProviderDelete(ctx context.Context, name string) (int64, error)
	ProviderDomainCount(ctx context.Context, dnsProviderID *int64) (int64, error)
	ProviderInsert(ctx context.Context, arg ProviderInsertParams) (int64, error)
	// db/query/provider.sql — dns_provider reference data + attribution stamp
	// (05-schema.md — dns_provider; 06-ingest.md §6.10/§6.11).
	ProviderList(ctx context.Context) ([]DnsProvider, error)
	// db/query/check_job.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Tick step 6 — the 30d check_job purge (04 §9; key: live_check.retention).
	PurgeCheckJobs(ctx context.Context, retention pgtype.Interval) (int64, error)
	RecomputeASNCounters(ctx context.Context) error
	RecomputeCountryCounters(ctx context.Context) error
	RecomputeProviderCounters(ctx context.Context) error
	// Tick step 3 — ASN + DNS-provider counter recompute (06-ingest.md §10.6).
	ResetASNCounters(ctx context.Context) error
	// Tick step 3 — country counter recompute (06-ingest.md §10.6): reset, then
	// recompute over the publicly-ranked scope.
	ResetCountryCounters(ctx context.Context) error
	ResetProviderCounters(ctx context.Context) error
	// Operator triage (P2.14; 04 — service/manual lifecycle).
	ServiceCandidateList(ctx context.Context) ([]ServiceCandidateListRow, error)
	ServiceCandidateResolve(ctx context.Context, host string) (int64, error)
	SnapshotASNDaily(ctx context.Context) error
	SnapshotCampaignDaily(ctx context.Context) error
	SnapshotCountryDaily(ctx context.Context) error
	// db/query/stats.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Tick step 2 — the four confirmed-state snapshot upserts (06-ingest.md §10).
	SnapshotGlobalDaily(ctx context.Context) error
	// The daily lifecycle sweep S1–S5 (04-lifecycle-scheduling.md §8): one
	// transaction, set-based; the linkage predicate is spelled identically in
	// every statement. @live_check_linkage / @delist_grace / @slow_lane_every.
	SweepClearOrphans(ctx context.Context, liveCheckLinkage pgtype.Interval) (int64, error)
	SweepDelistExpired(ctx context.Context, arg SweepDelistExpiredParams) (int64, error)
	SweepDelistLiveCheck(ctx context.Context, arg SweepDelistLiveCheckParams) (int64, error)
	SweepReenableDelisted(ctx context.Context, liveCheckLinkage pgtype.Interval) (int64, error)
	SweepStampOrphans(ctx context.Context, liveCheckLinkage pgtype.Interval) (int64, error)
	TrancoInsertAborted(ctx context.Context, arg TrancoInsertAbortedParams) error
	TrancoInsertProvenance(ctx context.Context, arg TrancoInsertProvenanceParams) (int64, error)
	TrancoLastSuccessAt(ctx context.Context) (pgtype.Timestamptz, error)
	// db/query/tranco.sql — sqlc query source (layout: 05-schema.md §10.2).
	TrancoLatestSuccessListID(ctx context.Context) (string, error)
	TrancoListWasAborted(ctx context.Context, listID string) (bool, error)
	TrancoRecentImports(ctx context.Context) ([]TrancoImport, error)
}

var _ Querier = (*Queries)(nil)
