// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// db/query/asn.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Sentinel lookup: binaries resolve the sentinel ASN once at startup by
	// lookup, never by literal id (05-schema.md §5).
	ASNSentinelID(ctx context.Context) (int32, error)
	// db/query/country.sql — sqlc query source (layout: 05-schema.md §10.2).
	// Sentinel lookup: binaries resolve the sentinel country once at startup by
	// lookup, never by literal id (05-schema.md §5).
	CountrySentinelID(ctx context.Context) (int32, error)
	TrancoInsertAborted(ctx context.Context, arg TrancoInsertAbortedParams) error
	TrancoInsertProvenance(ctx context.Context, arg TrancoInsertProvenanceParams) (int64, error)
	TrancoLastSuccessAt(ctx context.Context) (pgtype.Timestamptz, error)
	// db/query/tranco.sql — sqlc query source (layout: 05-schema.md §10.2).
	TrancoLatestSuccessListID(ctx context.Context) (string, error)
	TrancoListWasAborted(ctx context.Context, listID string) (bool, error)
	TrancoRecentImports(ctx context.Context) ([]TrancoImport, error)
}

var _ Querier = (*Queries)(nil)
