// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DomainResourceList = `-- name: DomainResourceList :many

SELECT rh.host, rh.aaaa_status, dr.source, dr.required, dr.first_seen, dr.last_seen, rh.last_checked_at
FROM domain_resource dr
JOIN resource_host rh ON rh.id = dr.resource_host_id
WHERE dr.domain_id = $1
ORDER BY rh.host
`

type DomainResourceListRow struct {
	Host          string             `json:"host"`
	AaaaStatus    *Ipv6Status        `json:"aaaa_status"`
	Source        ResourceSource     `json:"source"`
	Required      bool               `json:"required"`
	FirstSeen     pgtype.Timestamptz `json:"first_seen"`
	LastSeen      pgtype.Timestamptz `json:"last_seen"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
}

// Resource-dependency reads (07 §4.11). Forward list is bounded small
// (exact count, no cursor); the reverse dependents list is served by the
// domainlist builder.
func (q *Queries) DomainResourceList(ctx context.Context, domainID int64) ([]DomainResourceListRow, error) {
	rows, err := q.db.Query(ctx, DomainResourceList, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainResourceListRow{}
	for rows.Next() {
		var i DomainResourceListRow
		if err := rows.Scan(
			&i.Host,
			&i.AaaaStatus,
			&i.Source,
			&i.Required,
			&i.FirstSeen,
			&i.LastSeen,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ResourceHostByHost = `-- name: ResourceHostByHost :one
SELECT id, host, aaaa_status, dependent_count, last_checked_at
FROM resource_host WHERE host = $1
`

type ResourceHostByHostRow struct {
	ID             int64              `json:"id"`
	Host           string             `json:"host"`
	AaaaStatus     *Ipv6Status        `json:"aaaa_status"`
	DependentCount int32              `json:"dependent_count"`
	LastCheckedAt  pgtype.Timestamptz `json:"last_checked_at"`
}

func (q *Queries) ResourceHostByHost(ctx context.Context, host string) (ResourceHostByHostRow, error) {
	row := q.db.QueryRow(ctx, ResourceHostByHost, host)
	var i ResourceHostByHostRow
	err := row.Scan(
		&i.ID,
		&i.Host,
		&i.AaaaStatus,
		&i.DependentCount,
		&i.LastCheckedAt,
	)
	return i, err
}
