// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan.sql

package db

import (
	"context"
)

const LatestScanDetail = `-- name: LatestScanDetail :one

SELECT details FROM scan_detail WHERE domain_id = $1 ORDER BY ts DESC LIMIT 1
`

// db/query/scan.sql — sqlc query source (layout: 05-schema.md §10.2).
// The detail page's evidence block: the latest scan_detail payload
// (07 §4.3 ?include=evidence).
func (q *Queries) LatestScanDetail(ctx context.Context, domainID int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, LatestScanDetail, domainID)
	var details []byte
	err := row.Scan(&details)
	return details, err
}
