// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_candidate.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const DetectServiceCandidatesApex = `-- name: DetectServiceCandidatesApex :execrows


INSERT INTO service_candidate (domain_id, reasons)
SELECT d.id, ARRAY['apex_www_no_record']
FROM domain d
WHERE d.rank IS NOT NULL AND NOT d.disabled
  AND d.base_status = 'no_record'
  AND d.www_status  = 'not_applicable'
  AND d.ns_status IN ('supported', 'unsupported')
ON CONFLICT (domain_id) DO NOTHING
`

// db/query/service_candidate.sql — sqlc query source (layout: 05-schema.md §10.2).
// Tick step 4 — candidate detection, never auto-disable (04 §9).
func (q *Queries) DetectServiceCandidatesApex(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, DetectServiceCandidatesApex)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DetectServiceCandidatesIndegree = `-- name: DetectServiceCandidatesIndegree :execrows
INSERT INTO service_candidate (domain_id, reasons)
SELECT d.id, ARRAY['high_dependency_indegree']
FROM resource_host rh
JOIN domain d ON d.host = rh.host
WHERE rh.dependent_count >= $1
  AND d.rank IS NOT NULL AND NOT d.disabled
ON CONFLICT (domain_id) DO NOTHING
`

func (q *Queries) DetectServiceCandidatesIndegree(ctx context.Context, indegreeThreshold int32) (int64, error) {
	result, err := q.db.Exec(ctx, DetectServiceCandidatesIndegree, indegreeThreshold)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ServiceCandidateList = `-- name: ServiceCandidateList :many

SELECT sc.domain_id, d.host, sc.reasons, sc.detected_at
FROM service_candidate sc
JOIN domain d ON d.id = sc.domain_id
WHERE NOT sc.dismissed
ORDER BY sc.detected_at
`

type ServiceCandidateListRow struct {
	DomainID   int64              `json:"domain_id"`
	Host       string             `json:"host"`
	Reasons    []string           `json:"reasons"`
	DetectedAt pgtype.Timestamptz `json:"detected_at"`
}

// Operator triage (P2.14; 04 — service/manual lifecycle).
func (q *Queries) ServiceCandidateList(ctx context.Context) ([]ServiceCandidateListRow, error) {
	rows, err := q.db.Query(ctx, ServiceCandidateList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceCandidateListRow{}
	for rows.Next() {
		var i ServiceCandidateListRow
		if err := rows.Scan(
			&i.DomainID,
			&i.Host,
			&i.Reasons,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ServiceCandidateResolve = `-- name: ServiceCandidateResolve :execrows
UPDATE service_candidate SET dismissed = true
WHERE domain_id = (SELECT id FROM domain WHERE host = $1) AND NOT dismissed
`

func (q *Queries) ServiceCandidateResolve(ctx context.Context, host string) (int64, error) {
	result, err := q.db.Exec(ctx, ServiceCandidateResolve, host)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
