// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_candidate.sql

package db

import (
	"context"
)

const DetectServiceCandidatesApex = `-- name: DetectServiceCandidatesApex :execrows


INSERT INTO service_candidate (domain_id, reasons)
SELECT d.id, ARRAY['apex_www_no_record']
FROM domain d
WHERE d.rank IS NOT NULL AND NOT d.disabled
  AND d.base_status = 'no_record'
  AND d.www_status  = 'not_applicable'
  AND d.ns_status IN ('supported', 'unsupported')
ON CONFLICT (domain_id) DO NOTHING
`

// db/query/service_candidate.sql — sqlc query source (layout: 05-schema.md §10.2).
// Tick step 4 — candidate detection, never auto-disable (04 §9).
func (q *Queries) DetectServiceCandidatesApex(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, DetectServiceCandidatesApex)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DetectServiceCandidatesIndegree = `-- name: DetectServiceCandidatesIndegree :execrows
INSERT INTO service_candidate (domain_id, reasons)
SELECT d.id, ARRAY['high_dependency_indegree']
FROM resource_host rh
JOIN domain d ON d.host = rh.host
WHERE rh.dependent_count >= $1
  AND d.rank IS NOT NULL AND NOT d.disabled
ON CONFLICT (domain_id) DO NOTHING
`

func (q *Queries) DetectServiceCandidatesIndegree(ctx context.Context, indegreeThreshold int32) (int64, error) {
	result, err := q.db.Exec(ctx, DetectServiceCandidatesIndegree, indegreeThreshold)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
