// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shame.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ShameEligibleDomain = `-- name: ShameEligibleDomain :one


SELECT id, classification FROM domain
WHERE host = $1 AND kind = 'apex' AND rank IS NOT NULL AND NOT disabled
`

type ShameEligibleDomainRow struct {
	ID             int64          `json:"id"`
	Classification Classification `json:"classification"`
}

// db/query/shame.sql — sqlc query source (layout: 05-schema.md §10.2).
// v6ctl shame — the single top_shame write path (06-ingest.md §7).
func (q *Queries) ShameEligibleDomain(ctx context.Context, host string) (ShameEligibleDomainRow, error) {
	row := q.db.QueryRow(ctx, ShameEligibleDomain, host)
	var i ShameEligibleDomainRow
	err := row.Scan(&i.ID, &i.Classification)
	return i, err
}

const ShameList = `-- name: ShameList :many
SELECT d.host, d.rank, d.classification, ts.reason, ts.added_at,
       (d.classification = 'sinner' AND d.rank IS NOT NULL AND NOT d.disabled) AS visible
FROM top_shame ts
JOIN domain d ON d.id = ts.domain_id
ORDER BY d.rank NULLS LAST
`

type ShameListRow struct {
	Host           string             `json:"host"`
	Rank           *int32             `json:"rank"`
	Classification Classification     `json:"classification"`
	Reason         *string            `json:"reason"`
	AddedAt        pgtype.Timestamptz `json:"added_at"`
	Visible        *bool              `json:"visible"`
}

func (q *Queries) ShameList(ctx context.Context) ([]ShameListRow, error) {
	rows, err := q.db.Query(ctx, ShameList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShameListRow{}
	for rows.Next() {
		var i ShameListRow
		if err := rows.Scan(
			&i.Host,
			&i.Rank,
			&i.Classification,
			&i.Reason,
			&i.AddedAt,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ShameRemove = `-- name: ShameRemove :execrows
DELETE FROM top_shame WHERE domain_id = (SELECT id FROM domain WHERE host = $1)
`

func (q *Queries) ShameRemove(ctx context.Context, host string) (int64, error) {
	result, err := q.db.Exec(ctx, ShameRemove, host)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ShameUpsert = `-- name: ShameUpsert :exec
INSERT INTO top_shame (domain_id, reason)
VALUES ($1, $2)
ON CONFLICT (domain_id) DO UPDATE SET reason = EXCLUDED.reason
`

type ShameUpsertParams struct {
	DomainID int64   `json:"domain_id"`
	Reason   *string `json:"reason"`
}

func (q *Queries) ShameUpsert(ctx context.Context, arg ShameUpsertParams) error {
	_, err := q.db.Exec(ctx, ShameUpsert, arg.DomainID, arg.Reason)
	return err
}
