// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
)

const SnapshotASNDaily = `-- name: SnapshotASNDaily :exec
INSERT INTO stats_asn_daily (day, asn_id, domains, v6_domains, sinners, heroes)
SELECT
  CURRENT_DATE::timestamptz, asn_id,
  count(*),
  count(*) FILTER (WHERE classification IN ('partial','hero')),
  count(*) FILTER (WHERE classification = 'sinner'),
  count(*) FILTER (WHERE classification = 'hero')
FROM domain
WHERE rank IS NOT NULL AND NOT disabled
GROUP BY asn_id
ON CONFLICT (asn_id, day) DO UPDATE SET
  domains    = excluded.domains,
  v6_domains = excluded.v6_domains,
  sinners    = excluded.sinners,
  heroes     = excluded.heroes
`

func (q *Queries) SnapshotASNDaily(ctx context.Context) error {
	_, err := q.db.Exec(ctx, SnapshotASNDaily)
	return err
}

const SnapshotCampaignDaily = `-- name: SnapshotCampaignDaily :exec
INSERT INTO stats_campaign_daily (
  day, campaign_id, domains, v6_ready, sinners, partial, heroes,
  base_supported, www_supported, ns_supported, mx_supported, conn_supported)
SELECT
  CURRENT_DATE, cd.campaign_id,
  count(*),
  count(*) FILTER (WHERE d.base_status = 'supported'
                     AND d.ns_status  = 'supported'
                     AND d.www_status IN ('supported','not_applicable')),
  count(*) FILTER (WHERE d.classification = 'sinner'),
  count(*) FILTER (WHERE d.classification = 'partial'),
  count(*) FILTER (WHERE d.classification = 'hero'),
  count(*) FILTER (WHERE d.base_status = 'supported'),
  count(*) FILTER (WHERE d.www_status  = 'supported'),
  count(*) FILTER (WHERE d.ns_status   = 'supported'),
  count(*) FILTER (WHERE d.mx_status   = 'supported'),
  count(*) FILTER (WHERE d.conn_status = 'supported')
FROM campaign_domain cd
JOIN campaign c ON c.id = cd.campaign_id AND NOT c.disabled
JOIN domain   d ON d.id = cd.domain_id   AND NOT d.disabled
GROUP BY cd.campaign_id
ON CONFLICT (day, campaign_id) DO UPDATE SET
  domains        = excluded.domains,
  v6_ready       = excluded.v6_ready,
  sinners        = excluded.sinners,
  partial        = excluded.partial,
  heroes         = excluded.heroes,
  base_supported = excluded.base_supported,
  www_supported  = excluded.www_supported,
  ns_supported   = excluded.ns_supported,
  mx_supported   = excluded.mx_supported,
  conn_supported = excluded.conn_supported
`

func (q *Queries) SnapshotCampaignDaily(ctx context.Context) error {
	_, err := q.db.Exec(ctx, SnapshotCampaignDaily)
	return err
}

const SnapshotCountryDaily = `-- name: SnapshotCountryDaily :exec
INSERT INTO stats_country_daily (
  day, country_id, domains, sinners, partial, heroes, base_supported, conn_supported)
SELECT
  CURRENT_DATE, country_id,
  count(*),
  count(*) FILTER (WHERE classification = 'sinner'),
  count(*) FILTER (WHERE classification = 'partial'),
  count(*) FILTER (WHERE classification = 'hero'),
  count(*) FILTER (WHERE base_status = 'supported'),
  count(*) FILTER (WHERE conn_status = 'supported')
FROM domain
WHERE rank IS NOT NULL AND NOT disabled
GROUP BY country_id
ON CONFLICT (day, country_id) DO UPDATE SET
  domains        = excluded.domains,
  sinners        = excluded.sinners,
  partial        = excluded.partial,
  heroes         = excluded.heroes,
  base_supported = excluded.base_supported,
  conn_supported = excluded.conn_supported
`

func (q *Queries) SnapshotCountryDaily(ctx context.Context) error {
	_, err := q.db.Exec(ctx, SnapshotCountryDaily)
	return err
}

const SnapshotGlobalDaily = `-- name: SnapshotGlobalDaily :exec


INSERT INTO stats_global_daily (
  day, domains, sinners, partial, heroes, gold, inactive, unknown, disabled,
  base_supported, www_supported, ns_supported, mx_supported, conn_supported,
  resources_supported, top_heroes, top_nameserver, generated_at)
SELECT
  CURRENT_DATE,
  count(*) FILTER (WHERE NOT disabled),
  count(*) FILTER (WHERE NOT disabled AND classification = 'sinner'),
  count(*) FILTER (WHERE NOT disabled AND classification = 'partial'),
  count(*) FILTER (WHERE NOT disabled AND classification = 'hero'),
  count(*) FILTER (WHERE NOT disabled AND gold),
  count(*) FILTER (WHERE NOT disabled AND classification = 'inactive'),
  count(*) FILTER (WHERE NOT disabled AND classification = 'unknown'),
  count(*) FILTER (WHERE disabled),
  count(*) FILTER (WHERE NOT disabled AND base_status  = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND www_status   = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND ns_status    = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND mx_status    = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND conn_status  = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND resources_status = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND rank <= 1000
                     AND base_status = 'supported'
                     AND www_status IS DISTINCT FROM 'unsupported'),
  count(*) FILTER (WHERE NOT disabled AND rank <= 1000
                     AND ns_status = 'supported'),
  now()
FROM domain
WHERE rank IS NOT NULL
ON CONFLICT (day) DO UPDATE SET
  domains             = excluded.domains,
  sinners             = excluded.sinners,
  partial             = excluded.partial,
  heroes              = excluded.heroes,
  gold                = excluded.gold,
  inactive            = excluded.inactive,
  unknown             = excluded.unknown,
  disabled            = excluded.disabled,
  base_supported      = excluded.base_supported,
  www_supported       = excluded.www_supported,
  ns_supported        = excluded.ns_supported,
  mx_supported        = excluded.mx_supported,
  conn_supported      = excluded.conn_supported,
  resources_supported = excluded.resources_supported,
  top_heroes          = excluded.top_heroes,
  top_nameserver      = excluded.top_nameserver,
  generated_at        = excluded.generated_at
`

// db/query/stats.sql — sqlc query source (layout: 05-schema.md §10.2).
// Tick step 2 — the four confirmed-state snapshot upserts (06-ingest.md §10).
func (q *Queries) SnapshotGlobalDaily(ctx context.Context) error {
	_, err := q.db.Exec(ctx, SnapshotGlobalDaily)
	return err
}
