// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ExportRows = `-- name: ExportRows :many
SELECT d.host, d.rank, d.kind, p.host AS parent,
       d.classification, d.class_flags, d.saint,
       d.base_status, d.www_status, d.ns_status,
       d.mx_status, d.conn_status, d.resources_status,
       d.base_since, d.www_since, d.ns_since, d.mx_since, d.conn_since, d.resources_since,
       d.tld, c.code, a.number AS asn,
       dp.name AS dns_provider, d.hosting_provider, d.last_checked_at
FROM domain d
JOIN country c ON c.id = d.country_id
JOIN asn a ON a.id = d.asn_id
LEFT JOIN dns_provider dp ON dp.id = d.dns_provider_id
LEFT JOIN domain p ON p.id = d.parent_id
WHERE NOT d.disabled
  AND (NOT $1::bool OR d.rank IS NOT NULL)
  AND ($2::int = 0 OR d.rank <= $2)
ORDER BY d.rank ASC NULLS LAST, d.id ASC
`

type ExportRowsParams struct {
	RankedOnly bool  `json:"ranked_only"`
	MaxRank    int32 `json:"max_rank"`
}

type ExportRowsRow struct {
	Host            string             `json:"host"`
	Rank            *int32             `json:"rank"`
	Kind            DomainKind         `json:"kind"`
	Parent          *string            `json:"parent"`
	Classification  Classification     `json:"classification"`
	ClassFlags      []string           `json:"class_flags"`
	Saint           bool               `json:"saint"`
	BaseStatus      *Ipv6Status        `json:"base_status"`
	WwwStatus       *Ipv6Status        `json:"www_status"`
	NsStatus        *Ipv6Status        `json:"ns_status"`
	MxStatus        *Ipv6Status        `json:"mx_status"`
	ConnStatus      *Ipv6Status        `json:"conn_status"`
	ResourcesStatus *Ipv6Status        `json:"resources_status"`
	BaseSince       pgtype.Timestamptz `json:"base_since"`
	WwwSince        pgtype.Timestamptz `json:"www_since"`
	NsSince         pgtype.Timestamptz `json:"ns_since"`
	MxSince         pgtype.Timestamptz `json:"mx_since"`
	ConnSince       pgtype.Timestamptz `json:"conn_since"`
	ResourcesSince  pgtype.Timestamptz `json:"resources_since"`
	Tld             *string            `json:"tld"`
	Code            string             `json:"code"`
	Asn             int64              `json:"asn"`
	DnsProvider     *string            `json:"dns_provider"`
	HostingProvider *string            `json:"hosting_provider"`
	LastCheckedAt   pgtype.Timestamptz `json:"last_checked_at"`
}

// The nightly dataset export (07 §5.3): one parameterized read covers the
// three tiers — ranked_only for top100k/top1m, max_rank 0 = unbounded.
func (q *Queries) ExportRows(ctx context.Context, arg ExportRowsParams) ([]ExportRowsRow, error) {
	rows, err := q.db.Query(ctx, ExportRows, arg.RankedOnly, arg.MaxRank)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportRowsRow{}
	for rows.Next() {
		var i ExportRowsRow
		if err := rows.Scan(
			&i.Host,
			&i.Rank,
			&i.Kind,
			&i.Parent,
			&i.Classification,
			&i.ClassFlags,
			&i.Saint,
			&i.BaseStatus,
			&i.WwwStatus,
			&i.NsStatus,
			&i.MxStatus,
			&i.ConnStatus,
			&i.ResourcesStatus,
			&i.BaseSince,
			&i.WwwSince,
			&i.NsSince,
			&i.MxSince,
			&i.ConnSince,
			&i.ResourcesSince,
			&i.Tld,
			&i.Code,
			&i.Asn,
			&i.DnsProvider,
			&i.HostingProvider,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SnapshotASNDaily = `-- name: SnapshotASNDaily :exec
INSERT INTO stats_asn_daily (day, asn_id, domains, v6_domains, sinners, heroes)
SELECT
  CURRENT_DATE::timestamptz, asn_id,
  count(*),
  count(*) FILTER (WHERE classification IN ('partial','hero')),
  count(*) FILTER (WHERE classification = 'sinner'),
  count(*) FILTER (WHERE classification = 'hero')
FROM domain
WHERE rank IS NOT NULL AND NOT disabled
GROUP BY asn_id
ON CONFLICT (asn_id, day) DO UPDATE SET
  domains    = excluded.domains,
  v6_domains = excluded.v6_domains,
  sinners    = excluded.sinners,
  heroes     = excluded.heroes
`

func (q *Queries) SnapshotASNDaily(ctx context.Context) error {
	_, err := q.db.Exec(ctx, SnapshotASNDaily)
	return err
}

const SnapshotCampaignDaily = `-- name: SnapshotCampaignDaily :exec
INSERT INTO stats_campaign_daily (
  day, campaign_id, domains, v6_ready, sinners, partial, heroes,
  base_supported, www_supported, ns_supported, mx_supported, conn_supported)
SELECT
  CURRENT_DATE, cd.campaign_id,
  count(*),
  count(*) FILTER (WHERE d.base_status = 'supported'
                     AND d.ns_status  = 'supported'
                     AND d.www_status IN ('supported','not_applicable')),
  count(*) FILTER (WHERE d.classification = 'sinner'),
  count(*) FILTER (WHERE d.classification = 'partial'),
  count(*) FILTER (WHERE d.classification = 'hero'),
  count(*) FILTER (WHERE d.base_status = 'supported'),
  count(*) FILTER (WHERE d.www_status  = 'supported'),
  count(*) FILTER (WHERE d.ns_status   = 'supported'),
  count(*) FILTER (WHERE d.mx_status   = 'supported'),
  count(*) FILTER (WHERE d.conn_status = 'supported')
FROM campaign_domain cd
JOIN campaign c ON c.id = cd.campaign_id AND NOT c.disabled
JOIN domain   d ON d.id = cd.domain_id   AND NOT d.disabled
GROUP BY cd.campaign_id
ON CONFLICT (day, campaign_id) DO UPDATE SET
  domains        = excluded.domains,
  v6_ready       = excluded.v6_ready,
  sinners        = excluded.sinners,
  partial        = excluded.partial,
  heroes         = excluded.heroes,
  base_supported = excluded.base_supported,
  www_supported  = excluded.www_supported,
  ns_supported   = excluded.ns_supported,
  mx_supported   = excluded.mx_supported,
  conn_supported = excluded.conn_supported
`

func (q *Queries) SnapshotCampaignDaily(ctx context.Context) error {
	_, err := q.db.Exec(ctx, SnapshotCampaignDaily)
	return err
}

const SnapshotCountryDaily = `-- name: SnapshotCountryDaily :exec
INSERT INTO stats_country_daily (
  day, country_id, domains, sinners, partial, heroes, base_supported, conn_supported)
SELECT
  CURRENT_DATE, country_id,
  count(*),
  count(*) FILTER (WHERE classification = 'sinner'),
  count(*) FILTER (WHERE classification = 'partial'),
  count(*) FILTER (WHERE classification = 'hero'),
  count(*) FILTER (WHERE base_status = 'supported'),
  count(*) FILTER (WHERE conn_status = 'supported')
FROM domain
WHERE rank IS NOT NULL AND NOT disabled
GROUP BY country_id
ON CONFLICT (day, country_id) DO UPDATE SET
  domains        = excluded.domains,
  sinners        = excluded.sinners,
  partial        = excluded.partial,
  heroes         = excluded.heroes,
  base_supported = excluded.base_supported,
  conn_supported = excluded.conn_supported
`

func (q *Queries) SnapshotCountryDaily(ctx context.Context) error {
	_, err := q.db.Exec(ctx, SnapshotCountryDaily)
	return err
}

const SnapshotGlobalDaily = `-- name: SnapshotGlobalDaily :exec


INSERT INTO stats_global_daily (
  day, domains, sinners, partial, heroes, saints, inactive, unknown, disabled,
  base_supported, www_supported, ns_supported, mx_supported, conn_supported,
  resources_supported, top_heroes, top_nameserver, generated_at)
SELECT
  CURRENT_DATE,
  count(*) FILTER (WHERE NOT disabled),
  count(*) FILTER (WHERE NOT disabled AND classification = 'sinner'),
  count(*) FILTER (WHERE NOT disabled AND classification = 'partial'),
  count(*) FILTER (WHERE NOT disabled AND classification = 'hero'),
  count(*) FILTER (WHERE NOT disabled AND saint),
  count(*) FILTER (WHERE NOT disabled AND classification = 'inactive'),
  count(*) FILTER (WHERE NOT disabled AND classification = 'unknown'),
  count(*) FILTER (WHERE disabled),
  count(*) FILTER (WHERE NOT disabled AND base_status  = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND www_status   = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND ns_status    = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND mx_status    = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND conn_status  = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND resources_status = 'supported'),
  count(*) FILTER (WHERE NOT disabled AND rank <= 1000
                     AND base_status = 'supported'
                     AND www_status IS DISTINCT FROM 'unsupported'),
  count(*) FILTER (WHERE NOT disabled AND rank <= 1000
                     AND ns_status = 'supported'),
  now()
FROM domain
WHERE rank IS NOT NULL
ON CONFLICT (day) DO UPDATE SET
  domains             = excluded.domains,
  sinners             = excluded.sinners,
  partial             = excluded.partial,
  heroes              = excluded.heroes,
  saints              = excluded.saints,
  inactive            = excluded.inactive,
  unknown             = excluded.unknown,
  disabled            = excluded.disabled,
  base_supported      = excluded.base_supported,
  www_supported       = excluded.www_supported,
  ns_supported        = excluded.ns_supported,
  mx_supported        = excluded.mx_supported,
  conn_supported      = excluded.conn_supported,
  resources_supported = excluded.resources_supported,
  top_heroes          = excluded.top_heroes,
  top_nameserver      = excluded.top_nameserver,
  generated_at        = excluded.generated_at
`

// db/query/stats.sql — sqlc query source (layout: 05-schema.md §10.2).
// Tick step 2 — the four confirmed-state snapshot upserts (06-ingest.md §10).
func (q *Queries) SnapshotGlobalDaily(ctx context.Context) error {
	_, err := q.db.Exec(ctx, SnapshotGlobalDaily)
	return err
}

const StatsASNRange = `-- name: StatsASNRange :many
SELECT day, domains, v6_domains, sinners, heroes
FROM stats_asn_daily
WHERE asn_id = $1 AND day >= $2::timestamptz AND day <= $3::timestamptz
ORDER BY day ASC
`

type StatsASNRangeParams struct {
	AsnID   int32              `json:"asn_id"`
	FromDay pgtype.Timestamptz `json:"from_day"`
	ToDay   pgtype.Timestamptz `json:"to_day"`
}

type StatsASNRangeRow struct {
	Day       pgtype.Timestamptz `json:"day"`
	Domains   *int32             `json:"domains"`
	V6Domains *int32             `json:"v6_domains"`
	Sinners   *int32             `json:"sinners"`
	Heroes    *int32             `json:"heroes"`
}

func (q *Queries) StatsASNRange(ctx context.Context, arg StatsASNRangeParams) ([]StatsASNRangeRow, error) {
	rows, err := q.db.Query(ctx, StatsASNRange, arg.AsnID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsASNRangeRow{}
	for rows.Next() {
		var i StatsASNRangeRow
		if err := rows.Scan(
			&i.Day,
			&i.Domains,
			&i.V6Domains,
			&i.Sinners,
			&i.Heroes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const StatsCampaignRange = `-- name: StatsCampaignRange :many
SELECT day, domains, v6_ready, sinners, partial, heroes, base_supported,
       www_supported, ns_supported, mx_supported, conn_supported
FROM stats_campaign_daily
WHERE campaign_id = $1 AND day >= $2 AND day <= $3
ORDER BY day ASC
`

type StatsCampaignRangeParams struct {
	CampaignID int32       `json:"campaign_id"`
	FromDay    pgtype.Date `json:"from_day"`
	ToDay      pgtype.Date `json:"to_day"`
}

type StatsCampaignRangeRow struct {
	Day           pgtype.Date `json:"day"`
	Domains       *int32      `json:"domains"`
	V6Ready       *int32      `json:"v6_ready"`
	Sinners       *int32      `json:"sinners"`
	Partial       *int32      `json:"partial"`
	Heroes        *int32      `json:"heroes"`
	BaseSupported *int32      `json:"base_supported"`
	WwwSupported  *int32      `json:"www_supported"`
	NsSupported   *int32      `json:"ns_supported"`
	MxSupported   *int32      `json:"mx_supported"`
	ConnSupported *int32      `json:"conn_supported"`
}

func (q *Queries) StatsCampaignRange(ctx context.Context, arg StatsCampaignRangeParams) ([]StatsCampaignRangeRow, error) {
	rows, err := q.db.Query(ctx, StatsCampaignRange, arg.CampaignID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsCampaignRangeRow{}
	for rows.Next() {
		var i StatsCampaignRangeRow
		if err := rows.Scan(
			&i.Day,
			&i.Domains,
			&i.V6Ready,
			&i.Sinners,
			&i.Partial,
			&i.Heroes,
			&i.BaseSupported,
			&i.WwwSupported,
			&i.NsSupported,
			&i.MxSupported,
			&i.ConnSupported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const StatsCountryRange = `-- name: StatsCountryRange :many
SELECT day, domains, sinners, partial, heroes, base_supported, conn_supported
FROM stats_country_daily
WHERE country_id = $1 AND day >= $2 AND day <= $3
ORDER BY day ASC
`

type StatsCountryRangeParams struct {
	CountryID int32       `json:"country_id"`
	FromDay   pgtype.Date `json:"from_day"`
	ToDay     pgtype.Date `json:"to_day"`
}

type StatsCountryRangeRow struct {
	Day           pgtype.Date `json:"day"`
	Domains       *int32      `json:"domains"`
	Sinners       *int32      `json:"sinners"`
	Partial       *int32      `json:"partial"`
	Heroes        *int32      `json:"heroes"`
	BaseSupported *int32      `json:"base_supported"`
	ConnSupported *int32      `json:"conn_supported"`
}

func (q *Queries) StatsCountryRange(ctx context.Context, arg StatsCountryRangeParams) ([]StatsCountryRangeRow, error) {
	rows, err := q.db.Query(ctx, StatsCountryRange, arg.CountryID, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsCountryRangeRow{}
	for rows.Next() {
		var i StatsCountryRangeRow
		if err := rows.Scan(
			&i.Day,
			&i.Domains,
			&i.Sinners,
			&i.Partial,
			&i.Heroes,
			&i.BaseSupported,
			&i.ConnSupported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const StatsGeneration = `-- name: StatsGeneration :one
SELECT day, generated_at FROM stats_global_daily ORDER BY day DESC LIMIT 1
`

type StatsGenerationRow struct {
	Day         pgtype.Date        `json:"day"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
}

// The envelope meta source (07-api.md §2.4): generation = YYYYMMDD of
// max(stats_global_daily.day); as_of = its generated_at, falling back to
// day at 00:00:00Z when NULL (the day-0 seed row).
func (q *Queries) StatsGeneration(ctx context.Context) (StatsGenerationRow, error) {
	row := q.db.QueryRow(ctx, StatsGeneration)
	var i StatsGenerationRow
	err := row.Scan(&i.Day, &i.GeneratedAt)
	return i, err
}

const StatsGlobalRange = `-- name: StatsGlobalRange :many

SELECT day, domains, sinners, partial, heroes, saints, inactive, unknown, disabled,
       base_supported, www_supported, ns_supported, mx_supported, conn_supported,
       resources_supported, top_heroes, top_nameserver
FROM stats_global_daily
WHERE day >= $1 AND day <= $2
ORDER BY day ASC
`

type StatsGlobalRangeParams struct {
	FromDay pgtype.Date `json:"from_day"`
	ToDay   pgtype.Date `json:"to_day"`
}

type StatsGlobalRangeRow struct {
	Day                pgtype.Date `json:"day"`
	Domains            *int32      `json:"domains"`
	Sinners            *int32      `json:"sinners"`
	Partial            *int32      `json:"partial"`
	Heroes             *int32      `json:"heroes"`
	Saints             *int32      `json:"saints"`
	Inactive           *int32      `json:"inactive"`
	Unknown            *int32      `json:"unknown"`
	Disabled           *int32      `json:"disabled"`
	BaseSupported      *int32      `json:"base_supported"`
	WwwSupported       *int32      `json:"www_supported"`
	NsSupported        *int32      `json:"ns_supported"`
	MxSupported        *int32      `json:"mx_supported"`
	ConnSupported      *int32      `json:"conn_supported"`
	ResourcesSupported *int32      `json:"resources_supported"`
	TopHeroes          *int32      `json:"top_heroes"`
	TopNameserver      *int32      `json:"top_nameserver"`
}

// The §4.10 time-series reads: bounded windows (≤366 rows/yr), ascending;
// weekly sampling happens API-side over the fetched window.
func (q *Queries) StatsGlobalRange(ctx context.Context, arg StatsGlobalRangeParams) ([]StatsGlobalRangeRow, error) {
	rows, err := q.db.Query(ctx, StatsGlobalRange, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatsGlobalRangeRow{}
	for rows.Next() {
		var i StatsGlobalRangeRow
		if err := rows.Scan(
			&i.Day,
			&i.Domains,
			&i.Sinners,
			&i.Partial,
			&i.Heroes,
			&i.Saints,
			&i.Inactive,
			&i.Unknown,
			&i.Disabled,
			&i.BaseSupported,
			&i.WwwSupported,
			&i.NsSupported,
			&i.MxSupported,
			&i.ConnSupported,
			&i.ResourcesSupported,
			&i.TopHeroes,
			&i.TopNameserver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
