// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tranco.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const TrancoInsertAborted = `-- name: TrancoInsertAborted :exec
INSERT INTO tranco_import
  (list_id, list_date, line_count, rejected_count, duplicate_count, aborted, note)
VALUES ($1, $2, $3, $4, $5, true, $6)
`

type TrancoInsertAbortedParams struct {
	ListID         string      `json:"list_id"`
	ListDate       pgtype.Date `json:"list_date"`
	LineCount      *int32      `json:"line_count"`
	RejectedCount  *int32      `json:"rejected_count"`
	DuplicateCount *int32      `json:"duplicate_count"`
	Note           *string     `json:"note"`
}

func (q *Queries) TrancoInsertAborted(ctx context.Context, arg TrancoInsertAbortedParams) error {
	_, err := q.db.Exec(ctx, TrancoInsertAborted,
		arg.ListID,
		arg.ListDate,
		arg.LineCount,
		arg.RejectedCount,
		arg.DuplicateCount,
		arg.Note,
	)
	return err
}

const TrancoInsertProvenance = `-- name: TrancoInsertProvenance :execrows
INSERT INTO tranco_import
  (list_id, list_date, line_count, imported_count, delisted,
   rejected_count, duplicate_count, aborted, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, false, NULL)
ON CONFLICT (list_id) WHERE NOT aborted DO NOTHING
`

type TrancoInsertProvenanceParams struct {
	ListID         string      `json:"list_id"`
	ListDate       pgtype.Date `json:"list_date"`
	LineCount      *int32      `json:"line_count"`
	ImportedCount  *int32      `json:"imported_count"`
	Delisted       *int32      `json:"delisted"`
	RejectedCount  *int32      `json:"rejected_count"`
	DuplicateCount *int32      `json:"duplicate_count"`
}

func (q *Queries) TrancoInsertProvenance(ctx context.Context, arg TrancoInsertProvenanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, TrancoInsertProvenance,
		arg.ListID,
		arg.ListDate,
		arg.LineCount,
		arg.ImportedCount,
		arg.Delisted,
		arg.RejectedCount,
		arg.DuplicateCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const TrancoLastSuccessAt = `-- name: TrancoLastSuccessAt :one
SELECT max(imported_at)::timestamptz FROM tranco_import WHERE aborted = false
`

func (q *Queries) TrancoLastSuccessAt(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, TrancoLastSuccessAt)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const TrancoLatestSuccessListID = `-- name: TrancoLatestSuccessListID :one

SELECT list_id FROM tranco_import WHERE NOT aborted ORDER BY imported_at DESC LIMIT 1
`

// db/query/tranco.sql — sqlc query source (layout: 05-schema.md §10.2).
func (q *Queries) TrancoLatestSuccessListID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, TrancoLatestSuccessListID)
	var list_id string
	err := row.Scan(&list_id)
	return list_id, err
}

const TrancoListWasAborted = `-- name: TrancoListWasAborted :one
SELECT EXISTS(SELECT 1 FROM tranco_import WHERE list_id = $1 AND aborted)
`

func (q *Queries) TrancoListWasAborted(ctx context.Context, listID string) (bool, error) {
	row := q.db.QueryRow(ctx, TrancoListWasAborted, listID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const TrancoRecentImports = `-- name: TrancoRecentImports :many
SELECT id, list_id, list_date, line_count, imported_count, delisted,
       rejected_count, duplicate_count, aborted, note, imported_at
FROM tranco_import ORDER BY imported_at DESC LIMIT 10
`

func (q *Queries) TrancoRecentImports(ctx context.Context) ([]TrancoImport, error) {
	rows, err := q.db.Query(ctx, TrancoRecentImports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrancoImport{}
	for rows.Next() {
		var i TrancoImport
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.ListDate,
			&i.LineCount,
			&i.ImportedCount,
			&i.Delisted,
			&i.RejectedCount,
			&i.DuplicateCount,
			&i.Aborted,
			&i.Note,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
